version: 2
# Touched on 2026-02-17 to force Dependabot to re-evaluate immediately.
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "automated"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
