// AUTO-GENERATED from the ScaffBench 3 run summary. Do not edit rows by hand.
// Suite 3.0, harness 3.1.0, prompt path, high effort, 1 trial per spec.
import type { ScaffbenchCell, ScaffbenchModel } from "@web/components/home/scaffbench-2-data";

export const SCAFFBENCH3_MODELS: readonly ScaffbenchModel[] = [
  {
    key: "opencode/x-preview-f-free|high",
    model: "opencode/x-preview-f-free",
    effort: "high",
    effectiveReasoning: "high",
    provider: "opencode",
    label: "Ox Alpha Free",
    sortIndex: 69,
    eligibility: "ranked",
  },
];

export const SCAFFBENCH3_CELLS: readonly ScaffbenchCell[] = [
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "react-native-expo",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    lines: 1168,
    costUsd: 0,
    outTokens: 22713,
    steps: 0,
    durationMs: 953958,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "python-ingestion-api",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    lines: 944,
    costUsd: 0,
    outTokens: 16545,
    steps: 0,
    durationMs: 2226857,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "java-spring-jooq-keycloak",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 93,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 1660,
    costUsd: 0,
    outTokens: 36450,
    steps: 0,
    durationMs: 2916988,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "frontier-effect-eventsourcing",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    lines: 1050,
    costUsd: 0,
    outTokens: 32816,
    steps: 0,
    durationMs: 846922,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "go-realtime-api",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 10655,
    costUsd: 0,
    outTokens: 42082,
    steps: 0,
    durationMs: 1884243,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "multi-ts-go-grpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 95,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 10240,
    costUsd: 0,
    outTokens: 38371,
    steps: 0,
    durationMs: 1379896,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "ts-svelte-edge-orpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 351004,
    costUsd: 0,
    outTokens: 33018,
    steps: 0,
    durationMs: 1705743,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "elixir-broadway-absinthe",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 16430,
    costUsd: 0,
    outTokens: 56744,
    steps: 0,
    durationMs: 2476053,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "frontier-polyglot-proto",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    lines: 2241,
    costUsd: 0,
    outTokens: 18107,
    steps: 0,
    durationMs: 720423,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "dotnet-blazor-cqrs",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 1055,
    costUsd: 0,
    outTokens: 20658,
    steps: 0,
    durationMs: 1354954,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "rust-leptos-axum",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 1346,
    costUsd: 0,
    outTokens: 38981,
    steps: 0,
    durationMs: 1822882,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "multi-dotnet-ops",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    lines: 2263,
    costUsd: 0,
    outTokens: 36711,
    steps: 0,
    durationMs: 2560663,
  },
  {
    modelKey: "opencode/x-preview-f-free|high",
    path: "prompt",
    spec: "ai-search-workbench",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    lines: 5649,
    costUsd: 0,
    outTokens: 46337,
    steps: 0,
    durationMs: 1889584,
  },
];
