// AUTO-GENERATED from the ScaffBench V2.1 run summaries (see scripts/build-scaffbench-2-1-data.ts,
// spliced by scripts/splice-scaffbench-2-1.ts). V2.1 is the expanded 13-spec suite.
import type { ScaffbenchCell, ScaffbenchModel } from "./scaffbench-2-data";

export const SCAFFBENCH21_META = {
  "harnessVersion": "2.0.0",
  "generatorVersion": "2.1.3",
  "generatedAt": "2026-07-07T00:01:05.155Z",
  "indexWeights": {
    "macroPass": 0.6,
    "wired": 0.25,
    "cmd": 0.15
  }
} as const;

export const SCAFFBENCH21_SPECS = ["python-ingestion-api","multi-dotnet-ops","go-realtime-api","frontier-effect-eventsourcing","dotnet-blazor-cqrs","ts-svelte-edge-orpc","java-spring-jooq-keycloak","elixir-broadway-absinthe","multi-ts-go-grpc","rust-leptos-axum","ai-search-workbench","react-native-expo","frontier-polyglot-proto"] as const;

export const SCAFFBENCH21_MODELS: readonly ScaffbenchModel[] = [
  {
    "key": "claude-fable-5|low",
    "model": "claude-fable-5",
    "effort": "low",
    "effectiveReasoning": "low",
    "provider": "claude",
    "label": "Fable 5",
    "sortIndex": 62
  },
  {
    "key": "gpt-5.6-luna|max",
    "model": "gpt-5.6-luna",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "codex",
    "label": "GPT-5.6 Luna",
    "sortIndex": 62
  },
  {
    "key": "gpt-5.5|high",
    "model": "gpt-5.5",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "GPT-5.5",
    "sortIndex": 61
  },
  {
    "key": "gpt-5.6-sol|max",
    "model": "gpt-5.6-sol",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "codex",
    "label": "GPT-5.6 Sol",
    "sortIndex": 61
  },
  {
    "key": "claude-fable-5|high",
    "model": "claude-fable-5",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "claude",
    "label": "Fable 5",
    "sortIndex": 57
  },
  {
    "key": "claude-opus-4-8|max",
    "model": "claude-opus-4-8",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 56
  },
  {
    "key": "claude-opus-4-8|low",
    "model": "claude-opus-4-8",
    "effort": "low",
    "effectiveReasoning": "low",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 55
  },
  {
    "key": "gemini-3.5-flash|high",
    "model": "gemini-3.5-flash",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "agy",
    "label": "Gemini 3.5 Flash",
    "sortIndex": 55
  },
  {
    "key": "claude-sonnet-5|max",
    "model": "claude-sonnet-5",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Sonnet 5",
    "sortIndex": 51
  },
  {
    "key": "gpt-5.6-sol|high",
    "model": "gpt-5.6-sol",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "GPT-5.6 Sol",
    "sortIndex": 47
  },
  {
    "key": "gpt-5.6-terra|medium",
    "model": "gpt-5.6-terra",
    "effort": "medium",
    "effectiveReasoning": "medium",
    "provider": "codex",
    "label": "GPT-5.6 Terra",
    "sortIndex": 47
  },
  {
    "key": "gpt-5.6-luna|medium",
    "model": "gpt-5.6-luna",
    "effort": "medium",
    "effectiveReasoning": "medium",
    "provider": "codex",
    "label": "GPT-5.6 Luna",
    "sortIndex": 46
  },
  {
    "key": "opencode/hy3-free|default",
    "model": "opencode/hy3-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "Hy3",
    "sortIndex": 45
  },
  {
    "key": "claude-sonnet-4-6|high",
    "model": "claude-sonnet-4-6",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "claude",
    "label": "Sonnet 4.6",
    "sortIndex": 44
  },
  {
    "key": "opencode/deepseek-v4-flash-free|default",
    "model": "opencode/deepseek-v4-flash-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "DeepSeek V4 Flash",
    "sortIndex": 44
  },
  {
    "key": "gpt-5.3-codex-spark|high",
    "model": "gpt-5.3-codex-spark",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "Codex Spark",
    "sortIndex": 43
  },
  {
    "key": "opencode/mimo-v2.5-free|default",
    "model": "opencode/mimo-v2.5-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "MiMo V2.5",
    "sortIndex": 38
  },
  {
    "key": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "model": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "kilo",
    "label": "Nemotron 3 Nano 30B",
    "sortIndex": 35
  },
  {
    "key": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "model": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "kilo",
    "label": "Nemotron 3 Ultra 550B",
    "sortIndex": 24
  }
];

export const SCAFFBENCH21_CELLS: readonly ScaffbenchCell[] = [
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.456294,
    "outTokens": 13487,
    "steps": 24,
    "durationMs": 164458
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.167823,
    "outTokens": 23866,
    "steps": 42,
    "durationMs": 243108
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.9169205,
    "outTokens": 29074,
    "steps": 39,
    "durationMs": 324065
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.7082685,
    "outTokens": 17059,
    "steps": 16,
    "durationMs": 217385
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.315983,
    "outTokens": 25914,
    "steps": 42,
    "durationMs": 257249
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.8720995,
    "outTokens": 17376,
    "steps": 40,
    "durationMs": 217739
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.1796025,
    "outTokens": 20442,
    "steps": 27,
    "durationMs": 239122
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.1032325,
    "outTokens": 34769,
    "steps": 64,
    "durationMs": 367944
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 2.141318,
    "outTokens": 22892,
    "steps": 41,
    "durationMs": 232591
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.79829,
    "outTokens": 19606,
    "steps": 34,
    "durationMs": 195718
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.3133415,
    "outTokens": 38256,
    "steps": 63,
    "durationMs": 379666
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 1.428365,
    "outTokens": 12551,
    "steps": 28,
    "durationMs": 161800
  },
  {
    "modelKey": "claude-fable-5|low",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 1.1456325,
    "outTokens": 10177,
    "steps": 17,
    "durationMs": 127880
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.5207586,
    "outTokens": 48360,
    "steps": 19,
    "durationMs": 626902
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.6369864000000001,
    "outTokens": 67550,
    "steps": 20,
    "durationMs": 848081
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.6798242,
    "outTokens": 74286,
    "steps": 27,
    "durationMs": 898935
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.3502234,
    "outTokens": 74627,
    "steps": 31,
    "durationMs": 958150
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7110662,
    "outTokens": 73517,
    "steps": 20,
    "durationMs": 888447
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.722357,
    "outTokens": 109275,
    "steps": 30,
    "durationMs": 1331157
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.4669832,
    "outTokens": 53356,
    "steps": 7,
    "durationMs": 644839
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 16,
    "durationMs": 913776
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 35,
    "durationMs": 5867919
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.6996661999999999,
    "outTokens": 54674,
    "steps": 19,
    "durationMs": 764509
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 1.0408196,
    "outTokens": 69542,
    "steps": 10,
    "durationMs": 1018456
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.7877366,
    "outTokens": 59747,
    "steps": 6,
    "durationMs": 706991
  },
  {
    "modelKey": "gpt-5.6-luna|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.49091759999999995,
    "outTokens": 58550,
    "steps": 19,
    "durationMs": 4267083
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.980985,
    "outTokens": 17030,
    "steps": 16,
    "durationMs": 300664
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.020662,
    "outTokens": 21298,
    "steps": 8,
    "durationMs": 337736
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.116495,
    "outTokens": 21115,
    "steps": 15,
    "durationMs": 327912
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 1.428479,
    "outTokens": 24454,
    "steps": 10,
    "durationMs": 341907
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.444715,
    "outTokens": 28816,
    "steps": 9,
    "durationMs": 412708
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.245436,
    "outTokens": 34441,
    "steps": 14,
    "durationMs": 539921
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.974021,
    "outTokens": 18854,
    "steps": 13,
    "durationMs": 322862
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.422234,
    "outTokens": 33646,
    "steps": 16,
    "durationMs": 491979
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": 2.28709,
    "outTokens": 41899,
    "steps": 18,
    "durationMs": 600775
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.243987,
    "outTokens": 23749,
    "steps": 17,
    "durationMs": 385625
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 2.560534,
    "outTokens": 41001,
    "steps": 18,
    "durationMs": 718904
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.858243,
    "outTokens": 16136,
    "steps": 14,
    "durationMs": 251170
  },
  {
    "modelKey": "gpt-5.5|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.80798,
    "outTokens": 15994,
    "steps": 19,
    "durationMs": 258165
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 4.326332,
    "outTokens": 92029,
    "steps": 18,
    "durationMs": 1181154
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.310645,
    "outTokens": 74180,
    "steps": 15,
    "durationMs": 1033027
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.191519,
    "outTokens": 112603,
    "steps": 29,
    "durationMs": 1556119
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 4.95576,
    "outTokens": 70407,
    "steps": 17,
    "durationMs": 1166083
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 77,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 2,
    "durationMs": 5433297
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.437357,
    "outTokens": 84305,
    "steps": 26,
    "durationMs": 1147764
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 93,
    "cmdPct": 100,
    "costUsd": 4.254092,
    "outTokens": 79410,
    "steps": 14,
    "durationMs": 1070600
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.22308,
    "outTokens": 74802,
    "steps": 19,
    "durationMs": 1122656
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": 3.832134,
    "outTokens": 72340,
    "steps": 21,
    "durationMs": 1059961
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 4.274196,
    "outTokens": 65725,
    "steps": 28,
    "durationMs": 923290
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 6.13491,
    "outTokens": 91295,
    "steps": 20,
    "durationMs": 1388573
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 4.197842,
    "outTokens": 48250,
    "steps": 4,
    "durationMs": 3697499
  },
  {
    "modelKey": "gpt-5.6-sol|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 4.47443,
    "outTokens": 67694,
    "steps": 36,
    "durationMs": 1052947
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.8397755,
    "outTokens": 25151,
    "steps": 38,
    "durationMs": 326368
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 4.1627705,
    "outTokens": 48467,
    "steps": 54,
    "durationMs": 496626
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.0918,
    "outTokens": 64195,
    "steps": 39,
    "durationMs": 632949
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.828674,
    "outTokens": 47540,
    "steps": 22,
    "durationMs": 508516
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 7.1716715,
    "outTokens": 89158,
    "steps": 73,
    "durationMs": 874740
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.8793925,
    "outTokens": 34168,
    "steps": 39,
    "durationMs": 357221
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 9.0602045,
    "outTokens": 111731,
    "steps": 55,
    "durationMs": 1193530
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.436819,
    "outTokens": 63316,
    "steps": 72,
    "durationMs": 693375
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 6.5960045,
    "outTokens": 78881,
    "steps": 56,
    "durationMs": 765104
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.886774,
    "outTokens": 42203,
    "steps": 43,
    "durationMs": 438813
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 7.590475,
    "outTokens": 97497,
    "steps": 79,
    "durationMs": 938412
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 3.1151795,
    "outTokens": 36883,
    "steps": 34,
    "durationMs": 414731
  },
  {
    "modelKey": "claude-fable-5|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 2.5740545,
    "outTokens": 25712,
    "steps": 24,
    "durationMs": 318691
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.367595,
    "outTokens": 5821,
    "steps": 185,
    "durationMs": 2076949
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 14.84610225,
    "outTokens": 188239,
    "steps": 118,
    "durationMs": 2503947
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.9638355,
    "outTokens": 124821,
    "steps": 53,
    "durationMs": 1443940
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.75943525,
    "outTokens": 146791,
    "steps": 41,
    "durationMs": 1851381
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 9.9249945,
    "outTokens": 156780,
    "steps": 83,
    "durationMs": 1859394
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 161,
    "durationMs": 3600335
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 10.91312725,
    "outTokens": 215400,
    "steps": 88,
    "durationMs": 2572492
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 18.76200325,
    "outTokens": 262128,
    "steps": 126,
    "durationMs": 3390316
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 7.48473325,
    "outTokens": 165059,
    "steps": 65,
    "durationMs": 1901181
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.45492675,
    "outTokens": 112604,
    "steps": 62,
    "durationMs": 1401182
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 13.19089525,
    "outTokens": 179187,
    "steps": 118,
    "durationMs": 2193876
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 4.96633025,
    "outTokens": 88165,
    "steps": 49,
    "durationMs": 1156945
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.2866665,
    "outTokens": 59707,
    "steps": 27,
    "durationMs": 680491
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.542961,
    "outTokens": 18772,
    "steps": 42,
    "durationMs": 272824
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.64473,
    "outTokens": 21178,
    "steps": 42,
    "durationMs": 355721
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.736254,
    "outTokens": 26363,
    "steps": 36,
    "durationMs": 388440
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.802224,
    "outTokens": 13824,
    "steps": 15,
    "durationMs": 183501
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.323207,
    "outTokens": 17874,
    "steps": 33,
    "durationMs": 259790
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.45217525,
    "outTokens": 18532,
    "steps": 38,
    "durationMs": 313965
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.41092675,
    "outTokens": 23301,
    "steps": 27,
    "durationMs": 338862
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.01265125,
    "outTokens": 36376,
    "steps": 66,
    "durationMs": 545905
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": 2.031828,
    "outTokens": 28724,
    "steps": 44,
    "durationMs": 443817
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.030279,
    "outTokens": 14078,
    "steps": 26,
    "durationMs": 258733
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 3.0851255,
    "outTokens": 35195,
    "steps": 73,
    "durationMs": 494860
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.86470075,
    "outTokens": 10886,
    "steps": 24,
    "durationMs": 188619
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.86831175,
    "outTokens": 12045,
    "steps": 22,
    "durationMs": 283070
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 74514
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 100324
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 79592
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 58131
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 164470
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 153007
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 131282
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 120225
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 104008
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 94252
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 127703
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 118786
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 42742
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.93944505,
    "outTokens": 5502,
    "steps": 187,
    "durationMs": 1858481
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.96741305,
    "outTokens": 182012,
    "steps": 267,
    "durationMs": 2074892
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.35636615,
    "outTokens": 179707,
    "steps": 97,
    "durationMs": 1541083
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 3755156
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.3724337000000002,
    "outTokens": 14886,
    "steps": 320,
    "durationMs": 2055319
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.4871388,
    "outTokens": 92636,
    "steps": 95,
    "durationMs": 952575
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.8360802,
    "outTokens": 11414,
    "steps": 388,
    "durationMs": 2940820
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 7.38704505,
    "outTokens": 128562,
    "steps": 104,
    "durationMs": 1294404
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 11.462255100000002,
    "outTokens": 248104,
    "steps": 160,
    "durationMs": 2414089
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 11.99229645,
    "outTokens": 217208,
    "steps": 295,
    "durationMs": 3113724
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.995577550000001,
    "outTokens": 188079,
    "steps": 194,
    "durationMs": 1767987
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 199,
    "durationMs": 3690649
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 3887885
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.017591,
    "outTokens": 22956,
    "steps": 5,
    "durationMs": 375176
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.182961,
    "outTokens": 26636,
    "steps": 4,
    "durationMs": 428262
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.470487,
    "outTokens": 53613,
    "steps": 8,
    "durationMs": 814426
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 1.290734,
    "outTokens": 25064,
    "steps": 6,
    "durationMs": 367458
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.739293,
    "outTokens": 33748,
    "steps": 11,
    "durationMs": 542207
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.282549,
    "outTokens": 43774,
    "steps": 13,
    "durationMs": 697085
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.22337,
    "outTokens": 28929,
    "steps": 13,
    "durationMs": 471124
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.907653,
    "outTokens": 33805,
    "steps": 7,
    "durationMs": 595648
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 1.066719,
    "outTokens": 24732,
    "steps": 6,
    "durationMs": 377670
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.444649,
    "outTokens": 30006,
    "steps": 7,
    "durationMs": 444403
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 2.472238,
    "outTokens": 38807,
    "steps": 20,
    "durationMs": 666300
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 3.275813,
    "outTokens": 30844,
    "steps": 13,
    "durationMs": 486993
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 1.339811,
    "outTokens": 27342,
    "steps": 8,
    "durationMs": 411438
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.182051,
    "outTokens": 8015,
    "steps": 3,
    "durationMs": 149441
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.266646,
    "outTokens": 8829,
    "steps": 6,
    "durationMs": 211709
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.218777,
    "outTokens": 8729,
    "steps": 5,
    "durationMs": 149181
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1698665,
    "outTokens": 7324,
    "steps": 3,
    "durationMs": 119897
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1914205,
    "outTokens": 7847,
    "steps": 3,
    "durationMs": 141786
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.3236195,
    "outTokens": 7925,
    "steps": 5,
    "durationMs": 174266
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.181541,
    "outTokens": 8660,
    "steps": 2,
    "durationMs": 152080
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.357387,
    "outTokens": 12452,
    "steps": 5,
    "durationMs": 303803
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.269162,
    "outTokens": 10285,
    "steps": 5,
    "durationMs": 160042
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.26492,
    "outTokens": 11239,
    "steps": 4,
    "durationMs": 209470
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 0.277685,
    "outTokens": 9507,
    "steps": 3,
    "durationMs": 171534
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.135139,
    "outTokens": 5954,
    "steps": 3,
    "durationMs": 97235
  },
  {
    "modelKey": "gpt-5.6-terra|medium",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.174847,
    "outTokens": 7530,
    "steps": 6,
    "durationMs": 118287
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.1479446,
    "outTokens": 14725,
    "steps": 7,
    "durationMs": 265291
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": 0.10589319999999999,
    "outTokens": 11598,
    "steps": 3,
    "durationMs": 210297
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": 0.09819119999999999,
    "outTokens": 9092,
    "steps": 4,
    "durationMs": 154571
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.1385904,
    "outTokens": 13799,
    "steps": 4,
    "durationMs": 218636
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.0869528,
    "outTokens": 9043,
    "steps": 3,
    "durationMs": 137181
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.165572,
    "outTokens": 14806,
    "steps": 8,
    "durationMs": 299079
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 93,
    "cmdPct": 100,
    "costUsd": 0.055349800000000005,
    "outTokens": 6192,
    "steps": 2,
    "durationMs": 106328
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.09895480000000001,
    "outTokens": 9194,
    "steps": 6,
    "durationMs": 171285
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.1358288,
    "outTokens": 11808,
    "steps": 7,
    "durationMs": 204804
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.0680264,
    "outTokens": 6184,
    "steps": 4,
    "durationMs": 105383
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 0.1637738,
    "outTokens": 16131,
    "steps": 8,
    "durationMs": 283165
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.0977154,
    "outTokens": 10015,
    "steps": 6,
    "durationMs": 161033
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 50,
    "cmdPct": 100,
    "costUsd": 0.126841,
    "outTokens": 12103,
    "steps": 7,
    "durationMs": 216667
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1369506,
    "outTokens": 3463,
    "steps": 8,
    "durationMs": 65288
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 46,
    "cmdPct": 100,
    "costUsd": 0.21633,
    "outTokens": 5261,
    "steps": 13,
    "durationMs": 90743
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.29862720000000004,
    "outTokens": 5211,
    "steps": 12,
    "durationMs": 93785
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.207668,
    "outTokens": 3247,
    "steps": 10,
    "durationMs": 66389
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1962116,
    "outTokens": 2593,
    "steps": 8,
    "durationMs": 59067
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1606794,
    "outTokens": 4210,
    "steps": 8,
    "durationMs": 76594
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1721014,
    "outTokens": 3203,
    "steps": 8,
    "durationMs": 75934
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 44,
    "cmdPct": 100,
    "costUsd": 0.32937679999999997,
    "outTokens": 8506,
    "steps": 14,
    "durationMs": 129959
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.2079582,
    "outTokens": 3044,
    "steps": 8,
    "durationMs": 69244
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.147849,
    "outTokens": 3486,
    "steps": 8,
    "durationMs": 68124
  },
  {
    "modelKey": "gpt-5.6-luna|medium",
    "path": "mcp",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.1457618,
    "outTokens": 2403,
    "steps": 8,
    "durationMs": 46380
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 12325,
    "steps": 38,
    "durationMs": 191998
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16345,
    "steps": 43,
    "durationMs": 305086
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 24264,
    "steps": 51,
    "durationMs": 526926
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16022,
    "steps": 44,
    "durationMs": 275438
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 24892,
    "steps": 41,
    "durationMs": 434339
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 39701,
    "steps": 63,
    "durationMs": 781369
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 23258,
    "steps": 49,
    "durationMs": 318043
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 29782,
    "steps": 53,
    "durationMs": 615094
  },
  {
    "modelKey": "opencode/hy3-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 34832,
    "steps": 80,
    "durationMs": 603872
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7655706000000001,
    "outTokens": 18624,
    "steps": 33,
    "durationMs": 266022
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.24886705,
    "outTokens": 56785,
    "steps": 55,
    "durationMs": 666310
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.3129156499999999,
    "outTokens": 39238,
    "steps": 33,
    "durationMs": 503561
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.41737559999999996,
    "outTokens": 8436,
    "steps": 13,
    "durationMs": 2002867
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.1347518500000002,
    "outTokens": 53126,
    "steps": 51,
    "durationMs": 661968
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.5069561,
    "outTokens": 39404,
    "steps": 40,
    "durationMs": 544582
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.6346418,
    "outTokens": 59561,
    "steps": 43,
    "durationMs": 748069
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.6606077000000001,
    "outTokens": 34454,
    "steps": 64,
    "durationMs": 534721
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 2.01723615,
    "outTokens": 70758,
    "steps": 49,
    "durationMs": 871983
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.20853275,
    "outTokens": 26168,
    "steps": 48,
    "durationMs": 402474
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 3.07950795,
    "outTokens": 61484,
    "steps": 92,
    "durationMs": 879077
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.8667705,
    "outTokens": 21182,
    "steps": 33,
    "durationMs": 311341
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 6109396
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9851,
    "steps": 28,
    "durationMs": 130690
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 17035,
    "steps": 44,
    "durationMs": 145298
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 20415,
    "steps": 45,
    "durationMs": 184973
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 32000,
    "steps": 0,
    "durationMs": 251231
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 45761,
    "steps": 56,
    "durationMs": 347394
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 24631,
    "steps": 43,
    "durationMs": 337507
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 27570,
    "steps": 28,
    "durationMs": 227483
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 21882,
    "steps": 66,
    "durationMs": 211545
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 81,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16143,
    "steps": 38,
    "durationMs": 124501
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 25764,
    "steps": 41,
    "durationMs": 232056
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 27209,
    "steps": 74,
    "durationMs": 713315
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 7793,
    "steps": 21,
    "durationMs": 79245
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 22939,
    "steps": 24,
    "durationMs": 247872
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3897,
    "steps": 18
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3897,
    "steps": 18
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9653,
    "steps": 30
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9653,
    "steps": 30
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2771,
    "steps": 7
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2771,
    "steps": 7
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4278,
    "steps": 11
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4278,
    "steps": 11
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3311,
    "steps": 6
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3311,
    "steps": 6
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4321,
    "steps": 13
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4321,
    "steps": 13
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3877,
    "steps": 13
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 3877,
    "steps": 13
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10893,
    "steps": 25
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10893,
    "steps": 25
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2672,
    "steps": 8
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2672,
    "steps": 8
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4372,
    "steps": 11
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4372,
    "steps": 11
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2620,
    "steps": 6
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "mcp",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2620,
    "steps": 6
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 44961,
    "steps": 4,
    "durationMs": 46978
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 50455,
    "steps": 2,
    "durationMs": 174241
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 79836,
    "steps": 25,
    "durationMs": 97022
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 67683,
    "steps": 10,
    "durationMs": 63350
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 53909,
    "steps": 28,
    "durationMs": 69703
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 65703,
    "steps": 17,
    "durationMs": 124665
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 45340,
    "steps": 6,
    "durationMs": 39855
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 74131,
    "steps": 3,
    "durationMs": 178037
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 89949,
    "steps": 45,
    "durationMs": 162806
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 59272,
    "steps": 8,
    "durationMs": 329605
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 86,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 81406,
    "steps": 28,
    "durationMs": 156196
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 35901,
    "steps": 2,
    "durationMs": 38352
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 47729,
    "steps": 3,
    "durationMs": 55177
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 11681,
    "steps": 34,
    "durationMs": 187930
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16262,
    "steps": 42,
    "durationMs": 256681
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 11591,
    "steps": 22,
    "durationMs": 134248
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 8973,
    "steps": 18,
    "durationMs": 100318
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 31509,
    "steps": 69,
    "durationMs": 307765
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10426,
    "steps": 38,
    "durationMs": 136601
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 22129,
    "steps": 51,
    "durationMs": 243737
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 35028,
    "steps": 53,
    "durationMs": 467851
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15420,
    "steps": 48,
    "durationMs": 167034
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13207,
    "steps": 29,
    "durationMs": 193836
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 81,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 30950,
    "steps": 87,
    "durationMs": 334040
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15624,
    "steps": 39,
    "durationMs": 222061
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 8887,
    "steps": 29,
    "durationMs": 113651
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 12679,
    "steps": 0,
    "durationMs": 134909
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 34444,
    "steps": 22,
    "durationMs": 321054
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15920,
    "steps": 8,
    "durationMs": 183478
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 946,
    "steps": 1,
    "durationMs": 12096
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0,
    "durationMs": 69581
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 80,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13660,
    "steps": 16,
    "durationMs": 186778
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 14099,
    "steps": 0,
    "durationMs": 181643
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13386,
    "steps": 7,
    "durationMs": 92515
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1462,
    "steps": 2,
    "durationMs": 19946
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6920,
    "steps": 3,
    "durationMs": 79085
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 5261,
    "steps": 1,
    "durationMs": 53773
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 32000,
    "steps": 0,
    "durationMs": 194062
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 370,
    "steps": 1,
    "durationMs": 167468
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 15,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2655,
    "steps": 5,
    "durationMs": 165100
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 197,
    "steps": 1,
    "durationMs": 209201
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 54,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6143,
    "steps": 9,
    "durationMs": 484995
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 7,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 311,
    "steps": 1,
    "durationMs": 185462
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1246,
    "steps": 3,
    "durationMs": 316349
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 33,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16315,
    "steps": 40,
    "durationMs": 943737
  }
];
