// AUTO-GENERATED from the ScaffBench V2.1 run summaries (see scripts/build-scaffbench-2-1-data.ts).
// V2.1 is the expanded 13-spec suite (adds Java + Elixir ecosystems and two
// prompt-only frontier specs; .NET validated for real). Rows: Opus 4.8 low (full
// 13-spec ablation), Opus 4.8 max + Claude Sonnet 5 max (the 8 specs validated for
// both so far). Per-cell signals from the harness bySpecCell aggregate; corePass
// from validation steps minus the quality gate; a run with zero core steps is
// INCONCLUSIVE (scored:false) — e.g. multi-ts-go-grpc's frontend/+backend/ layout
// the root-only validator can't locate. Cost metered; steps from the trajectory.
import type { ScaffbenchCell, ScaffbenchModel } from "./scaffbench-2-data";

export const SCAFFBENCH21_META = {
  harnessVersion: "2.0.0",
  generatorVersion: "2.1.3",
  generatedAt: "2026-06-30T13:37:52.148Z",
  indexWeights: { macroPass: 0.6, wired: 0.25, cmd: 0.15 },
} as const;

export const SCAFFBENCH21_SPECS = ["python-ingestion-api","multi-dotnet-ops","go-realtime-api","frontier-effect-eventsourcing","dotnet-blazor-cqrs","ts-svelte-edge-orpc","java-spring-jooq-keycloak","elixir-broadway-absinthe","multi-ts-go-grpc","rust-leptos-axum","ai-search-workbench","react-native-expo","frontier-polyglot-proto"] as const;

export const SCAFFBENCH21_MODELS: readonly ScaffbenchModel[] = [
  {
    "key": "claude-opus-4-8|max",
    "model": "claude-opus-4-8",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 56
  },
  {
    "key": "claude-opus-4-8|low",
    "model": "claude-opus-4-8",
    "effort": "low",
    "effectiveReasoning": "low",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 55
  },
  {
    "key": "claude-sonnet-5|max",
    "model": "claude-sonnet-5",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Sonnet 5",
    "sortIndex": 47
  }
];

export const SCAFFBENCH21_CELLS: readonly ScaffbenchCell[] = [
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.367595,
    "outTokens": 5821,
    "steps": 185
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 14.84610225,
    "outTokens": 188239,
    "steps": 118
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.9638355,
    "outTokens": 124821,
    "steps": 53
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.75943525,
    "outTokens": 146791,
    "steps": 41
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 9.9249945,
    "outTokens": 156780,
    "steps": 83
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 161
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 10.91312725,
    "outTokens": 215400,
    "steps": 88
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 18.76200325,
    "outTokens": 262128,
    "steps": 126
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 7.48473325,
    "outTokens": 165059,
    "steps": 65
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.45492675,
    "outTokens": 112604,
    "steps": 62
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 13.19089525,
    "outTokens": 179187,
    "steps": 118
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 4.96633025,
    "outTokens": 88165,
    "steps": 49
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.2866665,
    "outTokens": 59707,
    "steps": 27
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.542961,
    "outTokens": 18772,
    "steps": 42
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.64473,
    "outTokens": 21178,
    "steps": 42
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.736254,
    "outTokens": 26363,
    "steps": 36
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.802224,
    "outTokens": 13824,
    "steps": 15
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.323207,
    "outTokens": 17874,
    "steps": 33
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.45217525,
    "outTokens": 18532,
    "steps": 38
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.41092675,
    "outTokens": 23301,
    "steps": 27
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.01265125,
    "outTokens": 36376,
    "steps": 66
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": 2.031828,
    "outTokens": 28724,
    "steps": 44
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.030279,
    "outTokens": 14078,
    "steps": 26
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 3.0851255,
    "outTokens": 35195,
    "steps": 73
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.86470075,
    "outTokens": 10886,
    "steps": 24
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.86831175,
    "outTokens": 12045,
    "steps": 22
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.93944505,
    "outTokens": 5502,
    "steps": 187
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.96741305,
    "outTokens": 182012,
    "steps": 267
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.35636615,
    "outTokens": 179707,
    "steps": 97
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.3724337000000002,
    "outTokens": 14886,
    "steps": 320
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.4871388,
    "outTokens": 92636,
    "steps": 95
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.8360802,
    "outTokens": 11414,
    "steps": 388
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 11.462255100000002,
    "outTokens": 248104,
    "steps": 160
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 11.99229645,
    "outTokens": 217208,
    "steps": 295
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.995577550000001,
    "outTokens": 188079,
    "steps": 194
  }
];
