// AUTO-GENERATED from the ScaffBench 3 run summaries. Do not edit rows by hand.
// Suite 3.0, harness 3.1.0, prompt path, 1 trial per spec. Only models we have
// actually run appear here; the board renders exactly these rows.
// sortIndex follows the graded index (docs/guidelines/scaffbench-benchmark.md,
// Scoring): 0.6 Core + 0.2 lint/format share + 0.2 stack per spec, weighted by
// spec difficulty. GLM 5.3 Flash is exact (per-gate results in its run report).
// GPT-5.6 Luna is the lower bound (73; upper 83): its cells record Full only, so
// every Core-only spec counts lint and format as red until the run summary is
// rebuilt with the current harness and the exact per-gate results replace it.
// Gemini 3.7 Flash (low) is exact: computed by harness 3.1.0 under validator
// cache v9 from testing/llm-benchmarks/v3/lane-3 on Zorro; agy reports no cost
// or tokens, so those columns are empty by construction. Its ts-svelte-edge-orpc
// LoC is null until the archived project is re-measured with .svelte-kit excluded
// from the walk; the run summary recorded the build output as 220,342 lines.
import type { ScaffbenchCell, ScaffbenchModel } from "@web/components/home/scaffbench-types";

export const SCAFFBENCH3_MODELS: readonly ScaffbenchModel[] = [
  {
    key: "gpt-5.6-luna|high",
    model: "gpt-5.6-luna",
    effort: "high",
    effectiveReasoning: "high",
    harness: "codex",
    vendor: "openai",
    label: "GPT-5.6 Luna",
    sortIndex: 73,
    eligibility: "ranked",
  },
  {
    key: "glm-5.3-flash|high",
    model: "glm-5.3-flash",
    effort: "high",
    effectiveReasoning: "high",
    harness: "opencode",
    vendor: "zai",
    label: "GLM 5.3 Flash",
    sortIndex: 58,
    eligibility: "exploratory",
  },
  {
    key: "gemini-3.7-flash|low",
    model: "gemini-3.7-flash",
    effort: "low",
    effectiveReasoning: "low",
    harness: "agy",
    vendor: "google",
    label: "Gemini 3.7 Flash",
    sortIndex: 63,
    eligibility: "ranked",
  },
];

export const SCAFFBENCH3_CELLS: readonly ScaffbenchCell[] = [
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "ai-search-workbench",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 79,
    lines: 1197,
    costUsd: 0.886501,
    outTokens: 35219,
    steps: null,
    durationMs: 742043,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "dotnet-blazor-cqrs",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 965,
    costUsd: 0.663307,
    outTokens: 30983,
    steps: null,
    durationMs: 713291,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "elixir-broadway-absinthe",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 793,
    costUsd: 0.93621,
    outTokens: 39305,
    steps: null,
    durationMs: 972411,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "frontier-effect-eventsourcing",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 93,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 79,
    lines: 648,
    costUsd: 0.482846,
    outTokens: 28984,
    steps: null,
    durationMs: 620917,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "frontier-polyglot-proto",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 908,
    costUsd: 0.267081,
    outTokens: 15593,
    steps: null,
    durationMs: 354734,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "go-realtime-api",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 5380,
    costUsd: 0.690543,
    outTokens: 33856,
    steps: null,
    durationMs: 786462,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "java-spring-jooq-keycloak",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 99,
    lines: 830,
    costUsd: 0.346041,
    outTokens: 27600,
    steps: null,
    durationMs: 598069,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "multi-dotnet-ops",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 80,
    lines: 18880,
    costUsd: 0.945963,
    outTokens: 34600,
    steps: null,
    durationMs: 838419,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "multi-ts-go-grpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 95,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 79,
    lines: 2049,
    costUsd: 0.940376,
    outTokens: 42900,
    steps: null,
    durationMs: 1058460,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "python-ingestion-api",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 99,
    lines: 1053,
    costUsd: 0.538406,
    outTokens: 36698,
    steps: null,
    durationMs: 732746,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "react-native-expo",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 92,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 18,
    lines: 972,
    costUsd: 1.148512,
    outTokens: 42112,
    steps: null,
    durationMs: 1016461,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "rust-leptos-axum",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 79,
    lines: 610,
    costUsd: 0.339955,
    outTokens: 18928,
    steps: null,
    durationMs: 533080,
  },
  {
    modelKey: "gpt-5.6-luna|high",
    spec: "ts-svelte-edge-orpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 80,
    lines: 44430,
    costUsd: 0.732647,
    outTokens: 35561,
    steps: null,
    durationMs: 915753,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "ai-search-workbench",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 19,
    lines: 5649,
    costUsd: 0,
    outTokens: 46337,
    steps: null,
    durationMs: 1889584,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "dotnet-blazor-cqrs",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 1055,
    costUsd: 0,
    outTokens: 20658,
    steps: null,
    durationMs: 1354954,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "elixir-broadway-absinthe",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 16430,
    costUsd: 0,
    outTokens: 56744,
    steps: null,
    durationMs: 2476053,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "frontier-effect-eventsourcing",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 1050,
    costUsd: 0,
    outTokens: 32816,
    steps: null,
    durationMs: 846922,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "frontier-polyglot-proto",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 2241,
    costUsd: 0,
    outTokens: 18107,
    steps: null,
    durationMs: 720423,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "go-realtime-api",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 90,
    lines: 10655,
    costUsd: 0,
    outTokens: 42082,
    steps: null,
    durationMs: 1884243,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "java-spring-jooq-keycloak",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 93,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 99,
    lines: 1660,
    costUsd: 0,
    outTokens: 36450,
    steps: null,
    durationMs: 2916988,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "multi-dotnet-ops",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 89,
    lines: 2263,
    costUsd: 0,
    outTokens: 36711,
    steps: null,
    durationMs: 2560663,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "multi-ts-go-grpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 95,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 79,
    lines: 10240,
    costUsd: 0,
    outTokens: 38371,
    steps: null,
    durationMs: 1379896,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "python-ingestion-api",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 19,
    lines: 944,
    costUsd: 0,
    outTokens: 16545,
    steps: null,
    durationMs: 2226857,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "react-native-expo",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 1168,
    costUsd: 0,
    outTokens: 22713,
    steps: null,
    durationMs: 953958,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "rust-leptos-axum",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 96,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 89,
    lines: 1346,
    costUsd: 0,
    outTokens: 38981,
    steps: null,
    durationMs: 1822882,
  },
  {
    modelKey: "glm-5.3-flash|high",
    spec: "ts-svelte-edge-orpc",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 80,
    lines: 351004,
    costUsd: 0,
    outTokens: 33018,
    steps: null,
    durationMs: 1705743,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "ai-search-workbench",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 85,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 17,
    lines: 1796,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 90681,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "dotnet-blazor-cqrs",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 1916,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 291181,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "elixir-broadway-absinthe",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 3806,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 558890,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "frontier-effect-eventsourcing",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 80,
    lines: 991,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 140036,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "frontier-polyglot-proto",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 87,
    lines: 2023,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 233198,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "go-realtime-api",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 90,
    lines: 9261,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 136043,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "java-spring-jooq-keycloak",
    scored: true,
    corePass: true,
    fullPass: true,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 1,
    score: 100,
    lines: 1132,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 207073,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "multi-dotnet-ops",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 94,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 84,
    lines: 2162,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 222737,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "multi-ts-go-grpc",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 91,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 18,
    lines: 9804,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 233437,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "python-ingestion-api",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 1008,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 76121,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "react-native-expo",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: 1500,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 258778,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "rust-leptos-axum",
    scored: true,
    corePass: true,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 1,
    qualityPassCount: 0,
    score: 80,
    lines: 1328,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 452864,
  },
  {
    modelKey: "gemini-3.7-flash|low",
    spec: "ts-svelte-edge-orpc",
    scored: true,
    corePass: false,
    fullPass: false,
    wiredPct: 100,
    cmdPct: 100,
    trials: 1,
    scoredTrials: 1,
    passCount: 0,
    qualityPassCount: 0,
    score: 20,
    lines: null,
    costUsd: null,
    outTokens: null,
    steps: null,
    durationMs: 526396,
  },
];
