// AUTO-GENERATED from the ScaffBench V2.1 run summaries (see scripts/build-scaffbench-2-1-data.ts).
// V2.1 is the expanded 13-spec suite (adds Java + Elixir ecosystems and two
// prompt-only frontier specs; .NET validated for real). Rows: Opus 4.8 low (full
// 13-spec ablation), Opus 4.8 max + Claude Sonnet 5 max (the 8 specs validated for
// both so far). Per-cell signals from the harness bySpecCell aggregate; corePass
// from validation steps minus the quality gate; a run with zero core steps is
// INCONCLUSIVE (scored:false) — e.g. multi-ts-go-grpc's frontend/+backend/ layout
// the root-only validator can't locate. Cost metered; steps from the trajectory.
import type { ScaffbenchCell, ScaffbenchModel } from "./scaffbench-2-data";

export const SCAFFBENCH21_META = {
  harnessVersion: "2.0.0",
  generatorVersion: "2.1.3",
  generatedAt: "2026-06-30T13:37:52.148Z",
  indexWeights: { macroPass: 0.6, wired: 0.25, cmd: 0.15 },
} as const;

export const SCAFFBENCH21_SPECS = ["python-ingestion-api","multi-dotnet-ops","go-realtime-api","frontier-effect-eventsourcing","dotnet-blazor-cqrs","ts-svelte-edge-orpc","java-spring-jooq-keycloak","elixir-broadway-absinthe","multi-ts-go-grpc","rust-leptos-axum","ai-search-workbench","react-native-expo","frontier-polyglot-proto"] as const;

export const SCAFFBENCH21_MODELS: readonly ScaffbenchModel[] = [
  {
    "key": "claude-opus-4-8|max",
    "model": "claude-opus-4-8",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 56
  },
  {
    "key": "claude-opus-4-8|low",
    "model": "claude-opus-4-8",
    "effort": "low",
    "effectiveReasoning": "low",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 55
  },
  {
    "key": "gemini-3.5-flash|high",
    "model": "gemini-3.5-flash",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "agy",
    "label": "Gemini 3.5 Flash",
    "sortIndex": 55
  },
  {
    "key": "claude-sonnet-5|max",
    "model": "claude-sonnet-5",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Sonnet 5",
    "sortIndex": 51
  },
  {
    "key": "claude-sonnet-4-6|high",
    "model": "claude-sonnet-4-6",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "claude",
    "label": "Sonnet 4.6",
    "sortIndex": 44
  },
  {
    "key": "opencode/deepseek-v4-flash-free|default",
    "model": "opencode/deepseek-v4-flash-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "DeepSeek V4 Flash",
    "sortIndex": 44
  },
  {
    "key": "gpt-5.3-codex-spark|high",
    "model": "gpt-5.3-codex-spark",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "Codex Spark",
    "sortIndex": 43
  },
  {
    "key": "opencode/mimo-v2.5-free|default",
    "model": "opencode/mimo-v2.5-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "MiMo V2.5",
    "sortIndex": 38
  },
  {
    "key": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "model": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "kilo",
    "label": "Nemotron 3 Nano 30B",
    "sortIndex": 35
  },
  {
    "key": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "model": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "kilo",
    "label": "Nemotron 3 Ultra 550B",
    "sortIndex": 24
  }
];

export const SCAFFBENCH21_CELLS: readonly ScaffbenchCell[] = [
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.367595,
    "outTokens": 5821,
    "steps": 185
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 14.84610225,
    "outTokens": 188239,
    "steps": 118
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.9638355,
    "outTokens": 124821,
    "steps": 53
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.75943525,
    "outTokens": 146791,
    "steps": 41
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 9.9249945,
    "outTokens": 156780,
    "steps": 83
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 161
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 10.91312725,
    "outTokens": 215400,
    "steps": 88
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 18.76200325,
    "outTokens": 262128,
    "steps": 126
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 7.48473325,
    "outTokens": 165059,
    "steps": 65
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 6.45492675,
    "outTokens": 112604,
    "steps": 62
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 13.19089525,
    "outTokens": 179187,
    "steps": 118
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 4.96633025,
    "outTokens": 88165,
    "steps": 49
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.2866665,
    "outTokens": 59707,
    "steps": 27
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.542961,
    "outTokens": 18772,
    "steps": 42
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.64473,
    "outTokens": 21178,
    "steps": 42
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.736254,
    "outTokens": 26363,
    "steps": 36
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.802224,
    "outTokens": 13824,
    "steps": 15
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.323207,
    "outTokens": 17874,
    "steps": 33
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.45217525,
    "outTokens": 18532,
    "steps": 38
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.41092675,
    "outTokens": 23301,
    "steps": 27
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.01265125,
    "outTokens": 36376,
    "steps": 66
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": 2.031828,
    "outTokens": 28724,
    "steps": 44
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.030279,
    "outTokens": 14078,
    "steps": 26
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 3.0851255,
    "outTokens": 35195,
    "steps": 73
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.86470075,
    "outTokens": 10886,
    "steps": 24
  },
  {
    "modelKey": "claude-opus-4-8|low",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.86831175,
    "outTokens": 12045,
    "steps": 22
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "gemini-3.5-flash|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.93944505,
    "outTokens": 5502,
    "steps": 187
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.96741305,
    "outTokens": 182012,
    "steps": 267
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 7.35636615,
    "outTokens": 179707,
    "steps": 97
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.3724337000000002,
    "outTokens": 14886,
    "steps": 320
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.4871388,
    "outTokens": 92636,
    "steps": 95
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.8360802,
    "outTokens": 11414,
    "steps": 388
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 7.38704505,
    "outTokens": 128562,
    "steps": 104
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 11.462255100000002,
    "outTokens": 248104,
    "steps": 160
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 11.99229645,
    "outTokens": 217208,
    "steps": 295
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 5.995577550000001,
    "outTokens": 188079,
    "steps": 194
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 199
  },
  {
    "modelKey": "claude-sonnet-5|max",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7655706000000001,
    "outTokens": 18624,
    "steps": 33
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.24886705,
    "outTokens": 56785,
    "steps": 55
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.3129156499999999,
    "outTokens": 39238,
    "steps": 33
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.41737559999999996,
    "outTokens": 8436,
    "steps": 13
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.1347518500000002,
    "outTokens": 53126,
    "steps": 51
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.5069561,
    "outTokens": 39404,
    "steps": 40
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.6346418,
    "outTokens": 59561,
    "steps": 43
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.6606077000000001,
    "outTokens": 34454,
    "steps": 64
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 2.01723615,
    "outTokens": 70758,
    "steps": 49
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.20853275,
    "outTokens": 26168,
    "steps": 48
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 3.07950795,
    "outTokens": 61484,
    "steps": 92
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": 0.8667705,
    "outTokens": 21182,
    "steps": 33
  },
  {
    "modelKey": "claude-sonnet-4-6|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9851,
    "steps": 28
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 17035,
    "steps": 44
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 20415,
    "steps": 45
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 32000,
    "steps": 0
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 45761,
    "steps": 56
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 24631,
    "steps": 43
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 27570,
    "steps": 28
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 21882,
    "steps": 66
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 81,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16143,
    "steps": 38
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 25764,
    "steps": 41
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 27209,
    "steps": 74
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 7793,
    "steps": 21
  },
  {
    "modelKey": "opencode/deepseek-v4-flash-free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 22939,
    "steps": 24
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 44961,
    "steps": 4
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 50455,
    "steps": 2
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 79836,
    "steps": 25
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 67683,
    "steps": 10
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 53909,
    "steps": 28
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 65703,
    "steps": 17
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 45340,
    "steps": 6
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 74131,
    "steps": 3
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 94,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 89949,
    "steps": 45
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 59272,
    "steps": 8
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 86,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 81406,
    "steps": 28
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 35901,
    "steps": 2
  },
  {
    "modelKey": "gpt-5.3-codex-spark|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 47729,
    "steps": 3
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 11681,
    "steps": 34
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16262,
    "steps": 42
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 11591,
    "steps": 22
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 8973,
    "steps": 18
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 31509,
    "steps": 69
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10426,
    "steps": 38
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 22129,
    "steps": 51
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 35028,
    "steps": 53
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15420,
    "steps": 48
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13207,
    "steps": 29
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 81,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 30950,
    "steps": 87
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15624,
    "steps": 39
  },
  {
    "modelKey": "opencode/mimo-v2.5-free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 75,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 8887,
    "steps": 29
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 12679,
    "steps": 0
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 34444,
    "steps": 22
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15920,
    "steps": 8
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 946,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 80,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13660,
    "steps": 16
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 14099,
    "steps": 0
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13386,
    "steps": 7
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1462,
    "steps": 2
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6920,
    "steps": 3
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 5261,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free|default",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 32000,
    "steps": 0
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 370,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 15,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 2655,
    "steps": 5
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 197,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 54,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6143,
    "steps": 9
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 7,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 311,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1246,
    "steps": 3
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-ultra-550b-a55b:free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 33,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 16315,
    "steps": 40
  }
];
