// AUTO-GENERATED from ten ScaffBench 2 run summaries (see scripts/build-scaffbench-data.ts).
// Models: Opus 4.8/4.7/4.6/4.5 (Claude Code), GPT-5.5 low/medium/xhigh (Codex), and two
// free-tier models — North-mini Code (opencode) + Nemotron-3 Super (Kilo Code). 2026-06-26.
// Per-cell signals from the harness bySpecCell aggregate (wired = stackPercent, cmd =
// commandDisciplinePercent); corePass derived from validation steps minus the quality gate;
// steps from the saved trajectory; GPT cost estimated from token usage × OpenAI pricing.
export type ScaffbenchPath = "mcp" | "cli" | "prompt";

export type ScaffbenchModel = {
  key: string;
  model: string;
  effort: string;
  effectiveReasoning: string;
  provider: "claude" | "codex" | "opencode" | "kilo" | "agy";
  label: string;
  /** overall ScaffBench Index across all scored cells — the group sort key. */
  sortIndex: number;
};

export type ScaffbenchCell = {
  /** "<model>|<effort>" — joins a cell to its ScaffbenchModel. */
  modelKey: string;
  path: ScaffbenchPath;
  spec: string;
  /** false when the run was infra-inconclusive (timed-out toolchain) — excluded from rates. */
  scored: boolean;
  corePass: boolean;
  fullPass: boolean;
  wiredPct: number;
  cmdPct: number;
  costUsd: number | null;
  outTokens: number | null;
  steps: number;
  /** median wall-clock to scaffold this spec, in ms; null when the run predates
   *  duration capture. Aggregated into the leaderboard "Time" column. */
  durationMs?: number | null;
};

export const SCAFFBENCH2_META = {
  harnessVersion: "2.0.0",
  generatorVersion: "2.1.1",
  generatedAt: "2026-06-26T00:56:27.088Z",
  indexWeights: { macroPass: 0.6, wired: 0.25, cmd: 0.15 },
} as const;

export const SCAFFBENCH2_SPECS = ["ai-search-workbench","rust-leptos-axum","python-ingestion-api","go-realtime-api","multi-dotnet-ops"] as const;

export const SCAFFBENCH2_MODELS: readonly ScaffbenchModel[] = [
  {
    "key": "claude-opus-4-8|default",
    "model": "claude-opus-4-8",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 85
  },
  {
    "key": "claude-opus-4-7|default",
    "model": "claude-opus-4-7",
    "effort": "default",
    "effectiveReasoning": "xhigh",
    "provider": "claude",
    "label": "Opus 4.7",
    "sortIndex": 85
  },
  {
    "key": "gpt-5.5|medium",
    "model": "gpt-5.5",
    "effort": "medium",
    "effectiveReasoning": "medium",
    "provider": "codex",
    "label": "GPT-5.5",
    "sortIndex": 85
  },
  {
    "key": "claude-opus-4-8|max",
    "model": "claude-opus-4-8",
    "effort": "max",
    "effectiveReasoning": "max",
    "provider": "claude",
    "label": "Opus 4.8",
    "sortIndex": 84
  },
  {
    "key": "claude-opus-4-6|default",
    "model": "claude-opus-4-6",
    "effort": "default",
    "effectiveReasoning": "high",
    "provider": "claude",
    "label": "Opus 4.6",
    "sortIndex": 84
  },
  {
    "key": "gpt-5.5|low",
    "model": "gpt-5.5",
    "effort": "low",
    "effectiveReasoning": "low",
    "provider": "codex",
    "label": "GPT-5.5",
    "sortIndex": 84
  },
  {
    "key": "gpt-5.5|xhigh",
    "model": "gpt-5.5",
    "effort": "xhigh",
    "effectiveReasoning": "xhigh",
    "provider": "codex",
    "label": "GPT-5.5",
    "sortIndex": 80
  },
  {
    "key": "claude-opus-4-5|default",
    "model": "claude-opus-4-5",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "claude",
    "label": "Opus 4.5",
    "sortIndex": 79
  },
  {
    "key": "opencode/north-mini-code-free|default",
    "model": "opencode/north-mini-code-free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "opencode",
    "label": "North-mini Code",
    "sortIndex": 55
  },
  {
    "key": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "model": "kilo/nvidia/nemotron-3-super-120b-a12b:free",
    "effort": "default",
    "effectiveReasoning": "default",
    "provider": "kilo",
    "label": "Nemotron-3 Super",
    "sortIndex": 29
  }
];

export const SCAFFBENCH2_CELLS: readonly ScaffbenchCell[] = [
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 93
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.5187459999999993,
    "outTokens": 56222,
    "steps": 42
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.316778999999999,
    "outTokens": 31262,
    "steps": 47
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 4.242322,
    "outTokens": 62537,
    "steps": 59
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 62,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 30
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.2901379999999998,
    "outTokens": 7963,
    "steps": 9
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1515914999999999,
    "outTokens": 5168,
    "steps": 6
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1882139999999999,
    "outTokens": 6036,
    "steps": 8
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.2794015,
    "outTokens": 5119,
    "steps": 8
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 50,
    "costUsd": null,
    "outTokens": null,
    "steps": 1
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0284950000000002,
    "outTokens": 14168,
    "steps": 10
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.585712,
    "outTokens": 22347,
    "steps": 19
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7584619999999999,
    "outTokens": 8254,
    "steps": 11
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1336225,
    "outTokens": 14881,
    "steps": 15
  },
  {
    "modelKey": "claude-opus-4-8|default",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 33,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 4.975376999999999,
    "outTokens": 50030,
    "steps": 85
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.1580645000000005,
    "outTokens": 22755,
    "steps": 44
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.4924239999999998,
    "outTokens": 34495,
    "steps": 66
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.7674180000000006,
    "outTokens": 32341,
    "steps": 48
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.6139629999999996,
    "outTokens": 28690,
    "steps": 49
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0783010000000002,
    "outTokens": 2953,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0544375,
    "outTokens": 2406,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0699230000000002,
    "outTokens": 2818,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.037597,
    "outTokens": 1920,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 69,
    "cmdPct": 100,
    "costUsd": 1.4576044999999997,
    "outTokens": 6456,
    "steps": 9
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.8924055000000001,
    "outTokens": 7929,
    "steps": 12
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.3322955,
    "outTokens": 12569,
    "steps": 18
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0453765,
    "outTokens": 9521,
    "steps": 14
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.6401384999999999,
    "outTokens": 4477,
    "steps": 8
  },
  {
    "modelKey": "claude-opus-4-7|default",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.2560315000000002,
    "outTokens": 12999,
    "steps": 15
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 1.105671,
    "outTokens": 21556,
    "steps": 7
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.888613,
    "outTokens": 14795,
    "steps": 7
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.525074,
    "outTokens": 8307,
    "steps": 7
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.776771,
    "outTokens": 13738,
    "steps": 9
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.986703,
    "outTokens": 18708,
    "steps": 10
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.439728,
    "outTokens": 3956,
    "steps": 17
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.772497,
    "outTokens": 3454,
    "steps": 12
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.52218,
    "outTokens": 2834,
    "steps": 8
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.569819,
    "outTokens": 2398,
    "steps": 12
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.675077,
    "outTokens": 17755,
    "steps": 31
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.755312,
    "outTokens": 7627,
    "steps": 13
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.514862,
    "outTokens": 5026,
    "steps": 10
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.554795,
    "outTokens": 5072,
    "steps": 13
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.506404,
    "outTokens": 4058,
    "steps": 9
  },
  {
    "modelKey": "gpt-5.5|medium",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.489818,
    "outTokens": 10645,
    "steps": 39
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 67,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 71
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 37
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 62
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 41
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 62,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 29
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.599211,
    "outTokens": 12101,
    "steps": 10
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.236139,
    "outTokens": 13094,
    "steps": 11
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.8509490000000002,
    "outTokens": 14912,
    "steps": 12
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1272065000000002,
    "outTokens": 11010,
    "steps": 12
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.305569999999999,
    "outTokens": 47979,
    "steps": 28
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.089,
    "outTokens": 30233,
    "steps": 21
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.6982339999999998,
    "outTokens": 30137,
    "steps": 13
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.790079,
    "outTokens": 32720,
    "steps": 12
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.7787005000000002,
    "outTokens": 27001,
    "steps": 21
  },
  {
    "modelKey": "claude-opus-4-8|max",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.4953595,
    "outTokens": 52440,
    "steps": 30
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 2.058678,
    "outTokens": 43940,
    "steps": 84
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.7051285000000002,
    "outTokens": 13621,
    "steps": 29
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.9144720000000001,
    "outTokens": 16992,
    "steps": 41
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.1225245,
    "outTokens": 24777,
    "steps": 28
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": 1.8712909999999996,
    "outTokens": 22974,
    "steps": 45
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.784568,
    "outTokens": 2686,
    "steps": 6
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.746151,
    "outTokens": 1847,
    "steps": 6
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7437195000000001,
    "outTokens": 1945,
    "steps": 6
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.645769,
    "outTokens": 1680,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": 1.9115654999999996,
    "outTokens": 14822,
    "steps": 35
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.5456175,
    "outTokens": 4252,
    "steps": 7
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.49644599999999994,
    "outTokens": 3664,
    "steps": 7
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.4296135,
    "outTokens": 2181,
    "steps": 6
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.5790955000000001,
    "outTokens": 4467,
    "steps": 9
  },
  {
    "modelKey": "claude-opus-4-6|default",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.2879935000000002,
    "outTokens": 14260,
    "steps": 20
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 1.070957,
    "outTokens": 15647,
    "steps": 10
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.395625,
    "outTokens": 7441,
    "steps": 4
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.514662,
    "outTokens": 7853,
    "steps": 8
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.680183,
    "outTokens": 12096,
    "steps": 12
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.631062,
    "outTokens": 11887,
    "steps": 7
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.559511,
    "outTokens": 2651,
    "steps": 9
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.387731,
    "outTokens": 2364,
    "steps": 9
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 50,
    "costUsd": 0.477758,
    "outTokens": 6951,
    "steps": 8
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.554676,
    "outTokens": 1933,
    "steps": 10
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.308691,
    "outTokens": 19483,
    "steps": 29
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.69381,
    "outTokens": 5383,
    "steps": 15
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.492653,
    "outTokens": 3833,
    "steps": 12
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.567983,
    "outTokens": 4366,
    "steps": 14
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.384351,
    "outTokens": 2913,
    "steps": 9
  },
  {
    "modelKey": "gpt-5.5|low",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.931419,
    "outTokens": 12517,
    "steps": 21
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 4
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.419419,
    "outTokens": 59891,
    "steps": 13
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.255711,
    "outTokens": 24665,
    "steps": 21
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.35113,
    "outTokens": 50553,
    "steps": 17
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 77,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": null,
    "steps": 2
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.6584,
    "outTokens": 43175,
    "steps": 61
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.915212,
    "outTokens": 10201,
    "steps": 12
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.00377,
    "outTokens": 11905,
    "steps": 17
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.799656,
    "outTokens": 9015,
    "steps": 11
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.004675,
    "outTokens": 42468,
    "steps": 37
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 4.768281,
    "outTokens": 56479,
    "steps": 77
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.840602,
    "outTokens": 12958,
    "steps": 18
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.409481,
    "outTokens": 16842,
    "steps": 23
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.535211,
    "outTokens": 19234,
    "steps": 35
  },
  {
    "modelKey": "gpt-5.5|xhigh",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.743197,
    "outTokens": 30280,
    "steps": 46
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 2.488206,
    "outTokens": 48214,
    "steps": 98
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.504259,
    "outTokens": 26009,
    "steps": 55
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.6725255,
    "outTokens": 33235,
    "steps": 56
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 85,
    "cmdPct": 100,
    "costUsd": 1.6547014999999996,
    "outTokens": 33448,
    "steps": 39
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": 2.0689174999999995,
    "outTokens": 23801,
    "steps": 50
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.322304,
    "outTokens": 3290,
    "steps": 10
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1641325,
    "outTokens": 2111,
    "steps": 8
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.1898485,
    "outTokens": 2361,
    "steps": 7
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0826185000000002,
    "outTokens": 1851,
    "steps": 5
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 3.967259499999999,
    "outTokens": 24287,
    "steps": 52
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0073785,
    "outTokens": 7209,
    "steps": 21
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7705749999999998,
    "outTokens": 4427,
    "steps": 14
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.5796804999999999,
    "outTokens": 2313,
    "steps": 7
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.8621845,
    "outTokens": 5325,
    "steps": 17
  },
  {
    "modelKey": "claude-opus-4-5|default",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.0043229999999999,
    "outTokens": 5867,
    "steps": 20
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 10,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9966,
    "steps": 47
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13457,
    "steps": 30
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 37567,
    "steps": 109
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10140,
    "steps": 40
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4596,
    "steps": 13
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1931,
    "steps": 6
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1659,
    "steps": 5
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 1491,
    "steps": 5
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 50,
    "costUsd": null,
    "outTokens": null,
    "steps": 0
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 10,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4700,
    "steps": 15
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 35784,
    "steps": 109
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 19125,
    "steps": 77
  },
  {
    "modelKey": "opencode/north-mini-code-free|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 4372,
    "steps": 13
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 29,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 21307,
    "steps": 42
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 58,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 24721,
    "steps": 81
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 14656,
    "steps": 36
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "wiredPct": 8,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 9073,
    "steps": 23
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 15207,
    "steps": 46
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "mcp",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6868,
    "steps": 5
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "mcp",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 50,
    "costUsd": null,
    "outTokens": 3566,
    "steps": 9
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "mcp",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 18773,
    "steps": 8
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "mcp",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 50,
    "costUsd": null,
    "outTokens": 154,
    "steps": 2
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "mcp",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 77,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 10009,
    "steps": 14
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "cli",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 10,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 32106,
    "steps": 25
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "cli",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 13010,
    "steps": 8
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "cli",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 6291,
    "steps": 13
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "cli",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 0,
    "cmdPct": 67,
    "costUsd": null,
    "outTokens": 580,
    "steps": 1
  },
  {
    "modelKey": "kilo/nvidia/nemotron-3-super-120b-a12b:free|default",
    "path": "cli",
    "spec": "multi-dotnet-ops",
    "scored": false,
    "corePass": false,
    "fullPass": false,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": null,
    "outTokens": 5301,
    "steps": 5
  }
];
