// AUTO-GENERATED from the ScaffBench 2.2 cohort summaries by
// scripts/build-scaffbench-2-2-data.ts — regenerate, don't hand-edit.
// 2.2 protocol: harness 2.2.1, self-verify prompt, quality gates ON (the board
// metric is the Full tier natively), 13 specs x 3 interleaved trials per row.
import type { ScaffbenchCell, ScaffbenchModel } from "./scaffbench-2-data";

export const SCAFFBENCH22_META = {
  "harnessVersion": "2.2.1",
  "promptVersion": "2026-07-17-round-2",
  "generatorVersion": "2.2.0",
  "generatedAt": "2026-07-18T01:55:06.035Z",
  "trialsPerSpec": 3,
  "indexWeights": {
    "macroPass": 0.75,
    "wired": 0.25,
    "cmd": 0
  }
} as const;

export const SCAFFBENCH22_SPECS = ["ai-search-workbench","rust-leptos-axum","python-ingestion-api","go-realtime-api","multi-dotnet-ops","ts-svelte-edge-orpc","dotnet-blazor-cqrs","multi-ts-go-grpc","java-spring-jooq-keycloak","elixir-broadway-absinthe","react-native-expo","frontier-polyglot-proto","frontier-effect-eventsourcing"] as const;

export const SCAFFBENCH22_MODELS: readonly ScaffbenchModel[] = [
  {
    "key": "gpt-5.6-luna|high",
    "model": "gpt-5.6-luna",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "GPT-5.6 Luna",
    "sortIndex": 78,
    "eligibility": "ranked"
  },
  {
    "key": "gpt-5.6-sol|high",
    "model": "gpt-5.6-sol",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "GPT-5.6 Sol",
    "sortIndex": 74,
    "eligibility": "ranked"
  },
  {
    "key": "gpt-5.6-terra|high",
    "model": "gpt-5.6-terra",
    "effort": "high",
    "effectiveReasoning": "high",
    "provider": "codex",
    "label": "GPT-5.6 Terra",
    "sortIndex": 74,
    "eligibility": "ranked"
  }
];

export const SCAFFBENCH22_CELLS: readonly ScaffbenchCell[] = [
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 97,
    "cmdPct": 100,
    "costUsd": 0.6259674666666667,
    "outTokens": 42677,
    "steps": 33,
    "durationMs": 672179,
    "lines": 1106
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.3890149333333333,
    "outTokens": 24915,
    "steps": 14,
    "durationMs": 516723,
    "lines": 558
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.25746386666666665,
    "outTokens": 21262,
    "steps": 21,
    "durationMs": 360615,
    "lines": 752
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.33865966666666675,
    "outTokens": 28047,
    "steps": 21,
    "durationMs": 491243,
    "lines": 5574
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 2,
    "passRate": 67,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 87,
    "cmdPct": 100,
    "costUsd": 0.4684007333333333,
    "outTokens": 35071,
    "steps": 26,
    "durationMs": 619662,
    "lines": 1160
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.3995279,
    "outTokens": 30214,
    "steps": 34,
    "durationMs": 570858,
    "lines": 23267
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.44606026666666665,
    "outTokens": 31378,
    "steps": 30,
    "durationMs": 528822,
    "lines": 1051
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 0.41194420000000004,
    "outTokens": 30075,
    "steps": 27,
    "durationMs": 535307,
    "lines": 8178
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 98,
    "cmdPct": 100,
    "costUsd": 0.3254803333333333,
    "outTokens": 24632,
    "steps": 14,
    "durationMs": 419945,
    "lines": 564
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.44696106666666663,
    "outTokens": 32158,
    "steps": 23,
    "durationMs": 594178,
    "lines": 1557
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 0.5701920666666667,
    "outTokens": 35710,
    "steps": 54,
    "durationMs": 639526,
    "lines": 1104
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.3551718666666666,
    "outTokens": 28114,
    "steps": 24,
    "durationMs": 495022,
    "lines": 914
  },
  {
    "modelKey": "gpt-5.6-luna|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.35035013333333337,
    "outTokens": 30963,
    "steps": 19,
    "durationMs": 515570,
    "lines": 503
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 97,
    "cmdPct": 100,
    "costUsd": 3.9929473333333334,
    "outTokens": 42966,
    "steps": 31,
    "durationMs": 841874,
    "lines": 7859
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 1.396316,
    "outTokens": 20419,
    "steps": 9,
    "durationMs": 468649,
    "lines": 889
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 1.4051763333333334,
    "outTokens": 22340,
    "steps": 15,
    "durationMs": 451344,
    "lines": 1198
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 95,
    "cmdPct": 100,
    "costUsd": 1.7287306666666666,
    "outTokens": 26433,
    "steps": 19,
    "durationMs": 546431,
    "lines": 6383
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 2,
    "passRate": 67,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 2.645091,
    "outTokens": 35756,
    "steps": 24,
    "durationMs": 847365,
    "lines": 1398
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 3.522418666666667,
    "outTokens": 37433,
    "steps": 28,
    "durationMs": 786371,
    "lines": 38620
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.474833,
    "outTokens": 24597,
    "steps": 14,
    "durationMs": 513354,
    "lines": 1085
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 2.5075076666666667,
    "outTokens": 31904,
    "steps": 21,
    "durationMs": 622989,
    "lines": 5109
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 2,
    "passRate": 67,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.6771855,
    "outTokens": 25911,
    "steps": 11,
    "durationMs": 481261,
    "lines": 1036
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 2.895477,
    "outTokens": 36251,
    "steps": 23,
    "durationMs": 860740,
    "lines": 1253
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 2.264329,
    "outTokens": 25564,
    "steps": 46,
    "durationMs": 543484,
    "lines": 892
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 1.4725746666666668,
    "outTokens": 24497,
    "steps": 17,
    "durationMs": 512244,
    "lines": 1550
  },
  {
    "modelKey": "gpt-5.6-sol|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.9832886666666667,
    "outTokens": 19190,
    "steps": 11,
    "durationMs": 356954,
    "lines": 877
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "ai-search-workbench",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.993214,
    "outTokens": 27448,
    "steps": 19,
    "durationMs": 430672,
    "lines": 1099
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "rust-leptos-axum",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.5610858333333333,
    "outTokens": 13953,
    "steps": 16,
    "durationMs": 304966,
    "lines": 475
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "python-ingestion-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.46535375,
    "outTokens": 12938,
    "steps": 9,
    "durationMs": 334196,
    "lines": 630
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "go-realtime-api",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.5250713333333333,
    "outTokens": 17851,
    "steps": 14,
    "durationMs": 411167,
    "lines": 4415
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "multi-dotnet-ops",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 2,
    "qualityPassRate": 67,
    "wiredPct": 92,
    "cmdPct": 100,
    "costUsd": 0.5800255,
    "outTokens": 16544,
    "steps": 14,
    "durationMs": 356622,
    "lines": 746
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "ts-svelte-edge-orpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 97,
    "cmdPct": 100,
    "costUsd": 0.8165203333333334,
    "outTokens": 19300,
    "steps": 18,
    "durationMs": 378653,
    "lines": 23777
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "dotnet-blazor-cqrs",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.5943468333333334,
    "outTokens": 17457,
    "steps": 12,
    "durationMs": 328840,
    "lines": 1597
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "multi-ts-go-grpc",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 90,
    "cmdPct": 100,
    "costUsd": 0.5196891666666666,
    "outTokens": 16252,
    "steps": 17,
    "durationMs": 326911,
    "lines": 7967
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "java-spring-jooq-keycloak",
    "scored": true,
    "corePass": true,
    "fullPass": true,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 3,
    "qualityPassRate": 100,
    "wiredPct": 98,
    "cmdPct": 100,
    "costUsd": 0.489417,
    "outTokens": 13906,
    "steps": 13,
    "durationMs": 263707,
    "lines": 376
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "elixir-broadway-absinthe",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 2,
    "passRate": 67,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 1,
    "qualityPassRate": 33,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.7842288333333333,
    "outTokens": 20780,
    "steps": 19,
    "durationMs": 451452,
    "lines": 629
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "react-native-expo",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 0,
    "passRate": 0,
    "passAny": false,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 88,
    "cmdPct": 100,
    "costUsd": 1.0675993333333333,
    "outTokens": 23192,
    "steps": 33,
    "durationMs": 473574,
    "lines": 968
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "frontier-polyglot-proto",
    "scored": true,
    "corePass": false,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 1,
    "passRate": 33,
    "passAny": true,
    "passAll": false,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.499245,
    "outTokens": 15328,
    "steps": 16,
    "durationMs": 267279,
    "lines": 714
  },
  {
    "modelKey": "gpt-5.6-terra|high",
    "path": "prompt",
    "spec": "frontier-effect-eventsourcing",
    "scored": true,
    "corePass": true,
    "fullPass": false,
    "trials": 3,
    "scoredTrials": 3,
    "passCount": 3,
    "passRate": 100,
    "passAny": true,
    "passAll": true,
    "qualityPassCount": 0,
    "qualityPassRate": 0,
    "wiredPct": 100,
    "cmdPct": 100,
    "costUsd": 0.38242766666666667,
    "outTokens": 14877,
    "steps": 9,
    "durationMs": 191217,
    "lines": 425
  }
];
