/**
 * Generates `src/lib/docs/cli-flags-data.ts` from the shared CLI flag registry
 * in `@better-fullstack/types`. The docs CLI reference renders `<CliFlagTable>`
 * from that module so the flag/default tables never drift from the real
 * generator surface. Run via `bun run docs:cli-flags` (wired into `prebuild`).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { getCliFlagReference } from "@better-fullstack/types";

const WEB_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUTPUT_PATH = join(WEB_ROOT, "src/lib/docs/cli-flags-data.ts");

const groups = getCliFlagReference();

const header = `// AUTO-GENERATED by scripts/generate-cli-flags-data.ts — DO NOT EDIT.
// Source of truth: @better-fullstack/types (CLI_FLAG_GROUP_DEFINITIONS).
// Regenerate with: bun run docs:cli-flags
`;

const body = `export type CliFlagRow = {
  flag: string;
  summary: string;
  values: string[];
  valueHint: string | null;
  defaultValue: string | null;
  multiple: boolean;
};

export type CliFlagGroup = {
  id: string;
  title: string;
  description: string;
  flags: CliFlagRow[];
};

export const CLI_FLAG_GROUPS: CliFlagGroup[] = ${JSON.stringify(
  groups.map((group) => ({
    id: group.id,
    title: group.title,
    description: group.description,
    flags: group.flags.map((flag) => ({
      flag: flag.flag,
      summary: flag.summary,
      values: flag.values,
      valueHint: flag.valueHint,
      defaultValue: flag.defaultValue,
      multiple: flag.multiple,
    })),
  })),
  null,
  2,
)};

export const CLI_FLAG_GROUPS_BY_ID: Record<string, CliFlagGroup> = Object.fromEntries(
  CLI_FLAG_GROUPS.map((group) => [group.id, group]),
);
`;

writeFileSync(OUTPUT_PATH, `${header}\n${body}`);
// eslint-disable-next-line no-console
console.log(`Generated ${groups.length} CLI flag groups -> ${OUTPUT_PATH}`);
