import {
  AISchema,
  APISchema,
  AddonsSchema,
  AiDocsSchema,
  AnalyticsSchema,
  AnimationSchema,
  AstroIntegrationSchema,
  AuthSchema,
  BackendSchema,
  BotProtectionSchema,
  CMSSchema,
  CSSFrameworkSchema,
  CachingSchema,
  DartMobileSchema,
  DatabaseSchema,
  DatabaseSetupSchema,
  DotnetApiSchema,
  DotnetAuthSchema,
  DotnetCachingSchema,
  DotnetDeploySchema,
  DotnetFrontendSchema,
  DotnetJobQueueSchema,
  DotnetLibrariesSchema,
  DotnetObservabilitySchema,
  DotnetOrmSchema,
  DotnetRealtimeSchema,
  DotnetTestingSchema,
  DotnetValidationSchema,
  DotnetWebFrameworkSchema,
  EcommerceSchema,
  EcosystemSchema,
  EffectSchema,
  ElixirApiSchema,
  ElixirApplicationFrameworkSchema,
  ElixirAuthSchema,
  ElixirCachingSchema,
  ElixirClusteringSchema,
  ElixirDeploySchema,
  ElixirDocumentationSchema,
  ElixirEmailSchema,
  ElixirHttpSchema,
  ElixirHttpServerSchema,
  ElixirI18nSchema,
  ElixirJobsSchema,
  ElixirJsonSchema,
  ElixirLibrariesSchema,
  ElixirObservabilitySchema,
  ElixirOrmSchema,
  ElixirQualitySchema,
  ElixirRealtimeSchema,
  ElixirTestingSchema,
  ElixirValidationSchema,
  ElixirWebFrameworkSchema,
  EmailSchema,
  ExamplesSchema,
  FeatureFlagsSchema,
  FileStorageSchema,
  FileUploadSchema,
  FormsSchema,
  FrontendSchema,
  GoApiSchema,
  GoAuthSchema,
  GoCachingSchema,
  GoCliSchema,
  GoConfigSchema,
  GoDISchema,
  GoLoggingSchema,
  GoMessageQueueSchema,
  GoMigrationsSchema,
  GoObservabilitySchema,
  GoOrmSchema,
  GoProtoToolingSchema,
  GoQualitySchema,
  GoRealtimeSchema,
  GoTemplatingSchema,
  GoTestingSchema,
  GoValidationSchema,
  GoWebFrameworkSchema,
  I18nSchema,
  IntegrationsSchema,
  JavaApiSchema,
  JavaAuthSchema,
  JavaBuildToolSchema,
  JavaLanguageSchema,
  JavaLibrariesSchema,
  JavaLoggingSchema,
  JavaOrmSchema,
  JavaTestingLibrariesSchema,
  JavaWebFrameworkSchema,
  JobQueueSchema,
  KotlinMobileLibrariesSchema,
  KotlinMobileSchema,
  LoggingSchema,
  MobileDeepLinkingSchema,
  MobileLibrariesSchema,
  MobileNavigationSchema,
  MobileOTASchema,
  MobilePushSchema,
  MobileStorageSchema,
  MobileTestingSchema,
  MobileUISchema,
  ORMSchema,
  ObservabilitySchema,
  PackageManagerSchema,
  PaymentsSchema,
  PythonAiSchema,
  PythonApiSchema,
  PythonAuthSchema,
  PythonCachingSchema,
  PythonCliSchema,
  PythonCloudSdkSchema,
  PythonDataSchema,
  PythonGraphqlSchema,
  PythonHttpClientSchema,
  PythonMediaSchema,
  PythonMessageQueueSchema,
  PythonObservabilitySchema,
  PythonOrmSchema,
  PythonPackageManagerSchema,
  PythonQualitySchema,
  PythonRealtimeSchema,
  PythonServerSchema,
  PythonTaskQueueSchema,
  PythonTestingSchema,
  PythonValidationSchema,
  PythonWebFrameworkSchema,
  RateLimitSchema,
  RealtimeSchema,
  RuntimeSchema,
  RustApiSchema,
  RustAuthSchema,
  RustCachingSchema,
  RustCliSchema,
  RustErrorHandlingSchema,
  RustFrontendSchema,
  RustLibrariesSchema,
  RustLoggingSchema,
  RustMessageQueueSchema,
  RustObservabilitySchema,
  RustOrmSchema,
  RustRealtimeSchema,
  RustTemplatingSchema,
  RustWebFrameworkSchema,
  SearchSchema,
  ServerDeploySchema,
  ShadcnBaseColorSchema,
  ShadcnBaseSchema,
  ShadcnColorThemeSchema,
  ShadcnFontSchema,
  ShadcnIconLibrarySchema,
  ShadcnRadiusSchema,
  ShadcnStyleSchema,
  StateManagementSchema,
  SwiftMobileSchema,
  TestingSchema,
  UILibrarySchema,
  ValidationSchema,
  VectorDbSchema,
  VersionChannelSchema,
  WebDeploySchema,
  WebMcpSchema,
} from "@better-fullstack/types";
import { z } from "zod";

// Input schema fragments shared by the catalog, create, and stack-update operations.
export const mobileInputSchema = {
  mobileNavigation: MobileNavigationSchema.optional().describe("Mobile navigation"),
  mobileUI: MobileUISchema.optional().describe("Mobile UI"),
  mobileStorage: MobileStorageSchema.optional().describe("Mobile storage"),
  mobileTesting: MobileTestingSchema.optional().describe("Mobile testing"),
  mobilePush: MobilePushSchema.optional().describe("Mobile push notifications"),
  mobileOTA: MobileOTASchema.optional().describe("Mobile OTA updates"),
  mobileDeepLinking: MobileDeepLinkingSchema.optional().describe("Mobile deep linking"),
  mobileLibraries: z
    .array(MobileLibrariesSchema)
    .optional()
    .describe("Mobile application libraries"),
};

export const deploymentInputSchema = {
  dbSetup: DatabaseSetupSchema.optional().describe("Database hosting provider"),
  webDeploy: WebDeploySchema.optional().describe("Web deployment target"),
  serverDeploy: ServerDeploySchema.optional().describe("Server deployment target"),
};

export const crossEcosystemInputSchema = {
  rustWebFramework: RustWebFrameworkSchema.optional().describe("Rust web framework"),
  rustFrontend: RustFrontendSchema.optional().describe("Rust frontend (WASM)"),
  dotnetFrontend: DotnetFrontendSchema.optional().describe(".NET frontend (Blazor WebAssembly)"),
  kotlinMobile: KotlinMobileSchema.optional().describe("Kotlin mobile app"),
  kotlinMobileLibraries: z
    .array(KotlinMobileLibrariesSchema)
    .optional()
    .describe("Kotlin mobile libraries"),
  swiftMobile: SwiftMobileSchema.optional().describe("Swift mobile app"),
  dartMobile: DartMobileSchema.optional().describe("Dart mobile app"),
  rustOrm: RustOrmSchema.optional().describe("Rust ORM"),
  rustApi: RustApiSchema.optional().describe("Rust API layer"),
  rustCli: RustCliSchema.optional().describe("Rust CLI framework"),
  rustLibraries: z.array(RustLibrariesSchema).optional().describe("Rust libraries"),
  rustLogging: RustLoggingSchema.optional().describe("Rust logging library"),
  rustErrorHandling: RustErrorHandlingSchema.optional().describe("Rust error handling library"),
  rustCaching: RustCachingSchema.optional().describe("Rust caching library"),
  rustAuth: RustAuthSchema.optional().describe("Rust authentication library"),
  rustRealtime: RustRealtimeSchema.optional().describe("Rust realtime library"),
  rustMessageQueue: RustMessageQueueSchema.optional().describe("Rust message queue"),
  rustObservability: RustObservabilitySchema.optional().describe("Rust observability"),
  rustTemplating: RustTemplatingSchema.optional().describe("Rust template engine"),
  pythonWebFramework: PythonWebFrameworkSchema.optional().describe("Python web framework"),
  pythonOrm: PythonOrmSchema.optional().describe("Python ORM"),
  pythonValidation: PythonValidationSchema.optional().describe("Python validation"),
  pythonAi: z.array(PythonAiSchema).optional().describe("Python AI libraries"),
  pythonAuth: PythonAuthSchema.optional().describe("Python auth library"),
  pythonApi: PythonApiSchema.optional().describe("Python API framework"),
  pythonTaskQueue: PythonTaskQueueSchema.optional().describe("Python task queue"),
  pythonGraphql: PythonGraphqlSchema.optional().describe("Python GraphQL framework"),
  pythonQuality: PythonQualitySchema.optional().describe("Python code quality"),
  pythonTesting: z.array(PythonTestingSchema).optional().describe("Python testing libraries"),
  pythonCaching: PythonCachingSchema.optional().describe("Python caching library"),
  pythonRealtime: PythonRealtimeSchema.optional().describe("Python realtime library"),
  pythonObservability: PythonObservabilitySchema.optional().describe(
    "Python observability (OpenTelemetry, SigNoz, or Prometheus)",
  ),
  pythonCli: z.array(PythonCliSchema).optional().describe("Python CLI tooling"),
  pythonCloudSdk: PythonCloudSdkSchema.optional().describe("Python cloud SDK"),
  pythonHttpClient: PythonHttpClientSchema.optional().describe("Python HTTP client"),
  pythonData: z.array(PythonDataSchema).optional().describe("Python data/scientific libraries"),
  pythonMedia: PythonMediaSchema.optional().describe("Python media library"),
  pythonServer: PythonServerSchema.optional().describe("Python production server"),
  pythonPackageManager: PythonPackageManagerSchema.optional().describe("Python package manager"),
  pythonMessageQueue: PythonMessageQueueSchema.optional().describe("Python message queue client"),
  goWebFramework: GoWebFrameworkSchema.optional().describe("Go web framework"),
  goOrm: GoOrmSchema.optional().describe("Go ORM"),
  goApi: GoApiSchema.optional().describe("Go API layer"),
  goCli: GoCliSchema.optional().describe("Go CLI framework"),
  goLogging: GoLoggingSchema.optional().describe("Go logging library"),
  goAuth: GoAuthSchema.optional().describe("Go authentication library"),
  goTesting: z.array(GoTestingSchema).optional().describe("Go testing libraries"),
  goRealtime: GoRealtimeSchema.optional().describe("Go realtime/WebSocket library"),
  goMessageQueue: GoMessageQueueSchema.optional().describe("Go message queue"),
  goCaching: GoCachingSchema.optional().describe("Go caching library"),
  goConfig: GoConfigSchema.optional().describe("Go config management"),
  goObservability: GoObservabilitySchema.optional().describe(
    "Go observability (OpenTelemetry, SigNoz, or Prometheus)",
  ),
  goValidation: GoValidationSchema.optional().describe("Go validation"),
  goQuality: GoQualitySchema.optional().describe("Go code quality"),
  goMigrations: GoMigrationsSchema.optional().describe("Go database migrations"),
  goTemplating: GoTemplatingSchema.optional().describe("Go templating"),
  goProtoTooling: GoProtoToolingSchema.optional().describe("Go protobuf tooling"),
  goDI: GoDISchema.optional().describe("Go dependency injection"),
  javaLanguage: JavaLanguageSchema.optional().describe("JVM language (java, kotlin)"),
  javaWebFramework: JavaWebFrameworkSchema.optional().describe("Java web framework"),
  javaBuildTool: JavaBuildToolSchema.optional().describe("Java build tool"),
  javaOrm: JavaOrmSchema.optional().describe("Java ORM"),
  javaAuth: JavaAuthSchema.optional().describe("Java authentication library"),
  javaApi: JavaApiSchema.optional().describe("Java API layer"),
  javaLogging: JavaLoggingSchema.optional().describe("Java logging configuration"),
  javaLibraries: z.array(JavaLibrariesSchema).optional().describe("Java application libraries"),
  javaTestingLibraries: z
    .array(JavaTestingLibrariesSchema)
    .optional()
    .describe("Java testing libraries"),
  dotnetWebFramework: DotnetWebFrameworkSchema.optional().describe(".NET web framework"),
  dotnetOrm: DotnetOrmSchema.optional().describe(".NET ORM/data access"),
  dotnetAuth: DotnetAuthSchema.optional().describe(".NET authentication library"),
  dotnetApi: DotnetApiSchema.optional().describe(".NET API style"),
  dotnetTesting: z.array(DotnetTestingSchema).optional().describe(".NET testing libraries"),
  dotnetJobQueue: DotnetJobQueueSchema.optional().describe(".NET jobs and scheduling"),
  dotnetRealtime: DotnetRealtimeSchema.optional().describe(".NET realtime feature"),
  dotnetObservability: z
    .array(DotnetObservabilitySchema)
    .optional()
    .describe(".NET observability/logging libraries"),
  dotnetValidation: DotnetValidationSchema.optional().describe(".NET validation"),
  dotnetCaching: DotnetCachingSchema.optional().describe(".NET caching library"),
  dotnetDeploy: DotnetDeploySchema.optional().describe(".NET deployment target"),
  dotnetLibraries: z.array(DotnetLibrariesSchema).optional().describe(".NET application libraries"),
  elixirWebFramework: ElixirWebFrameworkSchema.optional().describe("Elixir web framework"),
  elixirOrm: ElixirOrmSchema.optional().describe("Elixir persistence layer"),
  elixirAuth: ElixirAuthSchema.optional().describe("Elixir authentication"),
  elixirApi: ElixirApiSchema.optional().describe("Elixir API layer"),
  elixirRealtime: ElixirRealtimeSchema.optional().describe("Elixir realtime feature"),
  elixirJobs: ElixirJobsSchema.optional().describe("Elixir jobs and scheduling"),
  elixirValidation: ElixirValidationSchema.optional().describe("Elixir validation/data"),
  elixirHttp: ElixirHttpSchema.optional().describe("Elixir HTTP client"),
  elixirJson: ElixirJsonSchema.optional().describe("Elixir JSON library"),
  elixirEmail: ElixirEmailSchema.optional().describe("Elixir email library"),
  elixirCaching: ElixirCachingSchema.optional().describe("Elixir caching library"),
  elixirObservability: ElixirObservabilitySchema.optional().describe("Elixir observability"),
  elixirTesting: ElixirTestingSchema.optional().describe("Elixir testing library"),
  elixirQuality: ElixirQualitySchema.optional().describe("Elixir code quality/security"),
  elixirI18n: ElixirI18nSchema.optional().describe("Elixir localization"),
  elixirHttpServer: ElixirHttpServerSchema.optional().describe("Elixir HTTP server"),
  elixirApplicationFramework: ElixirApplicationFrameworkSchema.optional().describe(
    "Elixir application framework",
  ),
  elixirDocumentation: ElixirDocumentationSchema.optional().describe(
    "Elixir documentation tooling",
  ),
  elixirClustering: ElixirClusteringSchema.optional().describe("Elixir clustering"),
  elixirDeploy: ElixirDeploySchema.optional().describe("Elixir deployment target"),
  elixirLibraries: z.array(ElixirLibrariesSchema).optional().describe("Elixir libraries"),
};

export const MCP_PLAN_CREATE_SCHEMA = {
  projectName: z.string().optional().describe("Project name (kebab-case)"),
  part: z
    .array(z.string())
    .optional()
    .describe("Stack graph part binding, e.g. frontend:typescript:next or backend.orm:go:gorm"),
  addons: z.array(AddonsSchema).optional().describe("Deprecated alias for tooling part bindings"),
  ecosystem: EcosystemSchema.optional().describe("Language ecosystem (default: typescript)"),
  frontend: z.array(FrontendSchema).optional().describe("Frontend frameworks (TypeScript only)"),
  backend: BackendSchema.optional().describe("Backend framework"),
  runtime: RuntimeSchema.optional().describe("JavaScript runtime"),
  database: DatabaseSchema.optional().describe("Database type"),
  orm: ORMSchema.optional().describe("ORM"),
  api: APISchema.optional().describe("API layer"),
  auth: AuthSchema.optional().describe("Auth provider"),
  payments: PaymentsSchema.optional().describe("Payments provider"),
  email: EmailSchema.optional().describe("Email provider"),
  examples: z.array(ExamplesSchema).optional().describe("Example templates"),
  packageManager: PackageManagerSchema.optional().describe("Package manager (default: bun)"),
  cssFramework: CSSFrameworkSchema.optional().describe("CSS framework"),
  uiLibrary: UILibrarySchema.optional().describe("UI component library"),
  shadcnBase: ShadcnBaseSchema.optional().describe("shadcn/ui headless library"),
  shadcnStyle: ShadcnStyleSchema.optional().describe("shadcn/ui visual style"),
  shadcnIconLibrary: ShadcnIconLibrarySchema.optional().describe("shadcn/ui icon library"),
  shadcnColorTheme: ShadcnColorThemeSchema.optional().describe("shadcn/ui color theme"),
  shadcnBaseColor: ShadcnBaseColorSchema.optional().describe("shadcn/ui base neutral color"),
  shadcnFont: ShadcnFontSchema.optional().describe("shadcn/ui font"),
  shadcnRadius: ShadcnRadiusSchema.optional().describe("shadcn/ui border radius"),
  ai: AISchema.optional().describe("AI SDK"),
  stateManagement: StateManagementSchema.optional().describe("State management"),
  forms: FormsSchema.optional().describe("Forms library"),
  validation: ValidationSchema.optional().describe("Validation library"),
  testing: TestingSchema.optional().describe("Testing framework"),
  realtime: RealtimeSchema.optional().describe("Realtime library"),
  jobQueue: JobQueueSchema.optional().describe("Job queue"),
  animation: AnimationSchema.optional().describe("Animation library"),
  logging: LoggingSchema.optional().describe("Logging library"),
  observability: ObservabilitySchema.optional().describe("Observability"),
  featureFlags: FeatureFlagsSchema.optional().describe("Feature flag provider"),
  integrations: IntegrationsSchema.optional().describe("Third-party integrations SDK"),
  ecommerce: EcommerceSchema.optional().describe("E-commerce platform SDK"),
  search: SearchSchema.optional().describe("Search engine"),
  vectorDb: VectorDbSchema.optional().describe("Vector database (TypeScript only)"),
  caching: CachingSchema.optional().describe("Caching solution"),
  rateLimit: RateLimitSchema.optional().describe("Rate limiting solution"),
  botProtection: BotProtectionSchema.optional().describe("Bot verification provider"),
  i18n: I18nSchema.optional().describe("Internationalization (i18n) library"),
  cms: CMSSchema.optional().describe("CMS"),
  fileStorage: FileStorageSchema.optional().describe("File storage"),
  ...mobileInputSchema,
  fileUpload: FileUploadSchema.optional().describe("File upload"),
  ...deploymentInputSchema,
  effect: EffectSchema.optional().describe("Effect services (effect, effect-full)"),
  analytics: AnalyticsSchema.optional().describe("Privacy-focused analytics provider"),
  webMcp: WebMcpSchema.optional().describe("Experimental browser-native WebMCP tools"),
  astroIntegration: AstroIntegrationSchema.optional().describe(
    "Astro UI framework integration (react, vue, svelte, solid)",
  ),
  aiDocs: z
    .array(AiDocsSchema)
    .optional()
    .describe("AI documentation files (claude-md, agents-md, cursorrules)"),
  versionChannel: VersionChannelSchema.optional().describe(
    "Dependency version channel (stable, latest, beta)",
  ),
  ...crossEcosystemInputSchema,
};

const { addons: _createOnlyAddonsAlias, ...MCP_STACK_UPDATE_BASE_SCHEMA } = MCP_PLAN_CREATE_SCHEMA;

export const MCP_STACK_UPDATE_SCHEMA = {
  ...MCP_STACK_UPDATE_BASE_SCHEMA,
  projectDir: z.string().describe("Absolute path to the existing Better-Fullstack project"),
  acknowledgeArchitectureChange: z
    .boolean()
    .optional()
    .describe(
      "Acknowledge that this update replaces an existing database/orm/auth/api/backend/runtime choice. Required to apply architecture-changing updates; data and schema are NOT migrated automatically.",
    ),
};
