import type { PublishedStackSeed } from "./types";

const INITIAL_PUBLICATION_DATE = "2026-07-17";
const SEARCH_GROWTH_PUBLICATION_DATE = "2026-07-30";

export const PUBLISHED_STACK_SEEDS = [
  {
    slug: "nextjs-drizzle-better-auth",
    status: "published",
    priority: 100,
    primaryKeyword: "Next.js + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js auth template", "Next.js Drizzle boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
    },
    guideUrl: "/guides/typescript/nextjs-drizzle-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-prisma-better-auth",
    status: "published",
    priority: 95,
    primaryKeyword: "Next.js + Prisma + Better Auth Starter",
    keywordAliases: ["Next.js Prisma template", "Next.js auth boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      codeQuality: ["biome"],
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-hono-drizzle-better-auth",
    status: "published",
    priority: 98,
    primaryKeyword: "Next.js + Hono + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js Hono template", "Next.js Hono boilerplate"],
    selection: { webFrontend: ["next"], database: "postgres" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-drizzle-better-auth",
    status: "published",
    priority: 94,
    primaryKeyword: "TanStack Start + Drizzle + Better Auth Starter",
    keywordAliases: ["TanStack Start template", "TanStack Start boilerplate"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
    },
    guideUrl: "/guides/typescript/create-tanstack-start-project",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-trpc-drizzle",
    status: "published",
    priority: 96,
    primaryKeyword: "TanStack Router + Hono + tRPC + Drizzle Starter",
    keywordAliases: ["TanStack Hono template", "Hono tRPC boilerplate"],
    selection: { database: "postgres" },
    guideUrl: "/guides/typescript/hono-trpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "react-router-hono-orpc-drizzle",
    status: "published",
    priority: 88,
    primaryKeyword: "React Router + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["React Router Hono template", "oRPC starter"],
    selection: { webFrontend: ["react-router"], api: "orpc" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-hono-drizzle",
    status: "published",
    priority: 92,
    primaryKeyword: "SvelteKit + Hono + Drizzle Starter",
    keywordAliases: ["SvelteKit Hono template", "SvelteKit API boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/sveltekit-hono-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-elysia-drizzle",
    status: "published",
    priority: 90,
    primaryKeyword: "SvelteKit + Elysia + Drizzle Starter",
    keywordAliases: ["SvelteKit Elysia template", "Elysia Drizzle boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      backend: "elysia",
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nuxt-prisma-better-auth",
    status: "published",
    priority: 91,
    primaryKeyword: "Nuxt + Prisma + Better Auth Starter",
    keywordAliases: ["Nuxt Prisma template", "Nuxt auth boilerplate"],
    selection: {
      webFrontend: ["nuxt"],
      runtime: "none",
      backend: "self-nuxt",
      database: "postgres",
      orm: "prisma",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/nuxt-prisma-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "astro-react-hono-drizzle",
    status: "published",
    priority: 87,
    primaryKeyword: "Astro + React + Hono + Drizzle Starter",
    keywordAliases: ["Astro Hono template", "Astro React API starter"],
    selection: {
      webFrontend: ["astro"],
      astroIntegration: "react",
      uiLibrary: "daisyui",
    },
    guideUrl: "/guides/typescript/astro-react-hono",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "solidstart-orpc-drizzle",
    status: "published",
    priority: 86,
    primaryKeyword: "SolidStart + oRPC + Drizzle Starter",
    keywordAliases: ["SolidStart template", "SolidStart oRPC boilerplate"],
    selection: {
      webFrontend: ["solid-start"],
      runtime: "none",
      backend: "self-solid-start",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/solidstart-orpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "angular-express-prisma",
    status: "published",
    priority: 82,
    primaryKeyword: "Angular + Express + Prisma Starter",
    keywordAliases: ["Angular Express template", "Angular Prisma boilerplate"],
    selection: {
      webFrontend: ["angular"],
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      auth: "none",
      uiLibrary: "none",
      api: "none",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "rust-axum-leptos-seaorm",
    status: "published",
    priority: 93,
    primaryKeyword: "Rust + Axum + Leptos + SeaORM Starter",
    keywordAliases: ["Rust fullstack template", "Axum Leptos boilerplate"],
    selection: { ecosystem: "rust", rustFrontend: "leptos" },
    guideUrl: "/guides/rust/axum-leptos-fullstack",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "python-fastapi-postgres-sqlalchemy",
    status: "published",
    priority: 97,
    primaryKeyword: "FastAPI + PostgreSQL + SQLAlchemy Starter",
    keywordAliases: ["FastAPI Postgres template", "SQLAlchemy API boilerplate"],
    selection: { ecosystem: "python", database: "postgres" },
    guideUrl: "/guides/python/fastapi-postgres-sqlalchemy",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "go-gin-postgres-gorm",
    status: "published",
    priority: 89,
    primaryKeyword: "Go + Gin + PostgreSQL + GORM Starter",
    keywordAliases: ["Go Gin template", "GORM API boilerplate"],
    selection: { ecosystem: "go", database: "postgres" },
    guideUrl: "/guides/go/gin-postgres-gorm",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-better-auth",
    status: "published",
    priority: 99,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Better Auth Starter",
    keywordAliases: ["TanStack Start Postgres starter", "TanStack Start Drizzle template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
    },
    guideUrl: "/guides/typescript/tanstack-start-postgres-drizzle",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-sqlite-prisma-better-auth",
    status: "published",
    priority: 90,
    primaryKeyword: "TanStack Start + SQLite + Prisma + Better Auth Starter",
    keywordAliases: ["TanStack Start Prisma starter", "TanStack Start SQLite template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "sqlite",
      orm: "prisma",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-resend",
    status: "published",
    priority: 93,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Resend Starter",
    keywordAliases: ["TanStack Start Resend starter", "TanStack Start email template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
      email: "resend",
    },
    guideUrl: "/guides/typescript/tanstack-start-resend",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-clerk",
    status: "published",
    priority: 89,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Clerk Starter",
    keywordAliases: ["TanStack Start Clerk starter", "TanStack Start authentication template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
      auth: "clerk",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-orpc-drizzle",
    status: "published",
    priority: 95,
    primaryKeyword: "TanStack Router + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["Hono oRPC starter", "TanStack Router oRPC template"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "hono",
      database: "postgres",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/hono-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-openapi-drizzle",
    status: "published",
    priority: 94,
    primaryKeyword: "TanStack Router + Hono + OpenAPI + Drizzle Starter",
    keywordAliases: ["Hono OpenAPI starter", "TanStack Router OpenAPI template"],
    selection: {
      webFrontend: ["tanstack-router"],
      nativeFrontend: [],
      backend: "hono",
      database: "postgres",
      api: "openapi",
      auth: "none",
    },
    guideUrl: "/guides/typescript/hono-openapi-drizzle",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-prisma-better-auth",
    status: "published",
    priority: 92,
    primaryKeyword: "TanStack Router + Hono + Prisma + Better Auth Starter",
    keywordAliases: ["Hono Prisma starter", "Hono Better Auth template"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "hono",
      database: "postgres",
      orm: "prisma",
    },
    guideUrl: "/guides/typescript/hono-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-hono-openapi-drizzle",
    status: "published",
    priority: 96,
    primaryKeyword: "Next.js + Hono + OpenAPI + Drizzle Starter",
    keywordAliases: ["Next.js Hono OpenAPI starter", "Next.js separate API template"],
    selection: {
      webFrontend: ["next"],
      nativeFrontend: [],
      backend: "hono",
      runtime: "bun",
      database: "postgres",
      api: "openapi",
      auth: "none",
    },
    guideUrl: "/guides/typescript/nextjs-hono-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-drizzle-clerk",
    status: "published",
    priority: 91,
    primaryKeyword: "Next.js + PostgreSQL + Drizzle + Clerk Starter",
    keywordAliases: ["Next.js Clerk starter", "Next.js Drizzle authentication template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      auth: "clerk",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-prisma-stripe-better-auth",
    status: "published",
    priority: 93,
    primaryKeyword: "Next.js + Prisma + Stripe + Better Auth SaaS Starter",
    keywordAliases: ["Next.js Stripe starter", "Next.js Prisma SaaS template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      payments: "stripe",
    },
    guideUrl: "/guides/typescript/nextjs-prisma-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-drizzle-resend-better-auth",
    status: "published",
    priority: 92,
    primaryKeyword: "Next.js + Drizzle + Resend + Better Auth Starter",
    keywordAliases: ["Next.js Resend starter", "Next.js transactional email template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      email: "resend",
    },
    guideUrl: "/guides/typescript/nextjs-drizzle-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-postgres-prisma-nextauth",
    status: "published",
    priority: 88,
    primaryKeyword: "Next.js + PostgreSQL + Prisma + NextAuth Starter",
    keywordAliases: ["NextAuth Prisma starter", "Next.js Auth.js Postgres template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      auth: "nextauth",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "python-fastapi-postgres-sqlmodel",
    status: "published",
    priority: 94,
    primaryKeyword: "FastAPI + PostgreSQL + SQLModel Starter",
    keywordAliases: ["FastAPI SQLModel template", "Python PostgreSQL API starter"],
    selection: {
      ecosystem: "python",
      database: "postgres",
      pythonOrm: "sqlmodel",
      pythonTesting: ["pytest"],
    },
    guideUrl: "/guides/python/fastapi-postgres-sqlmodel",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "python-django-postgres-rest-framework",
    status: "published",
    priority: 91,
    primaryKeyword: "Django + PostgreSQL + Django REST Framework Starter",
    keywordAliases: ["Django REST API starter", "Django Postgres template"],
    selection: {
      ecosystem: "python",
      database: "postgres",
      pythonWebFramework: "django",
      pythonOrm: "none",
      pythonApi: "django-rest-framework",
      pythonTesting: ["pytest"],
    },
    guideUrl: "/guides/python/django-rest-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "go-echo-postgres-sqlc",
    status: "published",
    priority: 90,
    primaryKeyword: "Go + Echo + PostgreSQL + SQLC Starter",
    keywordAliases: ["Go Echo SQLC starter", "Echo Postgres API template"],
    selection: {
      ecosystem: "go",
      database: "postgres",
      goWebFramework: "echo",
      goOrm: "sqlc",
      goTesting: ["testify"],
    },
    guideUrl: "/guides/go/echo-sqlc-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
] as const satisfies readonly PublishedStackSeed[];
