import type { PublishedStackSeed } from "./types";

const INITIAL_PUBLICATION_DATE = "2026-07-17";

export const PUBLISHED_STACK_SEEDS = [
  {
    slug: "nextjs-drizzle-better-auth",
    status: "published",
    priority: 100,
    primaryKeyword: "Next.js + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js auth template", "Next.js Drizzle boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
    },
    guideUrl: "/guides/typescript/nextjs-drizzle-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-prisma-better-auth",
    status: "published",
    priority: 95,
    primaryKeyword: "Next.js + Prisma + Better Auth Starter",
    keywordAliases: ["Next.js Prisma template", "Next.js auth boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      codeQuality: ["biome"],
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-hono-drizzle-better-auth",
    status: "published",
    priority: 98,
    primaryKeyword: "Next.js + Hono + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js Hono template", "Next.js Hono boilerplate"],
    selection: { webFrontend: ["next"], database: "postgres" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-drizzle-better-auth",
    status: "published",
    priority: 94,
    primaryKeyword: "TanStack Start + Drizzle + Better Auth Starter",
    keywordAliases: ["TanStack Start template", "TanStack Start boilerplate"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
    },
    guideUrl: "/guides/typescript/create-tanstack-start-project",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-trpc-drizzle",
    status: "published",
    priority: 96,
    primaryKeyword: "TanStack Router + Hono + tRPC + Drizzle Starter",
    keywordAliases: ["TanStack Hono template", "Hono tRPC boilerplate"],
    selection: { database: "postgres" },
    guideUrl: "/guides/typescript/hono-trpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "react-router-hono-orpc-drizzle",
    status: "published",
    priority: 88,
    primaryKeyword: "React Router + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["React Router Hono template", "oRPC starter"],
    selection: { webFrontend: ["react-router"], api: "orpc" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-hono-drizzle",
    status: "published",
    priority: 92,
    primaryKeyword: "SvelteKit + Hono + Drizzle Starter",
    keywordAliases: ["SvelteKit Hono template", "SvelteKit API boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/sveltekit-hono-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-elysia-drizzle",
    status: "published",
    priority: 90,
    primaryKeyword: "SvelteKit + Elysia + Drizzle Starter",
    keywordAliases: ["SvelteKit Elysia template", "Elysia Drizzle boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      backend: "elysia",
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nuxt-prisma-better-auth",
    status: "published",
    priority: 91,
    primaryKeyword: "Nuxt + Prisma + Better Auth Starter",
    keywordAliases: ["Nuxt Prisma template", "Nuxt auth boilerplate"],
    selection: {
      webFrontend: ["nuxt"],
      runtime: "none",
      backend: "self-nuxt",
      database: "postgres",
      orm: "prisma",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/nuxt-prisma-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "astro-react-hono-drizzle",
    status: "published",
    priority: 87,
    primaryKeyword: "Astro + React + Hono + Drizzle Starter",
    keywordAliases: ["Astro Hono template", "Astro React API starter"],
    selection: {
      webFrontend: ["astro"],
      astroIntegration: "react",
      uiLibrary: "daisyui",
    },
    guideUrl: "/guides/typescript/astro-react-hono",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "solidstart-orpc-drizzle",
    status: "published",
    priority: 86,
    primaryKeyword: "SolidStart + oRPC + Drizzle Starter",
    keywordAliases: ["SolidStart template", "SolidStart oRPC boilerplate"],
    selection: {
      webFrontend: ["solid-start"],
      runtime: "none",
      backend: "self-solid-start",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/solidstart-orpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "angular-express-prisma",
    status: "published",
    priority: 82,
    primaryKeyword: "Angular + Express + Prisma Starter",
    keywordAliases: ["Angular Express template", "Angular Prisma boilerplate"],
    selection: {
      webFrontend: ["angular"],
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      auth: "none",
      uiLibrary: "none",
      api: "none",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "rust-axum-leptos-seaorm",
    status: "published",
    priority: 93,
    primaryKeyword: "Rust + Axum + Leptos + SeaORM Starter",
    keywordAliases: ["Rust fullstack template", "Axum Leptos boilerplate"],
    selection: { ecosystem: "rust", rustFrontend: "leptos" },
    guideUrl: "/guides/rust/axum-leptos-fullstack",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "python-fastapi-postgres-sqlalchemy",
    status: "published",
    priority: 97,
    primaryKeyword: "FastAPI + PostgreSQL + SQLAlchemy Starter",
    keywordAliases: ["FastAPI Postgres template", "SQLAlchemy API boilerplate"],
    selection: { ecosystem: "python", database: "postgres" },
    guideUrl: "/guides/python/fastapi-postgres-sqlalchemy",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "go-gin-postgres-gorm",
    status: "published",
    priority: 89,
    primaryKeyword: "Go + Gin + PostgreSQL + GORM Starter",
    keywordAliases: ["Go Gin template", "GORM API boilerplate"],
    selection: { ecosystem: "go", database: "postgres" },
    guideUrl: "/guides/go/gin-postgres-gorm",
    updated: INITIAL_PUBLICATION_DATE,
  },
] as const satisfies readonly PublishedStackSeed[];
