import type { PublishedStackSeed } from "@/lib/stack-pages/types";

const INITIAL_PUBLICATION_DATE = "2026-07-17";
const SEARCH_GROWTH_PUBLICATION_DATE = "2026-07-30";
const ECOSYSTEM_EXPANSION_PUBLICATION_DATE = "2026-10-09";

export const PUBLISHED_STACK_SEEDS = [
  {
    slug: "nextjs-drizzle-better-auth",
    status: "published",
    priority: 100,
    primaryKeyword: "Next.js + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js auth template", "Next.js Drizzle boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
    },
    guideUrl: "/guides/typescript/nextjs-drizzle-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-prisma-better-auth",
    status: "published",
    priority: 95,
    primaryKeyword: "Next.js + Prisma + Better Auth Starter",
    keywordAliases: ["Next.js Prisma template", "Next.js auth boilerplate"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      codeQuality: ["biome"],
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-hono-drizzle-better-auth",
    status: "published",
    priority: 98,
    primaryKeyword: "Next.js + Hono + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js Hono template", "Next.js Hono boilerplate"],
    selection: { webFrontend: ["next"], database: "postgres" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-drizzle-better-auth",
    status: "published",
    priority: 94,
    primaryKeyword: "TanStack Start + Drizzle + Better Auth Starter",
    keywordAliases: ["TanStack Start template", "TanStack Start boilerplate"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
    },
    guideUrl: "/guides/typescript/create-tanstack-start-project",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-trpc-drizzle",
    status: "published",
    priority: 96,
    primaryKeyword: "TanStack Router + Hono + tRPC + Drizzle Starter",
    keywordAliases: ["TanStack Hono template", "Hono tRPC boilerplate"],
    selection: { database: "postgres" },
    guideUrl: "/guides/typescript/hono-trpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "react-router-hono-orpc-drizzle",
    status: "published",
    priority: 88,
    primaryKeyword: "React Router + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["React Router Hono template", "oRPC starter"],
    selection: { webFrontend: ["react-router"], api: "orpc" },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-hono-drizzle",
    status: "published",
    priority: 92,
    primaryKeyword: "SvelteKit + Hono + Drizzle Starter",
    keywordAliases: ["SvelteKit Hono template", "SvelteKit API boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/sveltekit-hono-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-elysia-drizzle",
    status: "published",
    priority: 90,
    primaryKeyword: "SvelteKit + Elysia + Drizzle Starter",
    keywordAliases: ["SvelteKit Elysia template", "Elysia Drizzle boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      backend: "elysia",
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "nuxt-prisma-better-auth",
    status: "published",
    priority: 91,
    primaryKeyword: "Nuxt + Prisma + Better Auth Starter",
    keywordAliases: ["Nuxt Prisma template", "Nuxt auth boilerplate"],
    selection: {
      webFrontend: ["nuxt"],
      runtime: "none",
      backend: "self-nuxt",
      database: "postgres",
      orm: "prisma",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/nuxt-prisma-better-auth",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "astro-react-hono-drizzle",
    status: "published",
    priority: 87,
    primaryKeyword: "Astro + React + Hono + Drizzle Starter",
    keywordAliases: ["Astro Hono template", "Astro React API starter"],
    selection: {
      webFrontend: ["astro"],
      astroIntegration: "react",
      uiLibrary: "daisyui",
    },
    guideUrl: "/guides/typescript/astro-react-hono",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "solidstart-orpc-drizzle",
    status: "published",
    priority: 86,
    primaryKeyword: "SolidStart + oRPC + Drizzle Starter",
    keywordAliases: ["SolidStart template", "SolidStart oRPC boilerplate"],
    selection: {
      webFrontend: ["solid-start"],
      runtime: "none",
      backend: "self-solid-start",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/solidstart-orpc-drizzle",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "angular-express-prisma",
    status: "published",
    priority: 82,
    primaryKeyword: "Angular + Express + Prisma Starter",
    keywordAliases: ["Angular Express template", "Angular Prisma boilerplate"],
    selection: {
      webFrontend: ["angular"],
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      auth: "none",
      uiLibrary: "none",
      api: "none",
    },
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "rust-axum-leptos-seaorm",
    status: "published",
    priority: 93,
    primaryKeyword: "Rust + Axum + Leptos + SeaORM Starter",
    keywordAliases: ["Rust fullstack template", "Axum Leptos boilerplate"],
    selection: { ecosystem: "rust", rustFrontend: "leptos" },
    guideUrl: "/guides/rust/axum-leptos-fullstack",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "python-fastapi-postgres-sqlalchemy",
    status: "published",
    priority: 97,
    primaryKeyword: "FastAPI + PostgreSQL + SQLAlchemy Starter",
    keywordAliases: ["FastAPI Postgres template", "SQLAlchemy API boilerplate"],
    selection: { ecosystem: "python", database: "postgres" },
    guideUrl: "/guides/python/fastapi-postgres-sqlalchemy",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "go-gin-postgres-gorm",
    status: "published",
    priority: 89,
    primaryKeyword: "Go + Gin + PostgreSQL + GORM Starter",
    keywordAliases: ["Go Gin template", "GORM API boilerplate"],
    selection: { ecosystem: "go", database: "postgres" },
    guideUrl: "/guides/go/gin-postgres-gorm",
    updated: INITIAL_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-better-auth",
    status: "published",
    priority: 99,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Better Auth Starter",
    keywordAliases: ["TanStack Start Postgres starter", "TanStack Start Drizzle template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
    },
    guideUrl: "/guides/typescript/tanstack-start-postgres-drizzle",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-sqlite-prisma-better-auth",
    status: "published",
    priority: 90,
    primaryKeyword: "TanStack Start + SQLite + Prisma + Better Auth Starter",
    keywordAliases: ["TanStack Start Prisma starter", "TanStack Start SQLite template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "sqlite",
      orm: "prisma",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-resend",
    status: "published",
    priority: 93,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Resend Starter",
    keywordAliases: ["TanStack Start Resend starter", "TanStack Start email template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
      email: "resend",
    },
    guideUrl: "/guides/typescript/tanstack-start-resend",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-postgres-drizzle-clerk",
    status: "published",
    priority: 89,
    primaryKeyword: "TanStack Start + PostgreSQL + Drizzle + Clerk Starter",
    keywordAliases: ["TanStack Start Clerk starter", "TanStack Start authentication template"],
    selection: {
      webFrontend: ["tanstack-start"],
      runtime: "none",
      backend: "self-tanstack-start",
      database: "postgres",
      auth: "clerk",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-orpc-drizzle",
    status: "published",
    priority: 95,
    primaryKeyword: "TanStack Router + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["Hono oRPC starter", "TanStack Router oRPC template"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "hono",
      database: "postgres",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/hono-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-openapi-drizzle",
    status: "published",
    priority: 94,
    primaryKeyword: "TanStack Router + Hono + OpenAPI + Drizzle Starter",
    keywordAliases: ["Hono OpenAPI starter", "TanStack Router OpenAPI template"],
    selection: {
      webFrontend: ["tanstack-router"],
      nativeFrontend: [],
      backend: "hono",
      database: "postgres",
      api: "openapi",
      auth: "none",
    },
    guideUrl: "/guides/typescript/hono-openapi-drizzle",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-prisma-better-auth",
    status: "published",
    priority: 92,
    primaryKeyword: "TanStack Router + Hono + Prisma + Better Auth Starter",
    keywordAliases: ["Hono Prisma starter", "Hono Better Auth template"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "hono",
      database: "postgres",
      orm: "prisma",
    },
    guideUrl: "/guides/typescript/hono-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-hono-openapi-drizzle",
    status: "published",
    priority: 96,
    primaryKeyword: "Next.js + Hono + OpenAPI + Drizzle Starter",
    keywordAliases: ["Next.js Hono OpenAPI starter", "Next.js separate API template"],
    selection: {
      webFrontend: ["next"],
      nativeFrontend: [],
      backend: "hono",
      runtime: "bun",
      database: "postgres",
      api: "openapi",
      auth: "none",
    },
    guideUrl: "/guides/typescript/nextjs-hono-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-drizzle-clerk",
    status: "published",
    priority: 91,
    primaryKeyword: "Next.js + PostgreSQL + Drizzle + Clerk Starter",
    keywordAliases: ["Next.js Clerk starter", "Next.js Drizzle authentication template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      auth: "clerk",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-prisma-stripe-better-auth",
    status: "published",
    priority: 93,
    primaryKeyword: "Next.js + Prisma + Stripe + Better Auth SaaS Starter",
    keywordAliases: ["Next.js Stripe starter", "Next.js Prisma SaaS template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      payments: "stripe",
    },
    guideUrl: "/guides/typescript/nextjs-prisma-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-drizzle-resend-better-auth",
    status: "published",
    priority: 92,
    primaryKeyword: "Next.js + Drizzle + Resend + Better Auth Starter",
    keywordAliases: ["Next.js Resend starter", "Next.js transactional email template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      email: "resend",
    },
    guideUrl: "/guides/typescript/nextjs-drizzle-better-auth",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-postgres-prisma-nextauth",
    status: "published",
    priority: 88,
    primaryKeyword: "Next.js + PostgreSQL + Prisma + NextAuth Starter",
    keywordAliases: ["NextAuth Prisma starter", "Next.js Auth.js Postgres template"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      auth: "nextauth",
    },
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "python-fastapi-postgres-sqlmodel",
    status: "published",
    priority: 94,
    primaryKeyword: "FastAPI + PostgreSQL + SQLModel Starter",
    keywordAliases: ["FastAPI SQLModel template", "Python PostgreSQL API starter"],
    selection: {
      ecosystem: "python",
      database: "postgres",
      pythonOrm: "sqlmodel",
      pythonTesting: ["pytest"],
    },
    guideUrl: "/guides/python/fastapi-postgres-sqlmodel",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "python-django-postgres-rest-framework",
    status: "published",
    priority: 91,
    primaryKeyword: "Django + PostgreSQL + Django REST Framework Starter",
    keywordAliases: ["Django REST API starter", "Django Postgres template"],
    selection: {
      ecosystem: "python",
      database: "postgres",
      pythonWebFramework: "django",
      pythonOrm: "none",
      pythonApi: "django-rest-framework",
      pythonTesting: ["pytest"],
    },
    guideUrl: "/guides/python/django-rest-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "go-echo-postgres-sqlc",
    status: "published",
    priority: 90,
    primaryKeyword: "Go + Echo + PostgreSQL + SQLC Starter",
    keywordAliases: ["Go Echo SQLC starter", "Echo Postgres API template"],
    selection: {
      ecosystem: "go",
      database: "postgres",
      goWebFramework: "echo",
      goOrm: "sqlc",
      goTesting: ["testify"],
    },
    guideUrl: "/guides/go/echo-sqlc-api",
    updated: SEARCH_GROWTH_PUBLICATION_DATE,
  },
  {
    slug: "java-spring-boot-postgres-jpa",
    status: "published",
    priority: 90,
    primaryKeyword: "Spring Boot + PostgreSQL + Spring Data JPA Starter",
    keywordAliases: ["Spring Boot JPA template", "Spring Boot Postgres starter"],
    selection: {
      ecosystem: "java",
      database: "postgres",
      javaWebFramework: "spring-boot",
      javaBuildTool: "maven",
      javaOrm: "spring-data-jpa",
      javaTestingLibraries: ["junit5"],
    },
    guideUrl: "/guides/java/spring-boot-postgres-jpa",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "java-spring-boot-security-jpa",
    status: "published",
    priority: 87,
    primaryKeyword: "Spring Boot + Spring Security + JPA + Flyway Starter",
    keywordAliases: ["Spring Security API template", "Secure Spring Boot starter"],
    selection: {
      ecosystem: "java",
      database: "postgres",
      javaWebFramework: "spring-boot",
      javaBuildTool: "gradle",
      javaOrm: "spring-data-jpa",
      javaAuth: "spring-security",
      javaLibraries: ["spring-actuator", "flyway"],
      javaTestingLibraries: ["junit5", "testcontainers"],
    },
    guideUrl: "/guides/java/spring-security-api",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "kotlin-ktor-gradle-api",
    status: "published",
    priority: 85,
    primaryKeyword: "Kotlin + Ktor + Gradle API Starter",
    keywordAliases: ["Ktor API template", "Kotlin Ktor boilerplate"],
    selection: {
      ecosystem: "java",
      database: "none",
      javaLanguage: "kotlin",
      javaWebFramework: "ktor",
      javaBuildTool: "gradle",
      javaOrm: "none",
      javaAuth: "none",
      javaApi: "none",
      javaTestingLibraries: ["junit5"],
    },
    guideUrl: "/guides/java/ktor-kotlin-api",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "java-quarkus-maven-rest-api",
    status: "published",
    priority: 84,
    primaryKeyword: "Quarkus + Maven REST API Starter",
    keywordAliases: ["Quarkus REST template", "Quarkus Java API starter"],
    selection: {
      ecosystem: "java",
      database: "none",
      javaWebFramework: "quarkus",
      javaBuildTool: "maven",
      javaOrm: "none",
      javaAuth: "none",
      javaApi: "none",
      javaTestingLibraries: ["junit5", "rest-assured"],
    },
    guideUrl: "/guides/java/quarkus-rest-api",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "dotnet-aspnet-core-postgres-efcore",
    status: "published",
    priority: 89,
    primaryKeyword: "ASP.NET Core + PostgreSQL + EF Core Starter",
    keywordAliases: ["ASP.NET Core EF Core template", ".NET Minimal API Postgres starter"],
    selection: {
      ecosystem: "dotnet",
      database: "postgres",
      dotnetWebFramework: "aspnet-minimal",
      dotnetOrm: "ef-core",
      dotnetAuth: "aspnet-identity",
      dotnetApi: "minimal-api",
      dotnetRealtime: "signalr",
      dotnetObservability: ["serilog"],
      dotnetValidation: "fluentvalidation",
      dotnetDeploy: "docker",
    },
    guideUrl: "/guides/dotnet/aspnet-core-efcore",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "dotnet-blazor-efcore-identity-sqlite",
    status: "published",
    priority: 86,
    primaryKeyword: "Blazor + EF Core + ASP.NET Identity + SQLite Starter",
    keywordAliases: ["Blazor EF Core template", "Blazor Identity starter"],
    selection: {
      ecosystem: "dotnet",
      database: "sqlite",
      dotnetWebFramework: "aspnet-blazor",
      dotnetOrm: "ef-core",
      dotnetAuth: "aspnet-identity",
      dotnetApi: "minimal-api",
      dotnetRealtime: "signalr",
      dotnetObservability: ["serilog"],
      dotnetDeploy: "docker",
    },
    guideUrl: "/guides/dotnet/blazor-efcore-sqlite",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "dotnet-minimal-api-dapper-postgres",
    status: "published",
    priority: 84,
    primaryKeyword: "ASP.NET Core Minimal API + Dapper + PostgreSQL Starter",
    keywordAliases: ["Dapper Minimal API template", ".NET Dapper Postgres starter"],
    selection: {
      ecosystem: "dotnet",
      database: "postgres",
      dotnetWebFramework: "aspnet-minimal",
      dotnetOrm: "dapper",
      dotnetAuth: "none",
      dotnetApi: "minimal-api",
      dotnetRealtime: "none",
      dotnetObservability: ["health-checks"],
      dotnetDeploy: "docker",
    },
    guideUrl: "/guides/dotnet/aspnet-minimal-api-dapper",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "dotnet-hot-chocolate-graphql-efcore",
    status: "published",
    priority: 83,
    primaryKeyword: "ASP.NET Core + Hot Chocolate GraphQL + EF Core Starter",
    keywordAliases: ["Hot Chocolate GraphQL template", ".NET GraphQL starter"],
    selection: {
      ecosystem: "dotnet",
      database: "postgres",
      dotnetWebFramework: "aspnet-minimal",
      dotnetOrm: "ef-core",
      dotnetAuth: "none",
      dotnetApi: "graphql-hotchocolate",
      dotnetTesting: ["xunit", "testcontainers-dotnet"],
      dotnetRealtime: "none",
      dotnetObservability: ["serilog", "health-checks"],
      dotnetDeploy: "docker",
    },
    guideUrl: "/guides/dotnet/hot-chocolate-graphql-efcore",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "elixir-phoenix-liveview-ecto",
    status: "published",
    priority: 88,
    primaryKeyword: "Phoenix LiveView + Ecto + PostgreSQL Starter",
    keywordAliases: ["Phoenix LiveView template", "LiveView Ecto starter"],
    selection: {
      ecosystem: "elixir",
      database: "postgres",
      elixirWebFramework: "phoenix-live-view",
      elixirOrm: "ecto-sql",
      elixirAuth: "none",
      elixirApi: "none",
      elixirRealtime: "live-view-streams",
      elixirJobs: "none",
      elixirDeploy: "docker",
    },
    guideUrl: "/guides/elixir/phoenix-liveview-ecto",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "elixir-phoenix-json-api-oban",
    status: "published",
    priority: 85,
    primaryKeyword: "Phoenix JSON API + Ecto + Oban Starter",
    keywordAliases: ["Phoenix Oban template", "Phoenix REST API starter"],
    selection: {
      ecosystem: "elixir",
      database: "postgres",
      elixirWebFramework: "phoenix",
      elixirOrm: "ecto-sql",
      elixirAuth: "none",
      elixirApi: "rest",
      elixirRealtime: "none",
      elixirJobs: "oban",
      elixirEmail: "swoosh",
      elixirDeploy: "fly",
    },
    guideUrl: "/guides/elixir/phoenix-oban-jobs",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "elixir-phoenix-absinthe-graphql",
    status: "published",
    priority: 83,
    primaryKeyword: "Phoenix + Absinthe GraphQL + Ecto Starter",
    keywordAliases: ["Absinthe GraphQL template", "Phoenix GraphQL starter"],
    selection: {
      ecosystem: "elixir",
      database: "postgres",
      elixirWebFramework: "phoenix",
      elixirOrm: "ecto-sql",
      elixirAuth: "none",
      elixirApi: "absinthe",
      elixirRealtime: "channels",
      elixirJobs: "none",
    },
    guideUrl: "/guides/elixir/phoenix-absinthe-graphql",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "expo-hono-trpc-drizzle-better-auth",
    status: "published",
    priority: 88,
    primaryKeyword: "Expo + Hono + tRPC + Better Auth Starter",
    keywordAliases: ["Expo Hono template", "React Native Better Auth starter"],
    selection: {
      webFrontend: [],
      nativeFrontend: ["native-uniwind"],
      backend: "hono",
      runtime: "bun",
      database: "sqlite",
      orm: "drizzle",
      auth: "better-auth",
      api: "trpc",
      mobileNavigation: "expo-router",
      mobileUI: "uniwind",
    },
    guideUrl: "/guides/react-native/expo-hono-trpc-better-auth",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "expo-convex",
    status: "published",
    priority: 84,
    primaryKeyword: "Expo + Convex Starter",
    keywordAliases: ["Expo Convex template", "React Native Convex starter"],
    selection: {
      webFrontend: [],
      nativeFrontend: ["native-uniwind"],
      backend: "convex",
      runtime: "none",
      database: "none",
      orm: "none",
      auth: "none",
      api: "none",
      mobileNavigation: "expo-router",
      mobileUI: "uniwind",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-start-convex",
    status: "published",
    priority: 87,
    primaryKeyword: "TanStack Start + Convex Starter",
    keywordAliases: ["TanStack Start Convex template", "Convex React starter"],
    selection: {
      webFrontend: ["tanstack-start"],
      backend: "convex",
      runtime: "none",
      database: "none",
      orm: "none",
      api: "none",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-convex-clerk",
    status: "published",
    priority: 86,
    primaryKeyword: "Next.js + Convex + Clerk Starter",
    keywordAliases: ["Next.js Convex template", "Convex Clerk starter"],
    selection: {
      webFrontend: ["next"],
      backend: "convex",
      runtime: "none",
      database: "none",
      orm: "none",
      api: "none",
      auth: "clerk",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-hono-prisma",
    status: "published",
    priority: 85,
    primaryKeyword: "SvelteKit + Hono + Prisma Starter",
    keywordAliases: ["SvelteKit Prisma template", "Hono Prisma boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      backend: "hono",
      database: "postgres",
      orm: "prisma",
      uiLibrary: "none",
      api: "orpc",
    },
    guideUrl: "/guides/typescript/sveltekit-hono-drizzle",
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "sveltekit-drizzle-better-auth",
    status: "published",
    priority: 86,
    primaryKeyword: "SvelteKit + Drizzle + Better Auth Starter",
    keywordAliases: ["SvelteKit fullstack template", "SvelteKit auth boilerplate"],
    selection: {
      webFrontend: ["svelte"],
      runtime: "none",
      backend: "self-svelte",
      database: "sqlite",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nuxt-elysia-drizzle",
    status: "published",
    priority: 82,
    primaryKeyword: "Nuxt + Elysia + Drizzle Starter",
    keywordAliases: ["Nuxt Elysia template", "Vue Elysia boilerplate"],
    selection: {
      webFrontend: ["nuxt"],
      backend: "elysia",
      database: "postgres",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nuxt-drizzle-better-auth",
    status: "published",
    priority: 85,
    primaryKeyword: "Nuxt + Drizzle + Better Auth Starter",
    keywordAliases: ["Nuxt Drizzle template", "Nuxt fullstack starter"],
    selection: {
      webFrontend: ["nuxt"],
      runtime: "none",
      backend: "self-nuxt",
      database: "postgres",
      orm: "drizzle",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-nestjs-typeorm",
    status: "published",
    priority: 84,
    primaryKeyword: "Next.js + NestJS + TypeORM Starter",
    keywordAliases: ["Next.js NestJS template", "NestJS TypeORM boilerplate"],
    selection: {
      webFrontend: ["next"],
      backend: "nestjs",
      runtime: "node",
      database: "postgres",
      orm: "typeorm",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-fastify-prisma",
    status: "published",
    priority: 83,
    primaryKeyword: "TanStack Router + Fastify + Prisma Starter",
    keywordAliases: ["Fastify Prisma template", "React Fastify boilerplate"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "fastify",
      runtime: "node",
      database: "postgres",
      orm: "prisma",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-elysia-better-auth",
    status: "published",
    priority: 84,
    primaryKeyword: "TanStack Router + Elysia + Drizzle + Better Auth Starter",
    keywordAliases: ["Elysia Better Auth template", "React Elysia starter"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "elysia",
      runtime: "bun",
      database: "postgres",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "react-router-express-mongodb-mongoose",
    status: "published",
    priority: 86,
    primaryKeyword: "MERN Starter: MongoDB + Express + React Router + Node.js",
    keywordAliases: ["MERN stack template", "Express Mongoose boilerplate"],
    selection: {
      webFrontend: ["react-router"],
      runtime: "node",
      backend: "express",
      database: "mongodb",
      orm: "mongoose",
      api: "orpc",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-express-postgres-drizzle",
    status: "published",
    priority: 85,
    primaryKeyword: "PERN Starter: PostgreSQL + Express + TanStack Router + Node.js",
    keywordAliases: ["PERN stack template", "Express Postgres boilerplate"],
    selection: {
      webFrontend: ["tanstack-router"],
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "solid-hono-orpc-drizzle",
    status: "published",
    priority: 81,
    primaryKeyword: "Solid + Hono + oRPC + Drizzle Starter",
    keywordAliases: ["SolidJS Hono template", "Solid oRPC starter"],
    selection: {
      webFrontend: ["solid"],
      backend: "hono",
      uiLibrary: "none",
      api: "orpc",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-supabase-drizzle-better-auth",
    status: "published",
    priority: 85,
    primaryKeyword: "Next.js + Supabase + Drizzle + Better Auth Starter",
    keywordAliases: ["Next.js Supabase template", "Supabase Drizzle starter"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      dbSetup: "supabase",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "nextjs-drizzle-polar-better-auth",
    status: "published",
    priority: 84,
    primaryKeyword: "Next.js + Drizzle + Polar + Better Auth Starter",
    keywordAliases: ["Next.js Polar template", "Polar payments starter"],
    selection: {
      webFrontend: ["next"],
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      payments: "polar",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
  {
    slug: "tanstack-router-hono-workers-d1",
    status: "published",
    priority: 83,
    primaryKeyword: "Hono + Cloudflare Workers + D1 + Drizzle Starter",
    keywordAliases: ["Hono Cloudflare Workers template", "Cloudflare D1 Drizzle starter"],
    selection: {
      webFrontend: ["tanstack-router"],
      backend: "hono",
      runtime: "workers",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "d1",
    },
    updated: ECOSYSTEM_EXPANSION_PUBLICATION_DATE,
  },
] as const satisfies readonly PublishedStackSeed[];
