export const PRESET_IDS = [
  "future-stack",
  "t3",
  "nextjs-saas",
  "nextjs-minimal",
  "mern",
  "pern",
  "tanstack-start",
  "tanstack-hono",
  "sveltekit-fullstack",
  "nuxt-fullstack",
  "astro-fullstack",
  "tanstack-fullstack",
  "angular-express",
  "qwik-city",
  "uniwind",
  "expo-bare",
  "ai-cli-agent-workbench",
  "rust-fullstack",
  "rust-api",
  "rust-grpc",
  "rust-cli",
  "python-fastapi",
  "python-django",
  "python-ai-agent",
  "python-ai-anthropic",
  "go-gin",
  "go-echo",
  "go-grpc",
  "go-cli",
  "java-spring",
  "java-jpa",
  "java-secure",
  "dotnet-minimal-api",
  "dotnet-graphql",
  "dotnet-worker",
  "elixir-phoenix-api",
  "elixir-liveview-full",
  "elixir-plain-worker",
  "example-ai-chat",
  "example-slack-bot",
  "example-discord-bot",
  "example-github-review-bot",
] as const;
export type PresetId = (typeof PRESET_IDS)[number];

export const PRESET_ALIASES = {
  saas: "nextjs-saas",
  "react-hono": "tanstack-hono",
  "sveltekit-hono": "sveltekit-fullstack",
  "nuxt-hono": "nuxt-fullstack",
  "astro-react": "astro-fullstack",
  "solidstart-fullstack": "future-stack",
  "solid-hono": "future-stack",
  "ai-cli-react-hono": "ai-cli-agent-workbench",
  "ai-cli-frontend-lab": "ai-cli-agent-workbench",
} as const satisfies Record<string, PresetId>;
export type PresetAlias = keyof typeof PRESET_ALIASES;
export const PRESET_ALIAS_IDS = Object.keys(PRESET_ALIASES) as [PresetAlias, ...PresetAlias[]];
