import type { PackageManager, ProjectConfig } from "./types";

export type CliDefaultProjectConfigBase = Omit<ProjectConfig, "projectDir">;

export function createCliDefaultProjectConfigBase(
  packageManager: PackageManager = "bun",
): CliDefaultProjectConfigBase {
  return {
    projectName: "my-app",
    relativePath: "my-app",
    ecosystem: "typescript",
    database: "sqlite",
    orm: "drizzle",
    backend: "hono",
    runtime: "bun",
    frontend: ["tanstack-router"],
    addons: ["turborepo"],
    examples: [],
    auth: "better-auth",
    payments: "none",
    email: "none",
    fileUpload: "none",
    effect: "none",
    git: true,
    packageManager,
    versionChannel: "stable",
    install: true,
    dbSetup: "none",
    api: "trpc",
    webDeploy: "none",
    serverDeploy: "none",
    astroIntegration: "none",
    ai: "none",
    stateManagement: "none",
    forms: "react-hook-form",
    testing: "vitest",
    cssFramework: "tailwind",
    uiLibrary: "shadcn-ui",
    shadcnBase: "radix",
    shadcnStyle: "nova",
    shadcnIconLibrary: "lucide",
    shadcnColorTheme: "neutral",
    shadcnBaseColor: "neutral",
    shadcnFont: "inter",
    shadcnRadius: "default",
    validation: "zod",
    realtime: "none",
    jobQueue: "none",
    animation: "none",
    logging: "none",
    observability: "none",
    featureFlags: "none",
    analytics: "none",
    cms: "none",
    caching: "none",
    i18n: "none",
    search: "none",
    fileStorage: "none",
    rustWebFramework: "none",
    rustFrontend: "none",
    rustOrm: "none",
    rustApi: "none",
    rustCli: "none",
    rustLibraries: [],
    rustLogging: "tracing",
    rustErrorHandling: "anyhow-thiserror",
    rustCaching: "none",
    rustAuth: "none",
    pythonWebFramework: "fastapi",
    pythonOrm: "sqlalchemy",
    pythonValidation: "pydantic",
    pythonAi: [],
    pythonAuth: "none",
    pythonTaskQueue: "none",
    pythonGraphql: "none",
    pythonQuality: "ruff",
    goWebFramework: "gin",
    goOrm: "gorm",
    goApi: "none",
    goCli: "none",
    goLogging: "zap",
    goAuth: "none",
    aiDocs: ["claude-md"],
  };
}
