import type { BenchmarkSpec } from "../types";
import { AI_SEARCH_ADDONS, AI_SEARCH_FLAGS, AI_SEARCH_STACK } from "../constants";

export const AiSearchWorkbenchSpec: BenchmarkSpec = {
    id: "ai-search-workbench",
    title: "AI search workbench with separate semantic and full-text search",
    lane: "core",
    family: "typescript",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a TypeScript monorepo for an AI support/search workbench.",
      "Use a TanStack Router web app styled with Tailwind and shadcn/ui.",
      "Use a Hono backend on Bun.",
      "Use oRPC for the app API.",
      "Use PostgreSQL with Drizzle for relational app data.",
      "Use Better Auth for accounts.",
      "Use the Vercel AI SDK for AI features.",
      "Use Qdrant specifically for semantic vector search over embeddings.",
      "Use OpenSearch specifically for full-text document/admin search.",
      "Use Inngest for background indexing jobs.",
      "Use Pino logging and OpenTelemetry instrumentation.",
      "Use TanStack Store, TanStack Form, Valibot, Vitest + Playwright, and Paraglide.",
      "Include Turborepo, Biome, DevContainer, and GitHub Actions CI output.",
      "Do not add payments, email, realtime, CMS, file upload, file storage, feature flags, or deploy targets.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a production-grade AI support search starter. It needs account auth, relational app data, background indexing, semantic search for embeddings, full-text/admin search for documents, observability, tests, i18n, and CI. Keep it deploy-target neutral and do not include commerce/email/storage extras.",
    rightLibraryNotes: [
      "Qdrant must be used for semantic vector search.",
      "OpenSearch must be used for full-text document/admin search.",
      "Inngest must be used for background indexing jobs.",
      "oRPC must be used for the app API.",
    ],
    canonicalFlags: AI_SEARCH_FLAGS,
    expectedConfig: AI_SEARCH_STACK,
    expectedAddons: AI_SEARCH_ADDONS,
    strictMarkers: [
      { id: "frontend:tanstack-router", deps: ["@tanstack/react-router"] },
      { id: "backend:hono", deps: ["hono"] },
      { id: "api:orpc", deps: ["@orpc/server"], source: ["@orpc/"] },
      { id: "database:postgres+drizzle", deps: ["drizzle-orm"], source: ["drizzle-orm"] },
      { id: "auth:better-auth", deps: ["better-auth"], source: ["better-auth"] },
      { id: "ai:vercel-ai", deps: ["ai"] },
      {
        id: "vectorDb:qdrant",
        deps: ["@qdrant/js-client-rest"],
        source: ["@qdrant/js-client-rest"],
      },
      {
        id: "search:opensearch",
        deps: ["@opensearch-project/opensearch"],
        source: ["@opensearch-project/opensearch"],
      },
      { id: "jobQueue:inngest", deps: ["inngest"], source: ["inngest"] },
      { id: "logging:pino", deps: ["pino"], source: ["pino"] },
      { id: "observability:opentelemetry", deps: ["@opentelemetry/api"] },
      { id: "state:tanstack-store", deps: ["@tanstack/store"] },
      { id: "forms:tanstack-form", deps: ["@tanstack/react-form"] },
      { id: "validation:valibot", deps: ["valibot"] },
      { id: "testing:vitest-playwright", deps: ["vitest", "@playwright/test"] },
      {
        id: "i18n:paraglide",
        deps: ["@inlang/paraglide-js"],
        files: ["apps/web/project.inlang/settings.json"],
      },
      { id: "addon:biome", deps: ["@biomejs/biome"], files: ["biome.json"] },
      { id: "addon:devcontainer", files: [".devcontainer/devcontainer.json"] },
      { id: "addon:github-actions", files: [".github/workflows/ci.yml"] },
      { id: "forbidden:payments", forbiddenDeps: ["stripe", "@stripe/stripe-js", "polar-sh"] },
      { id: "forbidden:email", forbiddenDeps: ["resend", "nodemailer", "@react-email/components"] },
    ],
    acceptanceSets: {
      "web-framework": ["@tanstack/react-router", "next", "react-router", "@remix-run", "vite"],
      backend: ["hono", "express", "fastify", "elysia", "@nestjs/core"],
      "relational-db": ["drizzle-orm", "@prisma/client", "kysely", "typeorm", "sequelize"],
      auth: ["better-auth", "lucia", "@clerk", "next-auth", "@auth/", "@workos-inc"],
      ai: ["ai", "@ai-sdk", "openai", "@anthropic-ai", "langchain"],
      "semantic-search": [
        "@qdrant/js-client-rest",
        "pgvector",
        "weaviate-ts-client",
        "@pinecone-database/pinecone",
        "chromadb",
        "@zilliz/milvus2-sdk-node",
      ],
      "full-text-search": [
        "@opensearch-project/opensearch",
        "@elastic/elasticsearch",
        "meilisearch",
        "typesense",
        "algoliasearch",
      ],
      "background-jobs": [
        "inngest",
        "bullmq",
        "@trigger.dev",
        "graphile-worker",
        "pg-boss",
        "bee-queue",
      ],
      observability: ["@opentelemetry/api", "pino", "winston", "@sentry", "@logtail"],
      testing: ["vitest", "jest", "@playwright/test", "cypress"],
      i18n: ["@inlang/paraglide-js", "next-intl", "i18next", "react-i18next", "lingui"],
      ci: [".github/workflows", ".gitlab-ci.yml", ".circleci"],
    },
    validationProfile: {
      packageManager: "bun",
      qualityGate: true,
      doctorCheck: true,
      routeCheckCandidate: true,
    },
  };

