import type { BenchmarkSpec } from "@scaffbench/types";

import { AI_SEARCH_ADDONS, AI_SEARCH_FLAGS, AI_SEARCH_STACK } from "@scaffbench/constants";

export const AiSearchWorkbenchSpec: BenchmarkSpec = {
  id: "ai-search-workbench",
  introducedAt: "2026-08-21",
  title: "AI search workbench with split semantic/full-text search on the Vite+ toolchain",
  lane: "core",
  difficulty: 2,
  family: "typescript",
  supportedByBetterFullstack: true,
  requirements: [
    "Create a TypeScript monorepo for an AI support/search workbench: agents triage tickets, search past resolutions semantically, and admins search raw documents.",
    "Use a TanStack Router web app styled with Tailwind and shadcn/ui.",
    "Use a Hono backend on Bun.",
    "Use oRPC for the app API.",
    "Use PostgreSQL with Drizzle for relational app data only.",
    "Use Better Auth for accounts.",
    "Use the Vercel AI SDK for AI features.",
    "Use Qdrant for semantic vector search over embeddings. Postgres is present, but pgvector is not acceptable here, the vector workload must live in Qdrant.",
    "Use OpenSearch for full-text document/admin search. Do not collapse the two search modes into one engine.",
    "Use Inngest for background indexing jobs.",
    "Use Pino logging and OpenTelemetry instrumentation.",
    "Use TanStack Store, TanStack Form, Valibot, Vitest + Playwright, and Paraglide.",
    "Use the Vite+ toolchain (`vp`) for workspace scripts, linting, and formatting. Do not add Turborepo, Nx, or Biome.",
    "Include DevContainer and GitHub Actions CI output.",
    "Do not add payments, email, realtime, CMS, file upload, file storage, feature flags, or deploy targets.",
  ],
  naturalPrompt:
    "Build a production-grade AI support search starter. Support agents need semantic search over embedded past resolutions, admins need full-text search over raw documents, and the two workloads should not share one engine. It also needs account auth, relational app data, background indexing, observability, tests, i18n, CI, and a workspace toolchain for tasks, lint, and format. Keep it deploy-target neutral and do not include commerce/email/storage extras.",
  rightLibraryNotes: [
    "Qdrant must be used for semantic vector search; pgvector is not acceptable even though Postgres is present.",
    "OpenSearch must be used for full-text document/admin search.",
    "Inngest must be used for background indexing jobs.",
    "oRPC must be used for the app API.",
    "The Vite+ toolchain (vp) replaces Turborepo/Nx and Biome for workspace tasks, lint, and format.",
  ],
  canonicalFlags: AI_SEARCH_FLAGS,
  expectedConfig: AI_SEARCH_STACK,
  expectedAddons: AI_SEARCH_ADDONS,
  strictMarkers: [
    { id: "frontend:tanstack-router", deps: ["@tanstack/react-router"] },
    { id: "css:tailwind", deps: ["tailwindcss"] },
    { id: "ui:shadcn", files: ["components.json"] },
    { id: "backend:hono", deps: ["hono"] },
    { id: "api:orpc", deps: ["@orpc/server"], source: ["@orpc/"] },
    { id: "database:postgres+drizzle", deps: ["drizzle-orm"], source: ["drizzle-orm"] },
    { id: "auth:better-auth", deps: ["better-auth"], source: ["better-auth"] },
    { id: "ai:vercel-ai", deps: ["ai"] },
    {
      id: "vectorDb:qdrant",
      deps: ["@qdrant/js-client-rest"],
      source: ["@qdrant/js-client-rest"],
    },
    {
      id: "search:opensearch",
      deps: ["@opensearch-project/opensearch"],
      source: ["@opensearch-project/opensearch"],
    },
    { id: "jobQueue:inngest", deps: ["inngest"], source: ["inngest"] },
    { id: "logging:pino", deps: ["pino"], source: ["pino"] },
    { id: "observability:opentelemetry", deps: ["@opentelemetry/api"] },
    { id: "state:tanstack-store", deps: ["@tanstack/store"] },
    { id: "forms:tanstack-form", deps: ["@tanstack/react-form"] },
    { id: "validation:valibot", deps: ["valibot"] },
    { id: "testing:vitest-playwright", deps: ["vitest", "@playwright/test"] },
    {
      id: "i18n:paraglide",
      deps: ["@inlang/paraglide-js"],
      files: ["project.inlang/settings.json"],
    },
    { id: "addon:vite-plus", deps: ["vite-plus"] },
    { id: "addon:devcontainer", files: [".devcontainer/devcontainer.json"] },
    { id: "addon:github-actions", files: [".github/workflows/*.y*ml"] },
    { id: "forbidden:pgvector", forbiddenDeps: ["pgvector"] },
    { id: "forbidden:turborepo", forbiddenDeps: ["turbo"] },
    { id: "forbidden:nx", forbiddenDeps: ["nx", "@nx/"], forbiddenFiles: ["nx.json"] },
    { id: "forbidden:biome", forbiddenDeps: ["@biomejs/biome"] },
    { id: "forbidden:payments", forbiddenDeps: ["stripe", "@stripe/stripe-js", "polar-sh"] },
    { id: "forbidden:email", forbiddenDeps: ["resend", "nodemailer", "@react-email/components"] },
  ],
  acceptanceSets: {
    "web-framework": ["@tanstack/react-router", "next", "react-router", "@remix-run", "vite"],
    backend: ["hono", "express", "fastify", "elysia", "@nestjs/core"],
    "relational-db": ["drizzle-orm", "@prisma/client", "kysely", "typeorm", "sequelize"],
    auth: ["better-auth", "lucia", "@clerk", "next-auth", "@auth/", "@workos-inc"],
    ai: ["ai", "@ai-sdk", "openai", "@anthropic-ai", "langchain"],
    "semantic-search": [
      "@qdrant/js-client-rest",
      "pgvector",
      "weaviate-ts-client",
      "@pinecone-database/pinecone",
      "chromadb",
      "@zilliz/milvus2-sdk-node",
    ],
    "full-text-search": [
      "@opensearch-project/opensearch",
      "@elastic/elasticsearch",
      "meilisearch",
      "typesense",
      "algoliasearch",
    ],
    "background-jobs": [
      "inngest",
      "bullmq",
      "@trigger.dev",
      "graphile-worker",
      "pg-boss",
      "bee-queue",
    ],
    observability: ["@opentelemetry/api", "pino", "winston", "@sentry", "@logtail"],
    testing: ["vitest", "jest", "@playwright/test", "cypress"],
    i18n: ["@inlang/paraglide-js", "next-intl", "i18next", "react-i18next", "lingui"],
    toolchain: ["vite-plus", "turbo", "nx"],
    ci: [".github/workflows", ".gitlab-ci.yml", ".circleci"],
  },
  validationProfile: {
    packageManager: "bun",
    qualityGate: true,
    doctorCheck: true,
    routeCheckCandidate: true,
  },
};
