import type { BenchmarkSpec } from "../types";

export const DotnetBlazorCqrsSpec: BenchmarkSpec = {
    id: "dotnet-blazor-cqrs",
    title: ".NET Blazor app with Dapper, Duende IdentityServer, and HotChocolate GraphQL",
    lane: "core",
    family: "dotnet",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a .NET project using ASP.NET Blazor (not Minimal API or MVC).",
      "Use Dapper for data access (not EF Core).",
      "Use Duende IdentityServer for auth (not ASP.NET Identity).",
      "Use HotChocolate for a GraphQL API (not Minimal API or gRPC).",
      "Use PostgreSQL.",
      "Use NUnit with Moq and Testcontainers for .NET (not xUnit).",
      "Use Quartz.NET for background jobs (not Hangfire).",
      "Use SignalR for realtime.",
      "Use OpenTelemetry, NLog, and health checks for observability (not Serilog).",
      "Use FluentValidation, Redis caching, and Docker deploy output.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a .NET starter for an internal operations console. It needs a C# web UI, lightweight data access, a dedicated identity server, a GraphQL API, Postgres, background scheduling, realtime updates, validation, caching, observability, and container output. Choose the right .NET libraries rather than the framework defaults.",
    rightLibraryNotes: [
      "Blazor is required for the web framework.",
      "Dapper is required for data access (not EF Core).",
      "Duende IdentityServer is required for auth (not ASP.NET Identity).",
      "HotChocolate GraphQL is required (not Minimal API), with NUnit and Quartz.NET.",
    ],
    canonicalFlags: [
      "--ecosystem", "dotnet",
      "--database", "postgres",
      "--dotnet-web-framework", "aspnet-blazor",
      "--dotnet-orm", "dapper",
      "--dotnet-auth", "duende-identityserver",
      "--dotnet-api", "graphql-hotchocolate",
      "--dotnet-testing", "nunit", "moq", "testcontainers-dotnet",
      "--dotnet-job-queue", "quartz-net",
      "--dotnet-realtime", "signalr",
      "--dotnet-observability", "opentelemetry-dotnet", "nlog", "health-checks",
      "--dotnet-validation", "fluentvalidation",
      "--dotnet-caching", "redis",
      "--dotnet-deploy", "docker",
      "--auth", "none",
      "--email", "none",
      "--observability", "none",
      "--caching", "none",
      "--search", "none",
      "--ai-docs", "claude-md",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "dotnet",
      database: "postgres",
      dotnetWebFramework: "aspnet-blazor",
      dotnetOrm: "dapper",
      dotnetAuth: "duende-identityserver",
      dotnetApi: "graphql-hotchocolate",
      dotnetTesting: ["nunit", "moq", "testcontainers-dotnet"],
      dotnetJobQueue: "quartz-net",
      dotnetRealtime: "signalr",
      dotnetObservability: ["opentelemetry-dotnet", "nlog", "health-checks"],
      dotnetValidation: "fluentvalidation",
      dotnetCaching: "redis",
      dotnetDeploy: "docker",
    },
    strictMarkers: [
      { id: "dotnet:blazor", text: ["RazorComponents"] },
      { id: "orm:dapper", text: ["Dapper"] },
      { id: "auth:duende", text: ["Duende"] },
      { id: "api:hotchocolate", text: ["HotChocolate"] },
      { id: "testing:nunit", text: ["NUnit"] },
      { id: "testing:moq", text: ["Moq"] },
      { id: "testing:testcontainers", text: ["Testcontainers"] },
      { id: "jobs:quartz", text: ["Quartz"] },
      { id: "realtime:signalr", text: ["SignalR"] },
      { id: "validation:fluentvalidation", text: ["FluentValidation"] },
      { id: "observability:nlog", text: ["NLog"] },
      { id: "forbidden:hangfire", forbiddenText: ["Hangfire"] },
      { id: "forbidden:serilog", forbiddenText: ["Serilog"] },
    ],
    validationProfile: { native: ["dotnet"] },
  };

