import type { BenchmarkSpec } from "@/types";

export const ElixirBroadwayAbsintheSpec: BenchmarkSpec = {
    id: "elixir-broadway-absinthe",
    title: "Elixir Phoenix LiveView app with Absinthe, Broadway, Oban, and Nx",
    lane: "core",
    family: "elixir",
    supportedByBetterFullstack: true,
    requirements: [
      "Create an Elixir project using Phoenix LiveView (not plain Phoenix).",
      "Use Ecto SQL with PostgreSQL and Ecto changesets for validation.",
      "Use Guardian for auth (not phx.gen.auth or Ueberauth).",
      "Use Absinthe for a GraphQL API.",
      "Include Broadway and Nx as libraries.",
      "Use Phoenix Presence for realtime, Oban for jobs, Finch as the HTTP client, Jason for JSON, Swoosh for email, Nebulex for caching, and PromEx for observability.",
      "Use Wallaby for testing, Dialyxir for code quality, and Fly for deploy output.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build an Elixir Phoenix starter for a realtime data-ingestion app. It needs server-rendered live views, Postgres via Ecto, a dedicated JWT auth library, a GraphQL API, data pipelines, numerical/ML support, presence tracking, durable background jobs, a pooled HTTP client, caching, Prometheus metrics, browser-based tests, static analysis, and a deploy target. Pick the right BEAM libraries rather than the framework defaults.",
    rightLibraryNotes: [
      "Phoenix LiveView is required (not plain Phoenix).",
      "Guardian is required for auth; Absinthe is required for the GraphQL API.",
      "Broadway and Oban are required for pipelines and jobs.",
      "Presence, Finch, Nebulex, PromEx, Wallaby, and Dialyxir are the required choices.",
    ],
    canonicalFlags: [
      "--ecosystem", "elixir",
      "--database", "postgres",
      "--elixir-web-framework", "phoenix-live-view",
      "--elixir-orm", "ecto-sql",
      "--elixir-auth", "guardian",
      "--elixir-api", "absinthe",
      "--elixir-libraries", "broadway", "nx",
      "--elixir-realtime", "presence",
      "--elixir-jobs", "oban",
      "--elixir-validation", "ecto-changesets",
      "--elixir-http", "finch",
      "--elixir-json", "jason",
      "--elixir-email", "swoosh",
      "--elixir-caching", "nebulex",
      "--elixir-observability", "prom_ex",
      "--elixir-testing", "wallaby",
      "--elixir-quality", "dialyxir",
      "--elixir-deploy", "fly",
      "--auth", "none",
      "--email", "none",
      "--observability", "none",
      "--caching", "none",
      "--search", "none",
      "--ai-docs", "claude-md",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "elixir",
      database: "postgres",
      elixirWebFramework: "phoenix-live-view",
      elixirOrm: "ecto-sql",
      elixirAuth: "guardian",
      elixirApi: "absinthe",
      elixirLibraries: ["broadway", "nx"],
      elixirRealtime: "presence",
      elixirJobs: "oban",
      elixirValidation: "ecto-changesets",
      elixirHttp: "finch",
      elixirJson: "jason",
      elixirEmail: "swoosh",
      elixirCaching: "nebulex",
      elixirObservability: "prom_ex",
      elixirTesting: "wallaby",
      elixirQuality: "dialyxir",
      elixirDeploy: "fly",
    },
    strictMarkers: [
      { id: "web:phoenix-live-view", text: ["phoenix_live_view"] },
      { id: "orm:ecto-sql", text: ["ecto_sql"] },
      { id: "auth:guardian", text: [":guardian"] },
      { id: "api:absinthe", text: ["absinthe"] },
      { id: "lib:broadway", text: ["broadway"] },
      { id: "lib:nx", text: ["{:nx,"] },
      { id: "jobs:oban", text: [":oban"] },
      { id: "http:finch", text: [":finch"] },
      { id: "caching:nebulex", text: ["nebulex"] },
      { id: "observability:prom_ex", text: ["prom_ex"] },
      { id: "testing:wallaby", text: ["wallaby"] },
      { id: "quality:dialyxir", text: ["dialyxir"] },
      { id: "forbidden:credo", forbiddenText: [":credo"] },
    ],
    validationProfile: { native: ["elixir"] },
  };

