import type { BenchmarkSpec } from "@/types";

export const GoRealtimeApiSpec: BenchmarkSpec = {
    id: "go-realtime-api",
    title: "Go realtime API with Chi, Ent, gRPC, NATS, Redis, and OpenTelemetry",
    lane: "core",
    family: "go",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a Go API project using Chi, not Gin/Echo/Fiber.",
      "Use PostgreSQL with Ent.",
      "Use gRPC for typed service contracts.",
      "Use Cobra CLI tooling, Zap logging, JWT auth, Testify + GoMock tests, Gorilla WebSocket realtime, NATS messaging, Redis caching, Viper config, and OpenTelemetry.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a Go backend starter for a realtime admin API. It needs a lightweight router, Ent/Postgres models, typed gRPC service contracts, CLI/admin commands, structured logging, auth, websocket updates, event messaging, Redis cache, configuration, tracing, and test doubles.",
    rightLibraryNotes: [
      "Chi is required as the web framework.",
      "Ent is required for the data layer.",
      "gRPC-Go is required for typed service contracts.",
      "NATS and Gorilla WebSocket are required for messaging and realtime updates.",
    ],
    canonicalFlags: [
      "--ecosystem",
      "go",
      "--database",
      "postgres",
      "--go-web-framework",
      "chi",
      "--go-orm",
      "ent",
      "--go-api",
      "grpc-go",
      "--go-cli",
      "cobra",
      "--go-logging",
      "zap",
      "--go-auth",
      "jwt",
      "--go-testing",
      "testify",
      "gomock",
      "--go-realtime",
      "gorilla-websocket",
      "--go-message-queue",
      "nats",
      "--go-caching",
      "redis",
      "--go-config",
      "viper",
      "--go-observability",
      "opentelemetry",
      "--auth",
      "none",
      "--email",
      "none",
      "--observability",
      "none",
      "--caching",
      "none",
      "--search",
      "none",
      "--ai-docs",
      "none",
      "--no-install",
      "--no-git",
      "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "go",
      database: "postgres",
      goWebFramework: "chi",
      goOrm: "ent",
      goApi: "grpc-go",
      goCli: "cobra",
      goLogging: "zap",
      goAuth: "jwt",
      goTesting: ["testify", "gomock"],
      goRealtime: "gorilla-websocket",
      goMessageQueue: "nats",
      goCaching: "redis",
      goConfig: "viper",
      goObservability: "opentelemetry",
    },
    strictMarkers: [
      { id: "backend:chi", text: ["github.com/go-chi/chi"] },
      { id: "orm:ent", text: ["entgo.io/ent"], files: ["ent/schema/user.go"] },
      { id: "api:grpc-go", text: ["google.golang.org/grpc"] },
      { id: "cli:cobra", text: ["github.com/spf13/cobra"] },
      { id: "logging:zap", text: ["go.uber.org/zap"] },
      { id: "auth:jwt", text: ["github.com/golang-jwt/jwt"] },
      { id: "testing:testify+gomock", text: ["github.com/stretchr/testify", "go.uber.org/mock"] },
      { id: "realtime:gorilla-websocket", text: ["github.com/gorilla/websocket"] },
      { id: "queue:nats", text: ["github.com/nats-io/nats.go"] },
      { id: "caching:redis", text: ["github.com/redis/go-redis"] },
      { id: "config:viper", text: ["github.com/spf13/viper"] },
      { id: "observability:opentelemetry", text: ["go.opentelemetry.io/otel"] },
      { id: "forbidden:gin", forbiddenText: ["github.com/gin-gonic/gin"] },
    ],
    validationProfile: { native: ["go"] },
  };

