import type { BenchmarkSpec } from "@/types";

export const JavaSpringJooqKeycloakSpec: BenchmarkSpec = {
    id: "java-spring-jooq-keycloak",
    title: "Java Spring Boot API with jOOQ, Keycloak, GraphQL, and property/architecture tests",
    lane: "core",
    family: "java",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a Java project using Spring Boot with the Maven build tool.",
      "Use jOOQ for data access (NOT Spring Data JPA).",
      "Use Keycloak for auth (NOT Spring Security).",
      "Use Spring for GraphQL for the API and Logback for logging.",
      "Use PostgreSQL.",
      "Include MapStruct, Resilience4j, Spring for Kafka, Spring Batch, Micrometer Prometheus, Caffeine, springdoc-openapi, OpenTelemetry, Spring Validation, and Spring Actuator.",
      "Include JUnit 5, Mockito, Testcontainers, AssertJ, REST Assured, WireMock, Awaitility, ArchUnit, and jqwik for testing.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a Java Spring Boot starter for an event-driven service. It needs Postgres data access with a type-safe SQL layer, a dedicated identity server for auth, a GraphQL API, fault tolerance, event streaming, batch jobs, metrics, mapping, API docs, and tracing — plus a serious test stack with mocks, containers, HTTP stubs, architecture rules, and property-based tests. Choose the right Java libraries rather than the Spring defaults.",
    rightLibraryNotes: [
      "jOOQ is required for data access; Spring Data JPA is not used.",
      "Keycloak is required for auth; Spring Security is not the chosen provider.",
      "Spring for GraphQL is required for the API.",
      "ArchUnit and jqwik are required (architecture + property-based testing).",
    ],
    canonicalFlags: [
      "--ecosystem", "java",
      "--database", "postgres",
      "--java-web-framework", "spring-boot",
      "--java-build-tool", "maven",
      "--java-orm", "jooq",
      "--java-auth", "keycloak",
      "--java-api", "spring-graphql",
      "--java-logging", "logback",
      "--java-libraries",
      "mapstruct", "resilience4j", "spring-kafka", "spring-batch", "micrometer-prometheus",
      "caffeine", "springdoc-openapi", "opentelemetry-java", "spring-validation", "spring-actuator",
      "--java-testing-libraries",
      "junit5", "mockito", "testcontainers", "assertj", "rest-assured", "wiremock", "awaitility",
      "archunit", "jqwik",
      "--auth", "none",
      "--email", "none",
      "--observability", "none",
      "--caching", "none",
      "--search", "none",
      "--ai-docs", "claude-md",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "java",
      database: "postgres",
      javaWebFramework: "spring-boot",
      javaBuildTool: "maven",
      javaOrm: "jooq",
      javaAuth: "keycloak",
      javaApi: "spring-graphql",
      javaLogging: "logback",
      javaLibraries: [
        "mapstruct", "resilience4j", "spring-kafka", "spring-batch", "micrometer-prometheus",
        "caffeine", "springdoc-openapi", "opentelemetry-java", "spring-validation", "spring-actuator",
      ],
      javaTestingLibraries: [
        "junit5", "mockito", "testcontainers", "assertj", "rest-assured", "wiremock", "awaitility",
        "archunit", "jqwik",
      ],
    },
    strictMarkers: [
      { id: "backend:spring-boot", text: ["spring-boot-starter-parent"] },
      { id: "build:maven", files: ["pom.xml"] },
      { id: "orm:jooq", text: ["jooq"] },
      { id: "auth:keycloak", text: ["keycloak"] },
      { id: "api:spring-graphql", text: ["spring-boot-starter-graphql"] },
      { id: "lib:mapstruct", text: ["mapstruct"] },
      { id: "lib:resilience4j", text: ["resilience4j"] },
      { id: "lib:spring-kafka", text: ["spring-kafka"] },
      { id: "lib:spring-batch", text: ["spring-boot-starter-batch"] },
      { id: "lib:micrometer-prometheus", text: ["micrometer-registry-prometheus"] },
      { id: "testing:archunit", text: ["archunit"] },
      { id: "testing:jqwik", text: ["jqwik"] },
      { id: "testing:testcontainers", text: ["testcontainers"] },
      { id: "forbidden:jpa", forbiddenText: ["spring-boot-starter-data-jpa"] },
    ],
    validationProfile: { native: ["java"] },
  };

