import type { BenchmarkSpec } from "@scaffbench/types";

export const JavaSpringJooqKeycloakSpec: BenchmarkSpec = {
  id: "java-spring-jooq-keycloak",
  introducedAt: "2026-08-21",
  title: "Java Spring Boot API with jOOQ, Keycloak, GraphQL, and property/architecture tests",
  lane: "core",
  family: "java",
  supportedByBetterFullstack: true,
  requirements: [
    "Create a Java project using Spring Boot with the Maven build tool.",
    "Use jOOQ for data access (NOT Spring Data JPA).",
    "Use Keycloak as the identity provider. Do not hand-roll authentication and do not use Spring Security as the identity provider (no in-app user store, form login, or `UserDetailsService`); wiring Keycloak through Spring Security's OAuth2 resource server is the expected integration.",
    "Use Spring for GraphQL for the API and Logback for logging.",
    "Use PostgreSQL.",
    "Include MapStruct, Resilience4j, Spring for Kafka, Spring Batch, Micrometer Prometheus, Caffeine, springdoc-openapi, OpenTelemetry, Spring Validation, and Spring Actuator.",
    "Include JUnit 5, Mockito, Testcontainers, AssertJ, REST Assured, WireMock, Awaitility, ArchUnit, and jqwik for testing.",
  ],
  naturalPrompt:
    "Build a Java Spring Boot starter for an event-driven service. It needs Postgres data access with a type-safe SQL layer, a dedicated identity server for auth, a GraphQL API, fault tolerance, event streaming, batch jobs, metrics, mapping, API docs, and tracing, plus a serious test stack with mocks, containers, HTTP stubs, architecture rules, and property-based tests. Choose the right Java libraries rather than the Spring defaults.",
  rightLibraryNotes: [
    "jOOQ is required for data access; Spring Data JPA is not used.",
    "Keycloak is required as the identity provider; an in-app Spring Security user store or hand-rolled auth is a failure, while Spring Security's OAuth2 resource server is the expected way to validate Keycloak tokens.",
    "Spring for GraphQL is required for the API.",
    "ArchUnit and jqwik are required (architecture + property-based testing).",
  ],
  canonicalFlags: [
    "--ecosystem",
    "java",
    "--database",
    "postgres",
    "--java-web-framework",
    "spring-boot",
    "--java-build-tool",
    "maven",
    "--java-orm",
    "jooq",
    "--java-auth",
    "keycloak",
    "--java-api",
    "spring-graphql",
    "--java-logging",
    "logback",
    "--java-libraries",
    "mapstruct",
    "resilience4j",
    "spring-kafka",
    "spring-batch",
    "micrometer-prometheus",
    "caffeine",
    "springdoc-openapi",
    "opentelemetry-java",
    "spring-validation",
    "spring-actuator",
    "--java-testing-libraries",
    "junit5",
    "mockito",
    "testcontainers",
    "assertj",
    "rest-assured",
    "wiremock",
    "awaitility",
    "archunit",
    "jqwik",
    "--auth",
    "none",
    "--email",
    "none",
    "--observability",
    "none",
    "--caching",
    "none",
    "--search",
    "none",
    "--ai-docs",
    "claude-md",
    "--no-install",
    "--no-git",
    "--disable-analytics",
  ],
  expectedConfig: {
    ecosystem: "java",
    database: "postgres",
    javaWebFramework: "spring-boot",
    javaBuildTool: "maven",
    javaOrm: "jooq",
    javaAuth: "keycloak",
    javaApi: "spring-graphql",
    javaLogging: "logback",
    javaLibraries: [
      "mapstruct",
      "resilience4j",
      "spring-kafka",
      "spring-batch",
      "micrometer-prometheus",
      "caffeine",
      "springdoc-openapi",
      "opentelemetry-java",
      "spring-validation",
      "spring-actuator",
    ],
    javaTestingLibraries: [
      "junit5",
      "mockito",
      "testcontainers",
      "assertj",
      "rest-assured",
      "wiremock",
      "awaitility",
      "archunit",
      "jqwik",
    ],
  },
  strictMarkers: [
    { id: "backend:spring-boot", text: ["spring-boot-starter-parent"] },
    { id: "build:maven", files: ["pom.xml"] },
    { id: "orm:jooq", text: ["jooq"] },
    { id: "auth:keycloak", textAny: ["keycloak", "Keycloak", "KEYCLOAK"] },
    {
      id: "auth:oauth2-resource-server",
      textAny: ["oauth2-resource-server", "oauth2ResourceServer", "issuer-uri", "issuerUri"],
    },
    { id: "api:spring-graphql", text: ["spring-boot-starter-graphql"] },
    { id: "logging:logback", textAny: ["logback"] },
    { id: "lib:mapstruct", text: ["mapstruct"] },
    { id: "lib:resilience4j", text: ["resilience4j"] },
    { id: "lib:spring-kafka", text: ["spring-kafka"] },
    { id: "lib:spring-batch", text: ["spring-boot-starter-batch"] },
    { id: "lib:micrometer-prometheus", text: ["micrometer-registry-prometheus"] },
    { id: "lib:caffeine", textAny: ["caffeine"] },
    { id: "lib:springdoc-openapi", textAny: ["springdoc"] },
    { id: "lib:opentelemetry", textAny: ["opentelemetry"] },
    { id: "lib:spring-validation", textAny: ["spring-boot-starter-validation"] },
    { id: "lib:spring-actuator", textAny: ["spring-boot-starter-actuator"] },
    { id: "testing:junit5", textAny: ["junit-jupiter", "spring-boot-starter-test"] },
    { id: "testing:mockito", textAny: ["mockito"] },
    { id: "testing:assertj", textAny: ["assertj"] },
    { id: "testing:rest-assured", textAny: ["rest-assured", "restassured"] },
    { id: "testing:wiremock", textAny: ["wiremock", "WireMock"] },
    { id: "testing:awaitility", textAny: ["awaitility"] },
    { id: "testing:archunit", text: ["archunit"] },
    { id: "testing:jqwik", text: ["jqwik"] },
    { id: "testing:testcontainers", text: ["testcontainers"] },
    { id: "forbidden:jpa", forbiddenText: ["spring-boot-starter-data-jpa"] },
    {
      id: "forbidden:in-app-auth",
      forbiddenText: ["UserDetailsService", "formLogin", "InMemoryUserDetailsManager"],
    },
  ],
  validationProfile: { native: ["java"] },
};
