import type { BenchmarkSpec } from "../types";

export const MultiTsGoGrpcSpec: BenchmarkSpec = {
    id: "multi-ts-go-grpc",
    title: "Multi-ecosystem app: Nuxt (Vue) frontend with a Go Chi + gRPC backend",
    lane: "core",
    family: "multi-ecosystem",
    supportedByBetterFullstack: true,
    requirements: [
      "Create one multi-ecosystem project graph.",
      "Use a Nuxt (Vue) TypeScript frontend with Tailwind.",
      "Use a Go backend with the Chi router (not Gin/Echo/Fiber).",
      "Use sqlc for data access (not GORM or Ent).",
      "Use gRPC-Go for typed service contracts.",
      "Use goth for auth, Centrifuge for realtime, Watermill for messaging, Ristretto for caching, koanf for config, and zerolog for logging.",
      "Use OpenTelemetry and Testify + GoMock.",
      "Use PostgreSQL as the shared database.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a multi-ecosystem starter: a Vue/Nuxt web frontend and a Go backend. The Go side needs a lightweight router, type-safe SQL, typed gRPC contracts, social auth, scalable realtime, a messaging abstraction, an in-process cache, config management, structured logging, tracing, and test doubles. Use the project graph instead of one ecosystem.",
    rightLibraryNotes: [
      "The frontend must be TypeScript Nuxt (Vue).",
      "The Go backend must use Chi, sqlc, and gRPC-Go.",
      "Centrifuge and Watermill are required for realtime and messaging.",
      "Ristretto, koanf, and zerolog are required (not Redis, Viper, zap).",
    ],
    canonicalFlags: [
      "--part", "frontend:typescript:nuxt",
      "--part", "frontend.css:typescript:tailwind",
      "--part", "backend:go:chi",
      "--part", "backend.orm:go:sqlc",
      "--part", "backend.api:go:grpc-go",
      "--part", "backend.auth:go:goth",
      "--part", "backend.logging:go:zerolog",
      "--part", "backend.realtime:go:centrifuge",
      "--part", "backend.jobQueue:go:watermill",
      "--part", "backend.caching:go:ristretto",
      "--part", "backend.config:go:koanf",
      "--part", "backend.observability:go:opentelemetry",
      "--part", "backend.testing:go:testify",
      "--part", "backend.testing:go:gomock",
      "--part", "database:universal:postgres",
      "--addons", "turborepo",
      "--ai-docs", "none",
      "--package-manager", "bun",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedParts: [
      "frontend:typescript:nuxt",
      "frontend.css:typescript:tailwind",
      "backend:go:chi",
      "backend.orm:go:sqlc",
      "backend.api:go:grpc-go",
      "backend.auth:go:goth",
      "backend.logging:go:zerolog",
      "backend.realtime:go:centrifuge",
      "backend.jobQueue:go:watermill",
      "backend.caching:go:ristretto",
      "backend.config:go:koanf",
      "backend.observability:go:opentelemetry",
      "backend.testing:go:testify",
      "backend.testing:go:gomock",
      "database:universal:postgres",
    ],
    expectedAddons: ["turborepo"],
    strictMarkers: [
      { id: "frontend:nuxt", deps: ["nuxt"] },
      { id: "frontend:tailwind", deps: ["tailwindcss"] },
      { id: "backend:chi", text: ["github.com/go-chi/chi"] },
      { id: "orm:sqlc", files: ["apps/server/sqlc.yaml"] },
      { id: "api:grpc-go", text: ["google.golang.org/grpc"] },
      { id: "auth:goth", text: ["github.com/markbates/goth"] },
      { id: "realtime:centrifuge", text: ["github.com/centrifugal/centrifuge"] },
      { id: "queue:watermill", text: ["github.com/ThreeDotsLabs/watermill"] },
      { id: "caching:ristretto", text: ["github.com/dgraph-io/ristretto"] },
      { id: "config:koanf", text: ["github.com/knadh/koanf"] },
      { id: "logging:zerolog", text: ["github.com/rs/zerolog"] },
      { id: "observability:opentelemetry", text: ["go.opentelemetry.io/otel"] },
      { id: "testing:testify+gomock", text: ["github.com/stretchr/testify", "go.uber.org/mock"] },
      { id: "forbidden:gin", forbiddenText: ["github.com/gin-gonic/gin"] },
      { id: "forbidden:gorm", forbiddenText: ["gorm.io/gorm"] },
      { id: "forbidden:viper", forbiddenText: ["github.com/spf13/viper"] },
    ],
    validationProfile: { packageManager: "bun", native: ["go"] },
  };

