import type { BenchmarkSpec } from "@/types";

export const MultiDotnetOpsSpec: BenchmarkSpec = {
    id: "multi-dotnet-ops",
    introducedAt: "2026-08-21",
    title: "Multi-ecosystem ops portal with TypeScript frontend and .NET Minimal API backend",
    lane: "core",
    family: "multi-ecosystem",
    supportedByBetterFullstack: true,
    requirements: [
      "Create one multi-ecosystem project graph for an incident-ops portal: on-call engineers acknowledge incidents in the web UI, the backend fans out notifications.",
      "Use a Next.js TypeScript frontend with Tailwind and shadcn/ui.",
      "Use an ASP.NET Minimal API backend.",
      "Use EF Core, ASP.NET Identity, Minimal API endpoints, xUnit, Testcontainers for .NET, Serilog, SignalR for live incident updates, FluentValidation, Hangfire for notification fan-out, memory cache, and Docker output.",
      "Use PostgreSQL as the shared database.",
      "Include Turborepo, Biome, and GitHub Actions.",
    ],
    naturalPrompt:
      "Build a multi-ecosystem ops portal starter: a TypeScript web frontend and a .NET backend. It needs Postgres-backed identity, API endpoints, validation, background jobs, realtime notifications, observability/logging, tests, containers, and CI. Use the project graph instead of forcing everything into one ecosystem.",
    rightLibraryNotes: [
      "The frontend must be TypeScript Next.js.",
      "The backend must be ASP.NET Minimal API.",
      "EF Core and ASP.NET Identity are required.",
      "Hangfire and SignalR are required for jobs and realtime updates.",
    ],
    canonicalFlags: [
      "--part",
      "frontend:typescript:next",
      "--part",
      "frontend.css:typescript:tailwind",
      "--part",
      "frontend.ui:typescript:shadcn-ui",
      "--part",
      "backend:dotnet:aspnet-minimal",
      "--part",
      "backend.orm:dotnet:ef-core",
      "--part",
      "backend.auth:dotnet:aspnet-identity",
      "--part",
      "backend.api:dotnet:minimal-api",
      "--part",
      "backend.testing:dotnet:xunit",
      "--part",
      "backend.testing:dotnet:testcontainers-dotnet",
      "--part",
      "backend.observability:dotnet:serilog",
      "--part",
      "backend.realtime:dotnet:signalr",
      "--part",
      "backend.validation:dotnet:fluentvalidation",
      "--part",
      "backend.jobQueue:dotnet:hangfire",
      "--part",
      "backend.caching:dotnet:memory-cache",
      "--part",
      "backend.deploy:dotnet:docker",
      "--part",
      "database:universal:postgres",
      "--addons",
      "turborepo",
      "biome",
      "github-actions",
      "--ai-docs",
      "none",
      "--package-manager",
      "bun",
      "--shadcn-base",
      "radix",
      "--shadcn-style",
      "nova",
      "--shadcn-icon-library",
      "lucide",
      "--shadcn-color-theme",
      "neutral",
      "--shadcn-base-color",
      "neutral",
      "--shadcn-font",
      "inter",
      "--shadcn-radius",
      "default",
      "--no-install",
      "--no-git",
      "--disable-analytics",
    ],
    expectedParts: [
      "frontend:typescript:next",
      "frontend.css:typescript:tailwind",
      "frontend.ui:typescript:shadcn-ui",
      "backend:dotnet:aspnet-minimal",
      "backend.orm:dotnet:ef-core",
      "backend.auth:dotnet:aspnet-identity",
      "backend.api:dotnet:minimal-api",
      "backend.testing:dotnet:xunit",
      "backend.testing:dotnet:testcontainers-dotnet",
      "backend.observability:dotnet:serilog",
      "backend.realtime:dotnet:signalr",
      "backend.validation:dotnet:fluentvalidation",
      "backend.jobQueue:dotnet:hangfire",
      "backend.caching:dotnet:memory-cache",
      "backend.deploy:dotnet:docker",
      "database:universal:postgres",
    ],
    expectedAddons: ["turborepo", "biome", "github-actions"],
    strictMarkers: [
      { id: "frontend:next", deps: ["next"] },
      { id: "frontend:tailwind", deps: ["tailwindcss"] },
      { id: "frontend:shadcn", files: ["components.json"] },
      { id: "backend:aspnet-minimal", files: ["Program.cs"], text: ["MapGet"] },
      { id: "orm:ef-core", text: ["Microsoft.EntityFrameworkCore"] },
      { id: "db:postgres", textAny: ["Npgsql"] },
      { id: "auth:aspnet-identity", text: ["Microsoft.AspNetCore.Identity"] },
      { id: "testing:xunit", text: ["xunit"] },
      { id: "testing:testcontainers", text: ["Testcontainers"] },
      { id: "logging:serilog", text: ["Serilog"] },
      { id: "realtime:signalr", text: ["SignalR"] },
      { id: "validation:fluentvalidation", text: ["FluentValidation"] },
      { id: "jobs:hangfire", text: ["Hangfire"] },
      {
        id: "caching:memory-cache",
        textAny: ["IMemoryCache", "AddMemoryCache", "Microsoft.Extensions.Caching.Memory"],
      },
      { id: "deploy:docker", files: ["Dockerfile"] },
      { id: "addon:turborepo", deps: ["turbo"] },
      { id: "addon:biome", deps: ["@biomejs/biome"] },
      { id: "addon:github-actions", files: [".github/workflows/*.y*ml"] },
    ],
    validationProfile: {
      packageManager: "bun",
      native: ["dotnet"],
      qualityGate: true,
      doctorCheck: true,
    },
  };
