import type { BenchmarkSpec } from "@/types";

export const PythonIngestionApiSpec: BenchmarkSpec = {
    id: "python-ingestion-api",
    title: "Python FastAPI ingestion API with AI, queues, realtime, and quality gates",
    lane: "core",
    family: "python",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a Python API project using FastAPI.",
      "Use SQLModel for database models and Pydantic for validation.",
      "Use LangGraph and OpenAI SDK for AI workflows.",
      "Use JWT auth, Celery task queues, WebSockets realtime, Redis caching, OpenTelemetry, Typer, Rich, Ruff, Pytest, and Hypothesis.",
      "Do not choose Django REST Framework or Django Ninja because this is not a Django project.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a Python ingestion API starter for AI document processing. It needs FastAPI, SQL-backed models, strict validation, AI workflow libraries, queued workers, realtime job updates, Redis cache, tracing, CLI tools, and real test/quality tooling. Avoid Django-only API libraries.",
    rightLibraryNotes: [
      "FastAPI is required; Django-specific API packages are forbidden.",
      "SQLModel is required for the database layer.",
      "LangGraph plus OpenAI SDK are required for AI workflow scaffolding.",
      "Celery is required for background ingestion jobs.",
    ],
    canonicalFlags: [
      "--ecosystem",
      "python",
      "--database",
      "postgres",
      "--python-web-framework",
      "fastapi",
      "--python-orm",
      "sqlmodel",
      "--python-validation",
      "pydantic",
      "--python-ai",
      "langgraph",
      "openai-sdk",
      "--python-auth",
      "jwt",
      "--python-api",
      "none",
      "--python-task-queue",
      "celery",
      "--python-graphql",
      "none",
      "--python-quality",
      "ruff",
      "--python-testing",
      "pytest",
      "hypothesis",
      "--python-caching",
      "redis",
      "--python-realtime",
      "websockets",
      "--python-observability",
      "opentelemetry",
      "--python-cli",
      "typer",
      "rich",
      "--email",
      "none",
      "--observability",
      "none",
      "--caching",
      "none",
      "--search",
      "none",
      "--ai-docs",
      "none",
      "--no-install",
      "--no-git",
      "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "python",
      database: "postgres",
      pythonWebFramework: "fastapi",
      pythonOrm: "sqlmodel",
      pythonValidation: "pydantic",
      pythonAi: ["langgraph", "openai-sdk"],
      pythonAuth: "jwt",
      pythonApi: "none",
      pythonTaskQueue: "celery",
      pythonQuality: "ruff",
      pythonTesting: ["pytest", "hypothesis"],
      pythonCaching: "redis",
      pythonRealtime: "websockets",
      pythonObservability: "opentelemetry",
      pythonCli: ["typer", "rich"],
    },
    strictMarkers: [
      { id: "backend:fastapi", text: ["fastapi"] },
      { id: "orm:sqlmodel", text: ["sqlmodel"] },
      { id: "validation:pydantic", text: ["pydantic"] },
      { id: "ai:langgraph", text: ["langgraph"] },
      { id: "ai:openai-sdk", text: ["openai"] },
      { id: "auth:jwt", text: ["jwt"] },
      { id: "jobs:celery", text: ["celery"] },
      { id: "quality:ruff", text: ["ruff"] },
      { id: "testing:pytest", text: ["pytest"] },
      { id: "testing:hypothesis", text: ["hypothesis"] },
      { id: "realtime:websockets", text: ["websockets"] },
      { id: "cli:typer+rich", text: ["typer", "rich"] },
      { id: "forbidden:django-api", forbiddenText: ["django-rest-framework", "django-ninja"] },
    ],
    validationProfile: { native: ["python"] },
  };

