import type { BenchmarkSpec } from "@scaffbench/types";

export const ReactNativeExpoSpec: BenchmarkSpec = {
  id: "react-native-expo",
  introducedAt: "2026-08-21",
  title: "React Native Expo habit tracker with Expo Router, Uniwind, MMKV, and Maestro + RNTL",
  lane: "core",
  difficulty: 2,
  family: "react-native",
  supportedByBetterFullstack: true,
  requirements: [
    "Create a React Native (Expo) habit-tracker app: a habit list, a detail screen, and a settings screen, all working offline.",
    "Use Expo Router for navigation.",
    "Use Uniwind for Tailwind-style styling. NativeWind is the familiar answer and the wrong one here, do not add it.",
    "Use MMKV for on-device storage; all habit data lives on the device.",
    "Use Maestro plus React Native Testing Library for testing.",
    "Use Expo Notifications for habit reminders, Expo Updates for OTA, and Expo Linking for deep linking into a habit's detail screen.",
    "This is a mobile-only project: no backend, database, sync service, or auth.",
  ],
  naturalPrompt:
    "Build a React Native habit tracker on Expo that works fully offline: a habit list, detail and settings screens, local reminders, deep links into a habit, and over-the-air updates. It needs file-based navigation, Tailwind-style styling, fast on-device key-value storage, and both end-to-end and unit testing. It is a standalone mobile app with no server, database, or accounts.",
  rightLibraryNotes: [
    "Expo Router is required for navigation.",
    "Uniwind is the required styling approach (native-uniwind frontend); NativeWind is a failure.",
    "MMKV is required for storage; Maestro + RNTL for testing.",
    "Expo Notifications / Updates / Linking are the required push / OTA / deep-linking choices.",
  ],
  canonicalFlags: [
    "--ecosystem",
    "react-native",
    "--frontend",
    "native-uniwind",
    "--auth",
    "none",
    "--mobile-navigation",
    "expo-router",
    "--mobile-ui",
    "uniwind",
    "--mobile-storage",
    "mmkv",
    "--mobile-testing",
    "maestro-react-native-testing-library",
    "--mobile-push",
    "expo-notifications",
    "--mobile-ota",
    "expo-updates",
    "--mobile-deep-linking",
    "expo-linking",
    "--ai-docs",
    "claude-md",
    "--package-manager",
    "bun",
    "--no-install",
    "--no-git",
    "--disable-analytics",
  ],
  expectedConfig: {
    ecosystem: "react-native",
    frontend: ["native-uniwind"],
    mobileNavigation: "expo-router",
    mobileUI: "uniwind",
    mobileStorage: "mmkv",
    mobileTesting: "maestro-react-native-testing-library",
    mobilePush: "expo-notifications",
    mobileOTA: "expo-updates",
    mobileDeepLinking: "expo-linking",
  },
  strictMarkers: [
    { id: "nav:expo-router", deps: ["expo-router"] },
    { id: "styling:uniwind", deps: ["uniwind"] },
    { id: "storage:mmkv", deps: ["react-native-mmkv"] },
    { id: "push:expo-notifications", deps: ["expo-notifications"] },
    { id: "ota:expo-updates", deps: ["expo-updates"] },
    { id: "deep-linking:expo-linking", deps: ["expo-linking"] },
    { id: "testing:rntl", deps: ["@testing-library/react-native"] },
    { id: "testing:maestro", files: [".maestro/*.y*ml"] },
    { id: "forbidden:nativewind", forbiddenDeps: ["nativewind"] },
    {
      id: "forbidden:backend",
      forbiddenDeps: ["express", "hono", "fastify", "elysia", "@nestjs/core", "convex"],
    },
    {
      id: "forbidden:database",
      forbiddenDeps: [
        "drizzle-orm",
        "@prisma/client",
        "@supabase/supabase-js",
        "firebase",
        "@react-native-firebase/app",
      ],
    },
    {
      id: "forbidden:sync",
      forbiddenDeps: [
        "@powersync/react-native",
        "@instantdb/react-native",
        "replicache",
        "@rocicorp/zero",
        "@nozbe/watermelondb",
      ],
    },
    {
      id: "forbidden:auth",
      forbiddenDeps: [
        "better-auth",
        "@clerk/clerk-expo",
        "expo-auth-session",
        "@react-native-google-signin/google-signin",
      ],
    },
  ],
  validationProfile: { packageManager: "bun" },
};
