import type { BenchmarkSpec } from "@/types";

export const ReactNativeExpoSpec: BenchmarkSpec = {
    id: "react-native-expo",
    title: "React Native Expo app with Expo Router, Uniwind, MMKV, and Maestro + RNTL",
    lane: "core",
    family: "react-native",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a React Native (Expo) mobile app.",
      "Use Expo Router for navigation and Uniwind (Tailwind-style) styling.",
      "Use MMKV for on-device storage.",
      "Use Maestro plus React Native Testing Library for testing.",
      "Use Expo Notifications for push, Expo Updates for OTA, and Expo Linking for deep linking.",
      "This is a mobile-only project: no backend, database, or auth.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a React Native mobile starter on Expo. It needs file-based navigation, Tailwind-style styling, fast on-device key-value storage, push notifications, over-the-air updates, deep linking, and both end-to-end and unit testing. It is a standalone mobile app with no server, database, or accounts.",
    rightLibraryNotes: [
      "Expo Router is required for navigation.",
      "Uniwind is the required styling approach (native-uniwind frontend).",
      "MMKV is required for storage; Maestro + RNTL for testing.",
      "Expo Notifications / Updates / Linking are the required push / OTA / deep-linking choices.",
    ],
    canonicalFlags: [
      "--ecosystem", "react-native",
      "--frontend", "native-uniwind",
      "--auth", "none",
      "--mobile-navigation", "expo-router",
      "--mobile-ui", "uniwind",
      "--mobile-storage", "mmkv",
      "--mobile-testing", "maestro-react-native-testing-library",
      "--mobile-push", "expo-notifications",
      "--mobile-ota", "expo-updates",
      "--mobile-deep-linking", "expo-linking",
      "--ai-docs", "claude-md",
      "--package-manager", "bun",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "react-native",
      frontend: ["native-uniwind"],
      mobileNavigation: "expo-router",
      mobileUI: "uniwind",
      mobileStorage: "mmkv",
      mobileTesting: "maestro-react-native-testing-library",
      mobilePush: "expo-notifications",
      mobileOTA: "expo-updates",
      mobileDeepLinking: "expo-linking",
    },
    strictMarkers: [
      { id: "nav:expo-router", deps: ["expo-router"] },
      { id: "styling:uniwind", deps: ["uniwind"] },
      { id: "storage:mmkv", deps: ["react-native-mmkv"] },
      { id: "push:expo-notifications", deps: ["expo-notifications"] },
      { id: "ota:expo-updates", deps: ["expo-updates"] },
      { id: "deep-linking:expo-linking", deps: ["expo-linking"] },
      { id: "testing:rntl", deps: ["@testing-library/react-native"] },
      { id: "testing:maestro", files: ["apps/native/.maestro/home.yaml"] },
    ],
    validationProfile: { packageManager: "bun" },
  };

