import type { BenchmarkSpec } from "../types";

export const RustLeptosAxumSpec: BenchmarkSpec = {
    id: "rust-leptos-axum",
    title: "Rust Axum API with a Leptos WASM frontend and typed service libraries",
    lane: "core",
    family: "rust",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a Rust project with Axum as the backend web framework.",
      "Use Leptos specifically for the WASM frontend; do not replace it with Dioxus or React.",
      "Use PostgreSQL with SQLx.",
      "Use Tonic for a typed API boundary.",
      "Include Clap CLI support, tracing, anyhow/thiserror, Moka caching, OAuth2 auth, Lapin jobs, OpenTelemetry, and Askama templates.",
      "Include serde, uuid, chrono, reqwest, config, utoipa, validator, and tokio-test libraries.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a Rust starter for an internal product console. It should have an Axum server, a Rust WASM frontend, Postgres access, typed service/API boundaries, CLI/admin utilities, tracing, auth, cache, jobs, and template rendering. Choose the right Rust libraries rather than swapping in web defaults.",
    rightLibraryNotes: [
      "Leptos is required for the Rust WASM frontend.",
      "Axum is required for the server.",
      "SQLx is required for database access.",
      "Tonic is required for typed RPC/API contracts.",
    ],
    canonicalFlags: [
      "--ecosystem",
      "rust",
      "--database",
      "postgres",
      "--rust-web-framework",
      "axum",
      "--rust-frontend",
      "leptos",
      "--rust-orm",
      "sqlx",
      "--rust-api",
      "tonic",
      "--rust-cli",
      "clap",
      "--rust-libraries",
      "serde",
      "uuid",
      "chrono",
      "reqwest",
      "config",
      "utoipa",
      "validator",
      "tokio-test",
      "--rust-logging",
      "tracing",
      "--rust-error-handling",
      "anyhow-thiserror",
      "--rust-caching",
      "moka",
      "--rust-auth",
      "oauth2",
      "--rust-realtime",
      "none",
      "--rust-message-queue",
      "lapin",
      "--rust-observability",
      "opentelemetry",
      "--rust-templating",
      "askama",
      "--email",
      "none",
      "--observability",
      "none",
      "--caching",
      "none",
      "--search",
      "none",
      "--ai-docs",
      "none",
      "--no-install",
      "--no-git",
      "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "rust",
      database: "postgres",
      rustWebFramework: "axum",
      rustFrontend: "leptos",
      rustOrm: "sqlx",
      rustApi: "tonic",
      rustCli: "clap",
      rustLibraries: [
        "serde",
        "uuid",
        "chrono",
        "reqwest",
        "config",
        "utoipa",
        "validator",
        "tokio-test",
      ],
      rustLogging: "tracing",
      rustErrorHandling: "anyhow-thiserror",
      rustCaching: "moka",
      rustAuth: "oauth2",
      rustMessageQueue: "lapin",
      rustObservability: "opentelemetry",
      rustTemplating: "askama",
    },
    strictMarkers: [
      { id: "rust:axum", text: ["axum"] },
      {
        id: "frontend:leptos",
        text: ["leptos", "leptos_router"],
        files: ["crates/client/Cargo.toml"],
      },
      { id: "orm:sqlx", text: ["sqlx"] },
      { id: "api:tonic", text: ["tonic"] },
      { id: "cli:clap", text: ["clap"] },
      { id: "logging:tracing", text: ["tracing"] },
      { id: "cache:moka", text: ["moka"] },
      { id: "auth:oauth2", text: ["oauth2"] },
      { id: "jobs:lapin", text: ["lapin"] },
      { id: "observability:opentelemetry", text: ["opentelemetry"] },
      { id: "templating:askama", text: ["askama"] },
      { id: "forbidden:dioxus", forbiddenText: ["dioxus-router", "Dioxus.toml"] },
    ],
    validationProfile: { native: ["cargo"] },
  };

