import type { BenchmarkSpec } from "@/types";

export const TsMinimalRestraintSpec: BenchmarkSpec = {
    id: "ts-minimal-restraint",
    title: "Minimal React + Tailwind SPA with no backend, data, or auth (restraint test)",
    lane: "extended",
    family: "typescript",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a minimal TypeScript React single-page app built with Vite and Tailwind.",
      "It is a static marketing/landing page only.",
      "Do NOT add a backend, database, ORM, API layer, auth, payments, email, file storage, jobs, CMS, or analytics.",
      "Include Turborepo tooling.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build a small static marketing landing page as a React single-page app with Tailwind. It has no accounts, no database, and no server — just a clean front end. Keep it lean and do not add backend or data tooling.",
    rightLibraryNotes: [
      "This is a frontend-only starter: do not add a backend, database, ORM, API, auth, payments, or email.",
    ],
    canonicalFlags: [
      "--ecosystem", "typescript",
      "--frontend", "react-vite",
      "--backend", "none",
      "--runtime", "none",
      "--api", "none",
      "--database", "none",
      "--orm", "none",
      "--db-setup", "none",
      "--auth", "none",
      "--payments", "none",
      "--email", "none",
      "--file-upload", "none",
      "--logging", "none",
      "--observability", "none",
      "--feature-flags", "none",
      "--analytics", "none",
      "--effect", "none",
      "--state-management", "none",
      "--forms", "none",
      "--validation", "none",
      "--testing", "none",
      "--ai", "none",
      "--realtime", "none",
      "--job-queue", "none",
      "--animation", "none",
      "--css-framework", "tailwind",
      "--ui-library", "none",
      "--cms", "none",
      "--caching", "none",
      "--rate-limit", "none",
      "--i18n", "none",
      "--search", "none",
      "--vector-db", "none",
      "--file-storage", "none",
      "--web-deploy", "none",
      "--server-deploy", "none",
      "--addons", "turborepo",
      "--examples", "none",
      "--ai-docs", "none",
      "--package-manager", "bun",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "typescript",
      frontend: ["react-vite"],
      backend: "none",
      database: "none",
      orm: "none",
      api: "none",
      auth: "none",
      cssFramework: "tailwind",
    },
    expectedAddons: ["turborepo"],
    strictMarkers: [
      { id: "frontend:react-vite", deps: ["react", "vite"] },
      { id: "css:tailwind", deps: ["tailwindcss"] },
      {
        id: "forbidden:backend",
        forbiddenDeps: ["hono", "express", "fastify", "elysia", "@nestjs/core"],
      },
      {
        id: "forbidden:database",
        forbiddenDeps: ["drizzle-orm", "@prisma/client", "kysely", "typeorm", "mongoose"],
      },
      {
        id: "forbidden:auth",
        forbiddenDeps: ["better-auth", "lucia", "next-auth", "@clerk/clerk-react"],
      },
      { id: "forbidden:payments", forbiddenDeps: ["stripe", "@stripe/stripe-js", "polar-sh"] },
      { id: "forbidden:email", forbiddenDeps: ["resend", "nodemailer", "@react-email/components"] },
      { id: "forbidden:api", forbiddenDeps: ["@orpc/server", "@trpc/server", "graphql"] },
    ],
    validationProfile: { packageManager: "bun" },
  };

