import type { BenchmarkSpec } from "@scaffbench/types";

export const TsMinimalRestraintSpec: BenchmarkSpec = {
  id: "ts-minimal-restraint",
  introducedAt: "2026-08-21",
  title: "Minimal React + Tailwind SPA with no backend, data, or auth (restraint test)",
  lane: "extended",
  family: "typescript",
  supportedByBetterFullstack: true,
  requirements: [
    "Create a minimal TypeScript React single-page app built with Vite and Tailwind.",
    "It is the launch page for a developer tool: hero, feature grid, pricing table, and a waitlist email form.",
    "The waitlist form POSTs to an external form endpoint read from an env var, you do NOT build the endpoint.",
    "Pricing is three static tiers, no checkout, no billing provider.",
    "Do NOT add a backend, database, ORM, API layer, auth, payments, email, file storage, jobs, CMS, or analytics. Every one of those is tempting here; adding any of them is a failure.",
    "Include Turborepo tooling.",
  ],
  naturalPrompt:
    "Build the launch page for a developer tool as a React single-page app with Tailwind: hero, feature grid, static three-tier pricing, and a waitlist email form that posts to an external form service configured by env var. There are no accounts, no database, and no server of your own, keep it a lean front end and resist adding backend or data tooling.",
  rightLibraryNotes: [
    "This is a frontend-only starter: do not add a backend, database, ORM, API, auth, payments, or email.",
    "The pricing table and waitlist form are bait, they need no billing provider and no server.",
  ],
  canonicalFlags: [
    "--ecosystem",
    "typescript",
    "--frontend",
    "react-vite",
    "--backend",
    "none",
    "--runtime",
    "none",
    "--api",
    "none",
    "--database",
    "none",
    "--orm",
    "none",
    "--db-setup",
    "none",
    "--auth",
    "none",
    "--payments",
    "none",
    "--email",
    "none",
    "--file-upload",
    "none",
    "--logging",
    "none",
    "--observability",
    "none",
    "--feature-flags",
    "none",
    "--analytics",
    "none",
    "--effect",
    "none",
    "--state-management",
    "none",
    "--forms",
    "none",
    "--validation",
    "none",
    "--testing",
    "none",
    "--ai",
    "none",
    "--realtime",
    "none",
    "--job-queue",
    "none",
    "--animation",
    "none",
    "--css-framework",
    "tailwind",
    "--ui-library",
    "none",
    "--cms",
    "none",
    "--caching",
    "none",
    "--rate-limit",
    "none",
    "--i18n",
    "none",
    "--search",
    "none",
    "--vector-db",
    "none",
    "--file-storage",
    "none",
    "--web-deploy",
    "none",
    "--server-deploy",
    "none",
    "--addons",
    "turborepo",
    "--examples",
    "none",
    "--ai-docs",
    "none",
    "--package-manager",
    "bun",
    "--no-install",
    "--no-git",
    "--disable-analytics",
  ],
  expectedConfig: {
    ecosystem: "typescript",
    frontend: ["react-vite"],
    backend: "none",
    database: "none",
    orm: "none",
    api: "none",
    auth: "none",
    cssFramework: "tailwind",
  },
  expectedAddons: ["turborepo"],
  strictMarkers: [
    { id: "frontend:react-vite", deps: ["react", "vite"] },
    { id: "css:tailwind", deps: ["tailwindcss"] },
    { id: "tooling:turborepo", explicitOnly: true, deps: ["turbo"] },
    {
      id: "forbidden:backend",
      forbiddenDeps: ["hono", "express", "fastify", "elysia", "@nestjs/core"],
    },
    {
      id: "forbidden:database",
      forbiddenDeps: ["drizzle-orm", "@prisma/client", "kysely", "typeorm", "mongoose"],
    },
    {
      id: "forbidden:auth",
      forbiddenDeps: ["better-auth", "lucia", "next-auth", "@clerk/clerk-react"],
    },
    { id: "forbidden:payments", forbiddenDeps: ["stripe", "@stripe/stripe-js", "polar-sh"] },
    { id: "forbidden:email", forbiddenDeps: ["resend", "nodemailer", "@react-email/components"] },
    { id: "forbidden:api", forbiddenDeps: ["@orpc/server", "@trpc/server", "graphql"] },
    {
      id: "forbidden:jobs",
      forbiddenDeps: [
        "inngest",
        "bullmq",
        "@trigger.dev/sdk",
        "pg-boss",
        "graphile-worker",
        "@temporalio/",
      ],
    },
    {
      id: "forbidden:cms",
      forbiddenDeps: [
        "@sanity/client",
        "sanity",
        "next-sanity",
        "contentful",
        "payload",
        "@payloadcms/",
        "@keystone-6/core",
        "@strapi/strapi",
        "@strapi/client",
        "@directus/sdk",
        "@keystatic/",
        "tinacms",
      ],
    },
    {
      id: "forbidden:analytics",
      forbiddenDeps: [
        "posthog-js",
        "@vercel/analytics",
        "@segment/analytics-next",
        "plausible-tracker",
        "mixpanel-browser",
      ],
      forbiddenText: ["googletagmanager", "gtag(", "umami"],
    },
    {
      id: "forbidden:file-storage",
      forbiddenDeps: [
        "@aws-sdk/client-s3",
        "uploadthing",
        "@uploadthing/react",
        "cloudinary",
        "@supabase/storage-js",
      ],
    },
  ],
  validationProfile: { packageManager: "bun" },
};
