import type { BenchmarkSpec } from "@/types";

export const TsSvelteEdgeOrpcSpec: BenchmarkSpec = {
    id: "ts-svelte-edge-orpc",
    title: "SvelteKit edge app on Cloudflare Workers with Hono + oRPC and D1",
    lane: "core",
    family: "typescript",
    supportedByBetterFullstack: true,
    requirements: [
      "Create a TypeScript monorepo for an edge-deployed app.",
      "Use a SvelteKit web frontend styled with Tailwind.",
      "Use a Hono backend running on the Cloudflare Workers runtime.",
      "Use oRPC for the app API (tRPC is not compatible with a Svelte frontend).",
      "Use SQLite via Cloudflare D1 with Drizzle as the ORM.",
      "Use Better Auth for accounts and Valibot for validation.",
      "Deploy both the web app and the server to Cloudflare.",
      "Do not add payments, email, realtime, search, vector DB, jobs, CMS, file storage/upload, analytics, or i18n.",
      "Do not install dependencies, do not initialize git, and do not start a dev server.",
    ],
    naturalPrompt:
      "Build an edge-first starter that runs on Cloudflare. It needs a Svelte web app, a lightweight server on the Workers runtime, a type-safe app API, an edge SQL database with a typed ORM, account auth, and validation. Pick libraries that actually run on Workers and deploy to Cloudflare.",
    rightLibraryNotes: [
      "oRPC is required for the API because tRPC does not support a Svelte frontend.",
      "The Workers runtime requires the Hono backend.",
      "Cloudflare D1 is required for the SQLite database, and Cloudflare for deploys.",
      "Better Auth must use a Workers-compatible ORM (Drizzle).",
    ],
    canonicalFlags: [
      "--ecosystem", "typescript",
      "--frontend", "svelte",
      "--backend", "hono",
      "--runtime", "workers",
      "--api", "orpc",
      "--database", "sqlite",
      "--orm", "drizzle",
      "--db-setup", "d1",
      "--auth", "better-auth",
      "--validation", "valibot",
      "--css-framework", "tailwind",
      "--ui-library", "none",
      "--web-deploy", "cloudflare",
      "--server-deploy", "cloudflare",
      "--payments", "none",
      "--email", "none",
      "--file-upload", "none",
      "--file-storage", "none",
      "--logging", "none",
      "--observability", "none",
      "--feature-flags", "none",
      "--analytics", "none",
      "--effect", "none",
      "--state-management", "none",
      "--forms", "none",
      "--testing", "none",
      "--ai", "none",
      "--realtime", "none",
      "--job-queue", "none",
      "--animation", "none",
      "--cms", "none",
      "--caching", "none",
      "--rate-limit", "none",
      "--i18n", "none",
      "--search", "none",
      "--vector-db", "none",
      "--addons", "turborepo",
      "--examples", "none",
      "--ai-docs", "none",
      "--package-manager", "bun",
      "--no-install", "--no-git", "--disable-analytics",
    ],
    expectedConfig: {
      ecosystem: "typescript",
      frontend: ["svelte"],
      backend: "hono",
      runtime: "workers",
      api: "orpc",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "d1",
      auth: "better-auth",
      validation: "valibot",
      cssFramework: "tailwind",
      webDeploy: "cloudflare",
      serverDeploy: "cloudflare",
    },
    expectedAddons: ["turborepo"],
    strictMarkers: [
      { id: "frontend:svelte", deps: ["@sveltejs/kit"] },
      { id: "backend:hono", deps: ["hono"] },
      { id: "api:orpc", deps: ["@orpc/server"], source: ["@orpc/"] },
      { id: "runtime:workers", deps: ["wrangler"] },
      { id: "orm:drizzle", deps: ["drizzle-orm"], source: ["drizzle-orm"] },
      { id: "auth:better-auth", deps: ["better-auth"], source: ["better-auth"] },
      { id: "validation:valibot", deps: ["valibot"] },
      { id: "css:tailwind", deps: ["tailwindcss"] },
      { id: "forbidden:trpc", forbiddenDeps: ["@trpc/server", "@trpc/client"] },
      { id: "forbidden:next", forbiddenDeps: ["next"] },
    ],
    validationProfile: { packageManager: "bun" },
  };

