// Generated from registry popularity (npm, crates.io, PyPI, NuGet and Hex downloads; GitHub stars
// for Go, Java and hosted tools), September 2026. Opt-outs stay last. Categories with no fair
// metric keep their source order and are left out.
export const OPTION_DISPLAY_ORDER: Readonly<Record<string, readonly string[]>> = {
  ai: [
    "anthropic-sdk",
    "openai-sdk",
    "vercel-ai",
    "langgraph",
    "langchain",
    "openai-agents",
    "mastra",
    "tanstack-ai",
    "google-adk",
    "llamaindex",
    "voltagent",
    "modelfusion",
    "ai-cli",
    "none",
  ],
  analytics: ["posthog", "vercel-analytics", "ga4", "plausible", "umami", "none"],
  animation: ["framer-motion", "lottie", "react-spring", "gsap", "auto-animate", "none"],
  api: ["trpc", "apollo-server", "graphql-yoga", "orpc", "openapi", "ts-rest", "garph", "none"],
  apiGateway: ["kong", "none"],
  appShells: ["electron", "pwa", "capacitor", "tauri", "opentui", "wxt"],
  astroIntegration: ["react", "vue", "solid", "svelte", "none"],
  auth: [
    "supabase-auth",
    "passport",
    "better-auth",
    "better-auth-organizations",
    "nextauth",
    "workos",
    "auth0",
    "clerk",
    "stack-auth",
    "go-better-auth",
    "kinde",
    "none",
  ],
  backend: [
    "express",
    "hono",
    "effect",
    "nestjs",
    "fastify",
    "nitro",
    "convex",
    "elysia",
    "adonisjs",
    "fets",
    "encore",
    "self-next",
    "self-tanstack-start",
    "self-astro",
    "self-svelte",
    "self-nuxt",
    "self-vinext",
    "self-solid-start",
    "none",
  ],
  botProtection: ["turnstile", "botid", "none"],
  caching: ["redis", "upstash-redis", "none"],
  cms: ["contentful", "sanity", "payload", "strapi", "directus", "keystatic", "tinacms", "none"],
  codeGeneration: ["openapi-typescript", "graphql-codegen"],
  containerOrchestration: ["docker-compose", "none"],
  cssFramework: ["tailwind", "scss", "styled-components", "less", "postcss-only", "none"],
  dataClient: ["tanstack-query", "swr", "apollo-client", "none"],
  database: ["postgres", "redis", "mysql", "mongodb", "sqlite", "edgedb", "none"],
  documentation: ["fumadocs", "starlight"],
  dotnetApi: ["minimal-api", "grpc-dotnet", "graphql-hotchocolate", "none"],
  dotnetCaching: ["memory-cache", "redis", "none"],
  dotnetDeploy: ["docker", "aws", "azure", "none"],
  dotnetJobQueue: ["hosted-services", "quartz-net", "hangfire", "none"],
  dotnetLibraries: [
    "polly",
    "automapper",
    "application-insights",
    "mediatr",
    "mongodb-driver",
    "scrutor",
    "masstransit",
    "refit",
    "prometheus-net",
    "seq",
    "api-versioning",
    "nhibernate",
    "rebus",
    "mapster",
    "sentry",
    "scalar",
    "fastendpoints",
    "fluent-email",
    "coravel",
    "magic-onion",
    "none",
  ],
  dotnetObservability: ["serilog", "nlog", "opentelemetry-dotnet", "health-checks", "none"],
  dotnetTesting: ["moq", "xunit", "nunit", "testcontainers-dotnet", "none"],
  dotnetValidation: ["data-annotations", "fluentvalidation", "none"],
  elixirApi: ["rest", "open_api_spex", "absinthe", "grpc", "none"],
  elixirAuth: ["phx-gen-auth", "guardian", "ueberauth", "pow", "none"],
  elixirCaching: ["redix", "cachex", "nebulex", "none"],
  elixirDeploy: ["mix-release", "docker", "fly", "gigalixir", "none"],
  elixirHttp: ["finch", "req", "tesla", "none"],
  elixirHttpServer: ["cowboy", "bandit", "none"],
  elixirLibraries: ["ex_aws", "floki", "rustler", "broadway", "nx", "none"],
  elixirObservability: ["telemetry", "opentelemetry", "sentry", "prom_ex", "none"],
  elixirOrm: ["ecto", "ecto-sql", "myxql", "ecto_sqlite3", "none"],
  elixirQuality: ["credo", "dialyxir", "excoveralls", "sobelow", "mix_audit", "none"],
  elixirTesting: ["ex_unit", "ex_machina", "wallaby", "mox", "bypass", "stream_data", "none"],
  elixirValidation: ["nimble-options", "ecto-changesets", "none"],
  email: [
    "nodemailer",
    "resend",
    "react-email",
    "sendgrid",
    "aws-ses",
    "mailgun",
    "postmark",
    "plunk",
    "none",
  ],
  featureFlags: ["posthog", "launchdarkly", "growthbook", "unleash", "flagsmith", "none"],
  fileStorage: ["s3", "r2", "supabase-storage", "cloudinary", "none"],
  fileUpload: ["uppy", "filepond", "uploadthing", "none"],
  forms: [
    "react-hook-form",
    "formik",
    "tanstack-form",
    "final-form",
    "conform",
    "modular-forms",
    "none",
  ],
  frontendUtilities: [
    "tanstack-virtual",
    "tanstack-table",
    "firebase",
    "tanstack-pacer",
    "tanstack-db",
  ],
  gitHooks: ["husky", "lefthook", "none"],
  goApi: ["grpc-go", "grpc-gateway", "gqlgen", "oapi-codegen", "connect-go", "none"],
  goCli: ["bubbletea", "cobra", "urfave-cli", "none"],
  goLogging: ["logrus", "zap", "zerolog", "slog", "none"],
  goMessageQueue: ["asynq", "watermill", "kafka-go", "nats", "none"],
  goObservability: ["signoz", "opentelemetry", "prometheus", "none"],
  goOrm: ["gorm", "sqlc", "sqlx", "ent", "bun", "none"],
  goTesting: ["testify", "ginkgo-gomega", "mockery", "testcontainers", "gomock", "none"],
  goWebFramework: [
    "gin",
    "fiber",
    "go-zero",
    "echo",
    "kratos",
    "chi",
    "httprouter",
    "stdlib",
    "none",
  ],
  httpClientTool: ["axios", "none"],
  i18n: ["i18next", "next-intl", "paraglide", "intlayer", "none"],
  javaApi: ["openapi-generator", "grpc", "spring-graphql", "none"],
  javaAuth: ["keycloak", "spring-security", "none"],
  javaBuildTool: ["gradle", "maven", "none"],
  javaLibraries: [
    "spring-actuator",
    "spring-devtools",
    "spring-validation",
    "spring-webflux",
    "spring-mail",
    "spring-websocket",
    "spring-rsocket",
    "spring-restclient",
    "caffeine",
    "lombok",
    "resilience4j",
    "flyway",
    "spring-oauth2-client",
    "spring-saml2",
    "mapstruct",
    "spring-quartz",
    "liquibase",
    "micrometer-prometheus",
    "springdoc-openapi",
    "thymeleaf",
    "spring-data-elasticsearch",
    "spring-batch",
    "spring-kafka",
    "opentelemetry-java",
    "spring-session-redis",
    "spring-session-jdbc",
    "spring-data-redis",
    "spring-data-mongodb",
    "spring-integration",
    "spring-hateoas",
    "spring-data-rest",
    "spring-data-neo4j",
    "spring-amqp",
    "spring-data-jdbc",
    "spring-data-cassandra",
    "spring-ldap",
    "spring-data-couchbase",
    "spring-pulsar",
    "none",
  ],
  javaLogging: ["log4j2", "logback", "none"],
  javaOrm: ["mybatis", "jooq", "spring-data-jpa", "none"],
  javaTestingLibraries: [
    "mockito",
    "testcontainers",
    "wiremock",
    "rest-assured",
    "junit5",
    "awaitility",
    "archunit",
    "assertj",
    "jqwik",
    "none",
  ],
  javaWebFramework: ["spring-boot", "quarkus", "ktor", "micronaut", "none"],
  jobQueue: ["bullmq", "temporal", "inngest", "trigger-dev", "none"],
  kotlinMobileLibraries: [
    "ktor-client",
    "coil",
    "koin",
    "junit5",
    "navigation-compose",
    "datastore",
    "kotlinx-serialization-json",
    "mockk",
    "voyager",
    "turbine",
    "none",
  ],
  mobileLibraries: [
    "expo-file-system",
    "expo-image",
    "expo-image-picker",
    "expo-clipboard",
    "expo-location",
    "expo-sharing",
    "expo-camera",
    "expo-audio",
    "expo-video",
    "expo-local-authentication",
    "expo-sqlite",
    "expo-task-manager",
    "expo-contacts",
    "expo-calendar",
    "expo-sensors",
    "expo-screen-capture",
    "expo-battery",
    "expo-background-task",
    "expo-brightness",
    "expo-maps",
    "none",
  ],
  mobileNavigation: ["react-navigation", "expo-router", "none"],
  mobileTesting: [
    "maestro",
    "maestro-react-native-testing-library",
    "react-native-testing-library",
    "none",
  ],
  mobileUI: ["uniwind", "unistyles", "tamagui", "gluestack-ui", "none"],
  observability: [
    "opentelemetry",
    "sentry",
    "datadog",
    "grafana",
    "axiom",
    "betterstack",
    "signoz",
    "none",
  ],
  orm: ["drizzle", "kysely", "prisma", "mongoose", "typeorm", "sequelize", "mikroorm", "none"],
  payments: [
    "stripe",
    "revenuecat",
    "polar",
    "paddle",
    "lemon-squeezy",
    "dodo",
    "paypal",
    "creem",
    "xendit",
    "commet",
    "autumn",
    "none",
  ],
  pythonAi: [
    "openai-sdk",
    "mcp",
    "scikit-learn",
    "langchain",
    "anthropic-sdk",
    "transformers",
    "pytorch",
    "langgraph",
    "tensorflow",
    "google-adk",
    "pydantic-ai",
    "llamaindex",
    "haystack",
    "smolagents",
    "crewai",
    "none",
  ],
  pythonAuth: ["pyjwt", "authlib", "jwt", "fastapi-users", "none"],
  pythonCli: ["click", "rich", "typer", "none"],
  pythonObservability: ["signoz", "prometheus-client", "opentelemetry", "none"],
  pythonOrm: ["sqlalchemy", "pymongo", "peewee", "sqlmodel", "tortoise-orm", "none"],
  pythonRealtime: ["websockets", "python-socketio", "none"],
  pythonTaskQueue: ["celery", "huey", "rq", "taskiq", "dramatiq", "none"],
  pythonTesting: ["pytest", "pytest-cov", "hypothesis", "none"],
  // Starlette ships inside FastAPI and aiohttp is mostly installed as an HTTP client.
  pythonWebFramework: [
    "fastapi",
    "flask",
    "django",
    "streamlit",
    "litestar",
    "starlette",
    "aiohttp",
    "none",
  ],
  rateLimit: ["upstash-ratelimit", "arcjet", "none"],
  realtime: ["ws", "socket-io", "yjs", "ably", "pusher", "liveblocks", "partykit", "none"],
  runtime: ["node", "bun", "workers", "none"],
  rustApi: ["tonic", "jsonrpsee", "async-graphql", "none"],
  rustAuth: ["oauth2", "openidconnect", "tower-sessions", "torii", "none"],
  rustLibraries: [
    "rand",
    "itertools",
    "serde",
    "regex",
    "parking-lot",
    "reqwest",
    "uuid",
    "chrono",
    "tokio-util",
    "rayon",
    "dashmap",
    "jsonwebtoken",
    "proptest",
    "secrecy",
    "mockall",
    "insta",
    "rstest",
    "argon2",
    "config",
    "tokio-test",
    "utoipa",
    "validator",
    "cargo-audit",
    "cargo-nextest",
    "none",
  ],
  rustMessageQueue: ["rdkafka", "async-nats", "lapin", "none"],
  rustOrm: ["sqlx", "rusqlite", "tokio-postgres", "diesel", "sea-orm", "mongodb", "none"],
  rustTemplating: ["askama", "minijinja", "tera", "none"],
  rustWebFramework: ["axum", "actix-web", "warp", "rocket", "salvo", "poem", "loco", "none"],
  search: ["elasticsearch", "meilisearch", "typesense", "opensearch", "bleve", "algolia", "none"],
  shadcnIconLibrary: [
    "lucide",
    "react-icons",
    "heroicons",
    "phosphor",
    "tabler",
    "hugeicons",
    "remixicon",
  ],
  stateManagement: [
    "zustand",
    "redux-toolkit",
    "tanstack-store",
    "nanostores",
    "jotai",
    "xstate",
    "mobx",
    "valtio",
    "legend-state",
    "none",
  ],
  staticAnalysis: ["gitleaks", "knip"],
  testing: ["vitest", "vitest-playwright", "playwright", "jest", "mocha", "cypress", "none"],
  testingTools: ["storybook", "msw"],
  uiLibrary: [
    "radix-ui",
    "base-ui",
    "mui",
    "shadcn-ui",
    "react-aria",
    "headless-ui",
    "antd",
    "mantine",
    "chakra-ui",
    "ark-ui",
    "daisyui",
    "shadcn-svelte",
    "nextui",
    "park-ui",
    "none",
  ],
  validation: [
    "zod",
    "typebox",
    "effect-schema",
    "valibot",
    "arktype",
    "typia",
    "runtypes",
    "none",
  ],
  webFrontend: [
    "react-vite",
    "next",
    "react-router",
    "tanstack-router",
    "tanstack-start",
    "vue",
    "angular",
    "astro",
    "solid",
    "solid-start",
    "svelte",
    "nuxt",
    "vinext",
    "qwik",
    "redwood",
    "vanilla-vite",
    "fresh",
    "none",
  ],
  workspaceRunner: ["turborepo", "nx", "none"],
};
