// AUTO-GENERATED by scripts/generate-cli-flags-data.ts — DO NOT EDIT.
// Source of truth: @better-fullstack/types (CLI_FLAG_GROUP_DEFINITIONS).
// Regenerate with: bun run docs:cli-flags

export type CliFlagRow = {
  flag: string;
  summary: string;
  values: string[];
  valueHint: string | null;
  defaultValue: string | null;
  multiple: boolean;
};

export type CliFlagGroup = {
  id: string;
  title: string;
  description: string;
  flags: CliFlagRow[];
};

export const CLI_FLAG_GROUPS: CliFlagGroup[] = [
  {
    "id": "common",
    "title": "Common flags",
    "description": "Flags that apply to every ecosystem and control workflow behavior.",
    "flags": [
      {
        "flag": "--ecosystem",
        "summary": "Language/runtime ecosystem to scaffold.",
        "values": [
          "typescript",
          "react-native",
          "rust",
          "python",
          "go",
          "java",
          "elixir",
          "dotnet"
        ],
        "valueHint": null,
        "defaultValue": "typescript",
        "multiple": false
      },
      {
        "flag": "--template",
        "summary": "Start from a curated stack preset instead of individual flags.",
        "values": [
          "mern",
          "pern",
          "t3",
          "saas",
          "uniwind",
          "none"
        ],
        "valueHint": null,
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--part",
        "summary": "Add a multi-ecosystem stack part. Repeat once per part.",
        "values": [],
        "valueHint": "role:ecosystem:tool (e.g. frontend:typescript:next)",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--addons",
        "summary": "Repo tooling and platform addons.",
        "values": [
          "pwa",
          "tauri",
          "electron",
          "capacitor",
          "wxt",
          "opentui",
          "turborepo",
          "nx",
          "mcp",
          "skills",
          "msw",
          "storybook",
          "swr",
          "tanstack-query",
          "tanstack-table",
          "tanstack-virtual",
          "tanstack-db",
          "tanstack-pacer",
          "backend-utils",
          "devcontainer",
          "docker-compose",
          "github-actions",
          "axios",
          "firebase",
          "graphql-codegen",
          "openapi-typescript",
          "apollo-client",
          "biome",
          "eslint",
          "prettier",
          "oxlint",
          "ultracite",
          "lefthook",
          "husky",
          "ruler",
          "starlight",
          "fumadocs",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "turborepo",
        "multiple": true
      },
      {
        "flag": "--examples",
        "summary": "Optional example features to include.",
        "values": [
          "ai",
          "chat-sdk",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--ai-docs",
        "summary": "Agent instruction files to generate.",
        "values": [
          "claude-md",
          "agents-md",
          "cursorrules",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "claude-md agents-md",
        "multiple": true
      },
      {
        "flag": "--package-manager",
        "summary": "Package manager for the generated workspace.",
        "values": [
          "npm",
          "pnpm",
          "bun",
          "yarn"
        ],
        "valueHint": null,
        "defaultValue": "bun",
        "multiple": false
      },
      {
        "flag": "--workspace-shape",
        "summary": "Monorepo or single-app workspace layout.",
        "values": [
          "monorepo",
          "single-app"
        ],
        "valueHint": null,
        "defaultValue": "monorepo",
        "multiple": false
      },
      {
        "flag": "--version-channel",
        "summary": "Dependency version channel.",
        "values": [
          "stable",
          "latest",
          "beta"
        ],
        "valueHint": null,
        "defaultValue": "stable",
        "multiple": false
      },
      {
        "flag": "--web-deploy",
        "summary": "Deployment target config for the web app.",
        "values": [
          "cloudflare",
          "fly",
          "railway",
          "render",
          "netlify",
          "docker",
          "sst",
          "vercel",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--server-deploy",
        "summary": "Deployment target config for the server.",
        "values": [
          "cloudflare",
          "fly",
          "railway",
          "render",
          "netlify",
          "docker",
          "sst",
          "vercel",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--directory-conflict",
        "summary": "Strategy when the target directory already exists.",
        "values": [
          "merge",
          "overwrite",
          "increment",
          "error"
        ],
        "valueHint": null,
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--install",
        "summary": "Install dependencies after scaffolding.",
        "values": [],
        "valueHint": "--install / --no-install",
        "defaultValue": "--install",
        "multiple": false
      },
      {
        "flag": "--git",
        "summary": "Initialize a Git repository.",
        "values": [],
        "valueHint": "--git / --no-git",
        "defaultValue": "--git",
        "multiple": false
      },
      {
        "flag": "--dry-run",
        "summary": "Preview generated files without writing them.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--verify",
        "summary": "Run generated checks after scaffolding where supported.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--yes",
        "summary": "Accept defaults. Conflicts with core stack flags.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--yolo",
        "summary": "Skip safety confirmations where supported.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--verbose",
        "summary": "Print detailed scaffold output.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--disable-analytics",
        "summary": "Opt out of anonymous CLI analytics.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      }
    ]
  },
  {
    "id": "typescript-stack",
    "title": "TypeScript stack",
    "description": "Core stack flags for `--ecosystem typescript`.",
    "flags": [
      {
        "flag": "--frontend",
        "summary": "Web frontend framework(s).",
        "values": [
          "tanstack-router",
          "react-router",
          "react-vite",
          "vanilla-vite",
          "vue",
          "tanstack-start",
          "next",
          "vinext",
          "nuxt",
          "svelte",
          "solid",
          "solid-start",
          "astro",
          "qwik",
          "angular",
          "redwood",
          "fresh",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "tanstack-router",
        "multiple": true
      },
      {
        "flag": "--backend",
        "summary": "Backend framework. `self` pairs with fullstack frontends.",
        "values": [
          "hono",
          "express",
          "fastify",
          "elysia",
          "fets",
          "effect",
          "nestjs",
          "adonisjs",
          "nitro",
          "encore",
          "convex",
          "self",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "hono",
        "multiple": false
      },
      {
        "flag": "--runtime",
        "summary": "Server runtime.",
        "values": [
          "bun",
          "node",
          "workers",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "bun",
        "multiple": false
      },
      {
        "flag": "--database",
        "summary": "Database engine.",
        "values": [
          "none",
          "sqlite",
          "postgres",
          "mysql",
          "mongodb",
          "edgedb",
          "redis"
        ],
        "valueHint": null,
        "defaultValue": "sqlite",
        "multiple": false
      },
      {
        "flag": "--orm",
        "summary": "ORM / query layer.",
        "values": [
          "drizzle",
          "prisma",
          "mongoose",
          "typeorm",
          "kysely",
          "mikroorm",
          "sequelize",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "drizzle",
        "multiple": false
      },
      {
        "flag": "--db-setup",
        "summary": "Hosted database provider setup.",
        "values": [
          "turso",
          "neon",
          "prisma-postgres",
          "planetscale",
          "mongodb-atlas",
          "supabase",
          "upstash",
          "d1",
          "docker",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--auth",
        "summary": "Authentication provider.",
        "values": [
          "better-auth",
          "better-auth-organizations",
          "go-better-auth",
          "clerk",
          "nextauth",
          "stack-auth",
          "supabase-auth",
          "auth0",
          "workos",
          "kinde",
          "passport",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "better-auth",
        "multiple": false
      },
      {
        "flag": "--api",
        "summary": "API layer. tRPC is React-oriented.",
        "values": [
          "trpc",
          "orpc",
          "ts-rest",
          "garph",
          "graphql-yoga",
          "apollo-server",
          "openapi",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "trpc",
        "multiple": false
      },
      {
        "flag": "--astro-integration",
        "summary": "Astro UI framework integration (Astro frontends).",
        "values": [
          "react",
          "vue",
          "svelte",
          "solid",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--manual-db",
        "summary": "Skip provider-specific database setup prompts.",
        "values": [],
        "valueHint": "boolean flag",
        "defaultValue": null,
        "multiple": false
      }
    ]
  },
  {
    "id": "typescript-services",
    "title": "TypeScript services",
    "description": "Optional service integrations for TypeScript stacks.",
    "flags": [
      {
        "flag": "--ai",
        "summary": "AI SDK / agent framework.",
        "values": [
          "vercel-ai",
          "mastra",
          "voltagent",
          "langgraph",
          "openai-agents",
          "openai-sdk",
          "anthropic-sdk",
          "google-adk",
          "modelfusion",
          "langchain",
          "llamaindex",
          "tanstack-ai",
          "ai-cli",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--payments",
        "summary": "Payments provider.",
        "values": [
          "revenuecat",
          "polar",
          "stripe",
          "lemon-squeezy",
          "paddle",
          "paypal",
          "dodo",
          "creem",
          "autumn",
          "commet",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--email",
        "summary": "Email provider.",
        "values": [
          "react-email",
          "resend",
          "nodemailer",
          "postmark",
          "sendgrid",
          "aws-ses",
          "mailgun",
          "plunk",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--realtime",
        "summary": "Realtime transport.",
        "values": [
          "socket-io",
          "ws",
          "partykit",
          "ably",
          "pusher",
          "liveblocks",
          "yjs",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--job-queue",
        "summary": "Background job / queue system.",
        "values": [
          "bullmq",
          "trigger-dev",
          "inngest",
          "temporal",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--cms",
        "summary": "Content management system.",
        "values": [
          "payload",
          "sanity",
          "strapi",
          "tinacms",
          "directus",
          "keystatic",
          "contentful",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--caching",
        "summary": "Cache layer.",
        "values": [
          "upstash-redis",
          "redis",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--search",
        "summary": "Search engine.",
        "values": [
          "meilisearch",
          "typesense",
          "elasticsearch",
          "opensearch",
          "algolia",
          "bleve",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--file-storage",
        "summary": "Object storage provider.",
        "values": [
          "s3",
          "r2",
          "cloudinary",
          "supabase-storage",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--file-upload",
        "summary": "File upload helper.",
        "values": [
          "uploadthing",
          "filepond",
          "uppy",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--analytics",
        "summary": "Web analytics provider.",
        "values": [
          "plausible",
          "umami",
          "posthog",
          "ga4",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--feature-flags",
        "summary": "Feature flag platform.",
        "values": [
          "growthbook",
          "posthog",
          "launchdarkly",
          "flagsmith",
          "unleash",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--ecommerce",
        "summary": "E-commerce platform SDK.",
        "values": [
          "medusa",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--vector-db",
        "summary": "Vector database.",
        "values": [
          "pgvector",
          "qdrant",
          "chroma",
          "pinecone",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rate-limit",
        "summary": "Rate limiting helper.",
        "values": [
          "arcjet",
          "upstash-ratelimit",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--i18n",
        "summary": "Internationalization library.",
        "values": [
          "paraglide",
          "i18next",
          "next-intl",
          "intlayer",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--effect",
        "summary": "Effect capability level.",
        "values": [
          "effect",
          "effect-full",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--logging",
        "summary": "Logging library.",
        "values": [
          "pino",
          "winston",
          "evlog",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--observability",
        "summary": "Observability provider.",
        "values": [
          "opentelemetry",
          "sentry",
          "grafana",
          "datadog",
          "axiom",
          "betterstack",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      }
    ]
  },
  {
    "id": "typescript-ui",
    "title": "TypeScript UI and app behavior",
    "description": "Frontend styling, state, forms, validation, and testing flags.",
    "flags": [
      {
        "flag": "--css-framework",
        "summary": "CSS framework.",
        "values": [
          "tailwind",
          "scss",
          "less",
          "postcss-only",
          "styled-components",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "tailwind",
        "multiple": false
      },
      {
        "flag": "--ui-library",
        "summary": "Component library.",
        "values": [
          "shadcn-ui",
          "shadcn-svelte",
          "daisyui",
          "radix-ui",
          "headless-ui",
          "park-ui",
          "chakra-ui",
          "nextui",
          "mantine",
          "mui",
          "antd",
          "base-ui",
          "ark-ui",
          "react-aria",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "shadcn-ui",
        "multiple": false
      },
      {
        "flag": "--state-management",
        "summary": "Client state manager.",
        "values": [
          "zustand",
          "jotai",
          "nanostores",
          "redux-toolkit",
          "mobx",
          "xstate",
          "valtio",
          "tanstack-store",
          "legend-state",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--forms",
        "summary": "Form library.",
        "values": [
          "tanstack-form",
          "react-hook-form",
          "formik",
          "final-form",
          "conform",
          "modular-forms",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "react-hook-form",
        "multiple": false
      },
      {
        "flag": "--validation",
        "summary": "Schema validation library.",
        "values": [
          "zod",
          "valibot",
          "arktype",
          "typebox",
          "typia",
          "runtypes",
          "effect-schema",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "zod",
        "multiple": false
      },
      {
        "flag": "--testing",
        "summary": "Testing setup.",
        "values": [
          "vitest",
          "playwright",
          "vitest-playwright",
          "jest",
          "mocha",
          "cypress",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "vitest",
        "multiple": false
      },
      {
        "flag": "--animation",
        "summary": "Animation library.",
        "values": [
          "framer-motion",
          "gsap",
          "react-spring",
          "auto-animate",
          "lottie",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      }
    ]
  },
  {
    "id": "shadcn",
    "title": "shadcn/ui flags",
    "description": "Only apply when `--ui-library shadcn-ui` is selected.",
    "flags": [
      {
        "flag": "--shadcn-base",
        "summary": "shadcn primitive base.",
        "values": [
          "radix",
          "base"
        ],
        "valueHint": null,
        "defaultValue": "radix",
        "multiple": false
      },
      {
        "flag": "--shadcn-style",
        "summary": "shadcn style preset.",
        "values": [
          "vega",
          "nova",
          "maia",
          "lyra",
          "mira",
          "luma",
          "sera"
        ],
        "valueHint": null,
        "defaultValue": "nova",
        "multiple": false
      },
      {
        "flag": "--shadcn-icon-library",
        "summary": "Icon library.",
        "values": [
          "lucide",
          "tabler",
          "hugeicons",
          "phosphor",
          "remixicon",
          "heroicons",
          "react-icons"
        ],
        "valueHint": null,
        "defaultValue": "lucide",
        "multiple": false
      },
      {
        "flag": "--shadcn-color-theme",
        "summary": "Color theme.",
        "values": [
          "neutral",
          "stone",
          "zinc",
          "gray",
          "amber",
          "blue",
          "cyan",
          "emerald",
          "fuchsia",
          "green",
          "indigo",
          "lime",
          "orange",
          "pink",
          "purple",
          "red",
          "rose",
          "sky",
          "teal",
          "violet",
          "yellow"
        ],
        "valueHint": null,
        "defaultValue": "neutral",
        "multiple": false
      },
      {
        "flag": "--shadcn-base-color",
        "summary": "Base neutral color.",
        "values": [
          "neutral",
          "stone",
          "zinc",
          "gray"
        ],
        "valueHint": null,
        "defaultValue": "neutral",
        "multiple": false
      },
      {
        "flag": "--shadcn-font",
        "summary": "Default font.",
        "values": [
          "inter",
          "geist",
          "noto-sans",
          "nunito-sans",
          "figtree",
          "roboto",
          "raleway",
          "dm-sans",
          "public-sans",
          "outfit",
          "jetbrains-mono",
          "geist-mono"
        ],
        "valueHint": null,
        "defaultValue": "inter",
        "multiple": false
      },
      {
        "flag": "--shadcn-radius",
        "summary": "Corner radius scale.",
        "values": [
          "default",
          "none",
          "small",
          "medium",
          "large"
        ],
        "valueHint": null,
        "defaultValue": "default",
        "multiple": false
      }
    ]
  },
  {
    "id": "react-native",
    "title": "React Native flags",
    "description": "Flags for `--ecosystem react-native`.",
    "flags": [
      {
        "flag": "--frontend",
        "summary": "Expo native frontend styling.",
        "values": [
          "native-bare",
          "native-uniwind",
          "native-unistyles",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "native-bare",
        "multiple": true
      },
      {
        "flag": "--mobile-navigation",
        "summary": "Navigation library.",
        "values": [
          "expo-router",
          "react-navigation",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-ui",
        "summary": "Mobile UI kit.",
        "values": [
          "tamagui",
          "gluestack-ui",
          "uniwind",
          "unistyles",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-storage",
        "summary": "On-device storage.",
        "values": [
          "mmkv",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-testing",
        "summary": "Mobile testing setup.",
        "values": [
          "maestro",
          "react-native-testing-library",
          "maestro-react-native-testing-library",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-push",
        "summary": "Push notifications.",
        "values": [
          "expo-notifications",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-ota",
        "summary": "Over-the-air updates.",
        "values": [
          "expo-updates",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-deep-linking",
        "summary": "Deep linking.",
        "values": [
          "expo-linking",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--mobile-libraries",
        "summary": "Optional Expo modules.",
        "values": [
          "expo-sqlite",
          "expo-camera",
          "expo-image-picker",
          "expo-location",
          "expo-sensors",
          "expo-file-system",
          "expo-image",
          "expo-audio",
          "expo-video",
          "expo-contacts",
          "expo-calendar",
          "expo-local-authentication",
          "expo-sharing",
          "expo-clipboard",
          "expo-task-manager",
          "expo-background-task",
          "expo-maps",
          "expo-brightness",
          "expo-battery",
          "expo-screen-capture",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      }
    ]
  },
  {
    "id": "rust",
    "title": "Rust flags",
    "description": "Flags for `--ecosystem rust`.",
    "flags": [
      {
        "flag": "--rust-web-framework",
        "summary": "Rust web framework.",
        "values": [
          "axum",
          "actix-web",
          "rocket",
          "poem",
          "loco",
          "warp",
          "salvo",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-frontend",
        "summary": "WASM frontend.",
        "values": [
          "leptos",
          "dioxus",
          "yew",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-orm",
        "summary": "Rust ORM / database.",
        "values": [
          "sea-orm",
          "sqlx",
          "diesel",
          "mongodb",
          "rusqlite",
          "tokio-postgres",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-api",
        "summary": "Rust API layer.",
        "values": [
          "tonic",
          "async-graphql",
          "jsonrpsee",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-cli",
        "summary": "Rust CLI tooling.",
        "values": [
          "clap",
          "ratatui",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-libraries",
        "summary": "Rust core libraries.",
        "values": [
          "serde",
          "uuid",
          "chrono",
          "reqwest",
          "config",
          "dashmap",
          "parking-lot",
          "secrecy",
          "tokio-util",
          "utoipa",
          "validator",
          "jsonwebtoken",
          "argon2",
          "tokio-test",
          "mockall",
          "proptest",
          "insta",
          "rand",
          "regex",
          "rayon",
          "itertools",
          "rstest",
          "cargo-nextest",
          "cargo-audit",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--rust-logging",
        "summary": "Rust logging.",
        "values": [
          "tracing",
          "env-logger",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "tracing",
        "multiple": false
      },
      {
        "flag": "--rust-error-handling",
        "summary": "Rust error handling.",
        "values": [
          "anyhow-thiserror",
          "eyre",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "anyhow-thiserror",
        "multiple": false
      },
      {
        "flag": "--rust-caching",
        "summary": "Rust caching.",
        "values": [
          "moka",
          "redis",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-auth",
        "summary": "Rust auth.",
        "values": [
          "oauth2",
          "torii",
          "openidconnect",
          "tower-sessions",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-realtime",
        "summary": "Rust realtime.",
        "values": [
          "tokio-tungstenite",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-message-queue",
        "summary": "Rust message queue.",
        "values": [
          "lapin",
          "rdkafka",
          "async-nats",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-observability",
        "summary": "Rust observability.",
        "values": [
          "opentelemetry",
          "metrics",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--rust-templating",
        "summary": "Rust templating.",
        "values": [
          "askama",
          "tera",
          "minijinja",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      }
    ]
  },
  {
    "id": "python",
    "title": "Python flags",
    "description": "Flags for `--ecosystem python`.",
    "flags": [
      {
        "flag": "--python-web-framework",
        "summary": "Python web framework.",
        "values": [
          "fastapi",
          "django",
          "flask",
          "litestar",
          "starlette",
          "aiohttp",
          "streamlit",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "fastapi",
        "multiple": false
      },
      {
        "flag": "--python-orm",
        "summary": "Python ORM / database.",
        "values": [
          "sqlalchemy",
          "sqlmodel",
          "tortoise-orm",
          "peewee",
          "pymongo",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "sqlalchemy",
        "multiple": false
      },
      {
        "flag": "--python-validation",
        "summary": "Validation library.",
        "values": [
          "pydantic",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "pydantic",
        "multiple": false
      },
      {
        "flag": "--python-ai",
        "summary": "Python AI / ML libraries.",
        "values": [
          "langchain",
          "llamaindex",
          "openai-sdk",
          "anthropic-sdk",
          "langgraph",
          "crewai",
          "haystack",
          "pydantic-ai",
          "google-adk",
          "smolagents",
          "pytorch",
          "transformers",
          "scikit-learn",
          "tensorflow",
          "mcp",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--python-auth",
        "summary": "Python auth.",
        "values": [
          "authlib",
          "jwt",
          "pyjwt",
          "fastapi-users",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-api",
        "summary": "Python API framework.",
        "values": [
          "django-rest-framework",
          "django-ninja",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-task-queue",
        "summary": "Python task queue.",
        "values": [
          "celery",
          "rq",
          "dramatiq",
          "huey",
          "taskiq",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-graphql",
        "summary": "Python GraphQL.",
        "values": [
          "strawberry",
          "ariadne",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-quality",
        "summary": "Python code quality tool.",
        "values": [
          "ruff",
          "mypy",
          "pyright",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "ruff",
        "multiple": false
      },
      {
        "flag": "--python-testing",
        "summary": "Python testing libraries.",
        "values": [
          "pytest",
          "hypothesis",
          "pytest-cov",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--python-caching",
        "summary": "Python caching.",
        "values": [
          "redis",
          "aiocache",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-realtime",
        "summary": "Python realtime.",
        "values": [
          "python-socketio",
          "websockets",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-observability",
        "summary": "Python observability.",
        "values": [
          "opentelemetry",
          "prometheus-client",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-cli",
        "summary": "Python CLI tooling.",
        "values": [
          "typer",
          "click",
          "rich",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--python-cloud-sdk",
        "summary": "Python cloud SDK.",
        "values": [
          "boto3",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-http-client",
        "summary": "Python HTTP client.",
        "values": [
          "requests",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-data",
        "summary": "Python data and scientific libraries.",
        "values": [
          "numpy",
          "pandas",
          "scipy",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--python-media",
        "summary": "Python media library.",
        "values": [
          "pillow",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-server",
        "summary": "Python production server.",
        "values": [
          "gunicorn",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--python-package-manager",
        "summary": "Python package manager.",
        "values": [
          "uv",
          "poetry",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "uv",
        "multiple": false
      },
      {
        "flag": "--python-message-queue",
        "summary": "Python message queue client.",
        "values": [
          "confluent-kafka",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      }
    ]
  },
  {
    "id": "go",
    "title": "Go flags",
    "description": "Flags for `--ecosystem go`. Global `--auth` also applies.",
    "flags": [
      {
        "flag": "--go-web-framework",
        "summary": "Go web framework.",
        "values": [
          "gin",
          "echo",
          "fiber",
          "chi",
          "stdlib",
          "go-zero",
          "kratos",
          "httprouter",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "gin",
        "multiple": false
      },
      {
        "flag": "--go-orm",
        "summary": "Go ORM / database.",
        "values": [
          "gorm",
          "sqlc",
          "ent",
          "bun",
          "sqlx",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "gorm",
        "multiple": false
      },
      {
        "flag": "--go-api",
        "summary": "Go API layer.",
        "values": [
          "grpc-go",
          "gqlgen",
          "grpc-gateway",
          "connect-go",
          "oapi-codegen",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-cli",
        "summary": "Go CLI tooling.",
        "values": [
          "cobra",
          "bubbletea",
          "urfave-cli",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-logging",
        "summary": "Go logging.",
        "values": [
          "zap",
          "zerolog",
          "slog",
          "logrus",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "zap",
        "multiple": false
      },
      {
        "flag": "--go-auth",
        "summary": "Go-native auth helpers.",
        "values": [
          "casbin",
          "jwt",
          "goth",
          "oauth2",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-testing",
        "summary": "Go testing libraries.",
        "values": [
          "testify",
          "gomock",
          "testcontainers",
          "ginkgo-gomega",
          "mockery",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--go-realtime",
        "summary": "Go realtime.",
        "values": [
          "gorilla-websocket",
          "centrifuge",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-message-queue",
        "summary": "Go message queue.",
        "values": [
          "nats",
          "watermill",
          "kafka-go",
          "asynq",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-caching",
        "summary": "Go caching.",
        "values": [
          "redis",
          "ristretto",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-config",
        "summary": "Go config loader.",
        "values": [
          "viper",
          "koanf",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-observability",
        "summary": "Go observability.",
        "values": [
          "opentelemetry",
          "prometheus",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-validation",
        "summary": "Go validation.",
        "values": [
          "validator",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-quality",
        "summary": "Go code quality.",
        "values": [
          "golangci-lint",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-migrations",
        "summary": "Go database migrations.",
        "values": [
          "golang-migrate",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-templating",
        "summary": "Go templating.",
        "values": [
          "templ",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-proto-tooling",
        "summary": "Go protobuf tooling.",
        "values": [
          "buf",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--go-di",
        "summary": "Go dependency injection.",
        "values": [
          "fx",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      }
    ]
  },
  {
    "id": "java",
    "title": "Java flags",
    "description": "Flags for `--ecosystem java`.",
    "flags": [
      {
        "flag": "--java-web-framework",
        "summary": "Java web framework.",
        "values": [
          "spring-boot",
          "quarkus",
          "micronaut",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "spring-boot",
        "multiple": false
      },
      {
        "flag": "--java-language",
        "summary": "JVM language (java or kotlin).",
        "values": [
          "java",
          "kotlin"
        ],
        "valueHint": null,
        "defaultValue": null,
        "multiple": false
      },
      {
        "flag": "--java-build-tool",
        "summary": "Build tool.",
        "values": [
          "maven",
          "gradle",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "maven",
        "multiple": false
      },
      {
        "flag": "--java-orm",
        "summary": "Java ORM / database.",
        "values": [
          "spring-data-jpa",
          "jooq",
          "mybatis",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--java-auth",
        "summary": "Java auth.",
        "values": [
          "spring-security",
          "keycloak",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--java-api",
        "summary": "Java API layer.",
        "values": [
          "spring-graphql",
          "openapi-generator",
          "grpc",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--java-logging",
        "summary": "Java logging.",
        "values": [
          "logback",
          "log4j2",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--java-libraries",
        "summary": "Java libraries.",
        "values": [
          "spring-actuator",
          "spring-validation",
          "flyway",
          "liquibase",
          "springdoc-openapi",
          "lombok",
          "mapstruct",
          "caffeine",
          "resilience4j",
          "spring-webflux",
          "spring-batch",
          "spring-kafka",
          "spring-mail",
          "spring-devtools",
          "micrometer-prometheus",
          "thymeleaf",
          "spring-amqp",
          "opentelemetry-java",
          "spring-data-redis",
          "spring-data-mongodb",
          "spring-data-elasticsearch",
          "spring-data-neo4j",
          "spring-data-cassandra",
          "spring-data-couchbase",
          "spring-data-jdbc",
          "spring-data-rest",
          "spring-quartz",
          "spring-pulsar",
          "spring-integration",
          "spring-websocket",
          "spring-rsocket",
          "spring-hateoas",
          "spring-session-redis",
          "spring-session-jdbc",
          "spring-ldap",
          "spring-oauth2-client",
          "spring-saml2",
          "spring-restclient",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      },
      {
        "flag": "--java-testing-libraries",
        "summary": "Java testing libraries.",
        "values": [
          "junit5",
          "mockito",
          "testcontainers",
          "assertj",
          "rest-assured",
          "wiremock",
          "awaitility",
          "archunit",
          "jqwik",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "junit5",
        "multiple": true
      }
    ]
  },
  {
    "id": "dotnet",
    "title": ".NET flags",
    "description": "Flags for `--ecosystem dotnet`.",
    "flags": [
      {
        "flag": "--dotnet-web-framework",
        "summary": ".NET web framework.",
        "values": [
          "aspnet-minimal",
          "aspnet-mvc",
          "aspnet-blazor",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "aspnet-minimal",
        "multiple": false
      },
      {
        "flag": "--dotnet-orm",
        "summary": ".NET data access.",
        "values": [
          "ef-core",
          "dapper",
          "linq2db",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "ef-core",
        "multiple": false
      },
      {
        "flag": "--dotnet-auth",
        "summary": ".NET auth.",
        "values": [
          "aspnet-identity",
          "duende-identityserver",
          "auth0-aspnet",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "aspnet-identity",
        "multiple": false
      },
      {
        "flag": "--dotnet-api",
        "summary": ".NET API style.",
        "values": [
          "minimal-api",
          "graphql-hotchocolate",
          "grpc-dotnet",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "minimal-api",
        "multiple": false
      },
      {
        "flag": "--dotnet-testing",
        "summary": ".NET testing libraries.",
        "values": [
          "xunit",
          "nunit",
          "moq",
          "testcontainers-dotnet",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "xunit",
        "multiple": true
      },
      {
        "flag": "--dotnet-job-queue",
        "summary": ".NET background jobs.",
        "values": [
          "hangfire",
          "quartz-net",
          "hosted-services",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--dotnet-realtime",
        "summary": ".NET realtime.",
        "values": [
          "signalr",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "signalr",
        "multiple": false
      },
      {
        "flag": "--dotnet-observability",
        "summary": ".NET observability.",
        "values": [
          "opentelemetry-dotnet",
          "serilog",
          "nlog",
          "health-checks",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "serilog",
        "multiple": true
      },
      {
        "flag": "--dotnet-validation",
        "summary": ".NET validation.",
        "values": [
          "fluentvalidation",
          "data-annotations",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--dotnet-caching",
        "summary": ".NET caching.",
        "values": [
          "redis",
          "memory-cache",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--dotnet-deploy",
        "summary": ".NET deploy target.",
        "values": [
          "docker",
          "azure",
          "aws",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "docker",
        "multiple": false
      },
      {
        "flag": "--dotnet-libraries",
        "summary": "Optional .NET libraries.",
        "values": [
          "automapper",
          "mediatr",
          "fastendpoints",
          "api-versioning",
          "scalar",
          "polly",
          "masstransit",
          "rebus",
          "coravel",
          "magic-onion",
          "prometheus-net",
          "seq",
          "application-insights",
          "sentry",
          "mongodb-driver",
          "nhibernate",
          "mapster",
          "scrutor",
          "refit",
          "fluent-email",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      }
    ]
  },
  {
    "id": "elixir",
    "title": "Elixir flags",
    "description": "Flags for `--ecosystem elixir`.",
    "flags": [
      {
        "flag": "--elixir-web-framework",
        "summary": "Elixir web framework.",
        "values": [
          "phoenix",
          "phoenix-live-view",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "phoenix",
        "multiple": false
      },
      {
        "flag": "--elixir-orm",
        "summary": "Elixir ORM / database.",
        "values": [
          "ecto",
          "ecto-sql",
          "myxql",
          "ecto_sqlite3",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "ecto-sql",
        "multiple": false
      },
      {
        "flag": "--elixir-auth",
        "summary": "Elixir auth.",
        "values": [
          "phx-gen-auth",
          "ueberauth",
          "guardian",
          "pow",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-api",
        "summary": "Elixir API layer.",
        "values": [
          "rest",
          "absinthe",
          "grpc",
          "open_api_spex",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "rest",
        "multiple": false
      },
      {
        "flag": "--elixir-realtime",
        "summary": "Elixir realtime.",
        "values": [
          "channels",
          "presence",
          "pubsub",
          "live-view-streams",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "channels",
        "multiple": false
      },
      {
        "flag": "--elixir-jobs",
        "summary": "Elixir jobs.",
        "values": [
          "oban",
          "quantum",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-validation",
        "summary": "Elixir validation.",
        "values": [
          "ecto-changesets",
          "nimble-options",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "ecto-changesets",
        "multiple": false
      },
      {
        "flag": "--elixir-http",
        "summary": "Elixir HTTP client.",
        "values": [
          "req",
          "finch",
          "tesla",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "req",
        "multiple": false
      },
      {
        "flag": "--elixir-json",
        "summary": "Elixir JSON library.",
        "values": [
          "jason",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "jason",
        "multiple": false
      },
      {
        "flag": "--elixir-email",
        "summary": "Elixir email.",
        "values": [
          "swoosh",
          "bamboo",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-caching",
        "summary": "Elixir caching.",
        "values": [
          "cachex",
          "nebulex",
          "redix",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-observability",
        "summary": "Elixir observability.",
        "values": [
          "telemetry",
          "opentelemetry",
          "prom_ex",
          "sentry",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "telemetry",
        "multiple": false
      },
      {
        "flag": "--elixir-testing",
        "summary": "Elixir testing.",
        "values": [
          "ex_unit",
          "mox",
          "bypass",
          "wallaby",
          "stream_data",
          "ex_machina",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "ex_unit",
        "multiple": false
      },
      {
        "flag": "--elixir-quality",
        "summary": "Elixir code quality.",
        "values": [
          "credo",
          "dialyxir",
          "sobelow",
          "excoveralls",
          "mix_audit",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "credo",
        "multiple": false
      },
      {
        "flag": "--elixir-i18n",
        "summary": "Elixir internationalization.",
        "values": [
          "gettext",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-http-server",
        "summary": "Elixir HTTP server.",
        "values": [
          "bandit",
          "cowboy",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "cowboy",
        "multiple": false
      },
      {
        "flag": "--elixir-application-framework",
        "summary": "Elixir application framework.",
        "values": [
          "ash",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-documentation",
        "summary": "Elixir documentation.",
        "values": [
          "ex_doc",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-clustering",
        "summary": "Elixir clustering.",
        "values": [
          "libcluster",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-deploy",
        "summary": "Elixir deploy target.",
        "values": [
          "docker",
          "fly",
          "gigalixir",
          "mix-release",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": false
      },
      {
        "flag": "--elixir-libraries",
        "summary": "Elixir libraries.",
        "values": [
          "broadway",
          "nx",
          "ex_aws",
          "floki",
          "rustler",
          "none"
        ],
        "valueHint": null,
        "defaultValue": "none",
        "multiple": true
      }
    ]
  }
];

export const CLI_FLAG_GROUPS_BY_ID: Record<string, CliFlagGroup> = Object.fromEntries(
  CLI_FLAG_GROUPS.map((group) => [group.id, group]),
);
