// Generated by scripts/validation/build-verified-combinations.ts. Do not edit by hand.

export type VerifiedCombinationActionLink = {
  label: string;
  href: string;
};

export type VerifiedCombinationSummary = {
  generatedAt: string;
  expiresAt: string;
  gitHead?: string;
  expectedTotals: {
    releaseGuard: number;
    publishedPackage: number;
  };
  smoke: Array<{
    label: string;
    sources: string[];
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  }>;
  releaseGuard: {
    source: string;
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    overallSuccess: boolean;
    generatedAt?: string;
    gitBranch?: string;
    gitHead?: string;
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  } | null;
  publishedPackage: {
    source: string;
    packageSpec?: string;
    generatedAt?: string;
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    overallSuccess: boolean;
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  } | null;
};

export const verifiedCombinationsSummary: VerifiedCombinationSummary = {
  "generatedAt": "2026-09-03T17:12:53.985Z",
  "expiresAt": "2026-09-05T05:12:53.985Z",
  "gitHead": "d644ce745a48cad689bb1446789e834a428e3607",
  "expectedTotals": {
    "releaseGuard": 22,
    "publishedPackage": 3
  },
  "smoke": [
    {
      "label": "PR core smoke",
      "sources": [
        "testing/.smoke-output/core/smoke-results.json"
      ],
      "pass": 0,
      "total": 12,
      "ownerArea": "testing",
      "actionLinks": [
        {
          "label": "preset",
          "href": "https://github.com/Marve10s/Better-Fullstack/blob/main/testing/lib/presets.ts"
        },
        {
          "label": "smoke harness",
          "href": "https://github.com/Marve10s/Better-Fullstack/blob/main/testing/smoke-test.ts"
        }
      ],
      "rerunCommand": "bun run test:smoke:pr-core",
      "failureHint": "Run the smoke preset and inspect the generated smoke-results.json source files.",
      "current": false,
      "reasons": [
        "missing"
      ]
    }
  ],
  "releaseGuard": null,
  "publishedPackage": null
};
