// Generated by scripts/validation/build-verified-combinations.ts. Do not edit by hand.

export type VerifiedCombinationActionLink = {
  label: string;
  href: string;
};

export type VerifiedCombinationSummary = {
  generatedAt: string;
  expiresAt: string;
  gitHead?: string;
  expectedTotals: {
    releaseGuard: number;
    publishedPackage: number;
  };
  smoke: Array<{
    label: string;
    sources: string[];
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  }>;
  scaffbench: Array<{
    label: string;
    source: string;
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    environmentQualified?: boolean;
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  }>;
  releaseGuard: {
    source: string;
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    overallSuccess: boolean;
    generatedAt?: string;
    gitBranch?: string;
    gitHead?: string;
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  } | null;
  publishedPackage: {
    source: string;
    packageSpec?: string;
    generatedAt?: string;
    pass: number;
    total: number;
    current?: boolean;
    reasons?: string[];
    overallSuccess: boolean;
    ownerArea: string;
    actionLinks: VerifiedCombinationActionLink[];
    rerunCommand: string;
    failureHint: string;
  } | null;
};

export const verifiedCombinationsSummary: VerifiedCombinationSummary = {
  "generatedAt": "2026-09-11T12:56:09.511Z",
  "expiresAt": "2026-09-13T00:56:09.511Z",
  "gitHead": "7528e1424ff55d916d822cb145fe63dba1cf6aaa",
  "expectedTotals": {
    "releaseGuard": 24,
    "publishedPackage": 3
  },
  "smoke": [
    {
      "label": "PR core smoke",
      "sources": [
        "testing/.smoke-output/core/smoke-results.json"
      ],
      "pass": 0,
      "total": 12,
      "ownerArea": "testing",
      "actionLinks": [
        {
          "label": "preset",
          "href": "https://github.com/Marve10s/Better-Fullstack/blob/main/testing/lib/presets.ts"
        },
        {
          "label": "smoke harness",
          "href": "https://github.com/Marve10s/Better-Fullstack/blob/main/testing/smoke-test.ts"
        }
      ],
      "rerunCommand": "bun run test:smoke:pr-core",
      "failureHint": "Run the smoke preset and inspect the generated smoke-results.json source files.",
      "current": false,
      "reasons": [
        "missing"
      ]
    }
  ],
  "scaffbench": [
    {
      "label": "ScaffBench 2",
      "source": "testing/.tmp-scaffbench-2/summary.json",
      "pass": 0,
      "total": 1,
      "ownerArea": "packages/template-generator/templates",
      "actionLinks": [
        {
          "label": "owner",
          "href": "https://github.com/Marve10s/Better-Fullstack/blob/main/packages/template-generator/templates"
        }
      ],
      "rerunCommand": "regenerate the ScaffBench summary in the archived run dir",
      "failureHint": "Inspect failureTags and validation steps in the ScaffBench summary, then follow the owner area for the stack family.",
      "current": false,
      "reasons": [
        "missing"
      ]
    }
  ],
  "releaseGuard": null,
  "publishedPackage": null
};
