import type { Ecosystem, TechCategory } from "./types";

export const TECH_OPTIONS: Record<
  TechCategory,
  {
    id: string;
    name: string;
    description: string;
    icon: string;
    color: string;
    default?: boolean;
    className?: string;
  }[]
> = {
  api: [
    {
      id: "trpc",
      name: "tRPC",
      description: "End-to-end typesafe APIs",
      icon: "https://cdn.simpleicons.org/trpc/398CCB",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "orpc",
      name: "oRPC",
      description: "Typesafe APIs Made Simple",
      icon: "/icon/orpc.svg",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "ts-rest",
      name: "ts-rest",
      description: "RPC-like client for REST APIs",
      icon: "",
      color: "from-green-400 to-green-600",
    },
    {
      id: "garph",
      name: "Garph",
      description: "Fullstack GraphQL Framework for TypeScript",
      icon: "",
      color: "from-pink-400 to-pink-600",
    },
    {
      id: "none",
      name: "No API",
      description: "No API layer (API routes disabled)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  webFrontend: [
    {
      id: "tanstack-router",
      name: "TanStack Router",
      description: "Modern type-safe router for React",
      icon: "/icon/tanstack.png",
      color: "from-blue-400 to-blue-600",
      default: true,
    },
    {
      id: "react-router",
      name: "React Router",
      description: "Declarative routing for React",
      icon: "/icon/react-router.svg",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "tanstack-start",
      name: "TanStack Start",
      description: "Full-stack React and Solid framework powered by TanStack Router",
      icon: "/icon/tanstack.png",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "next",
      name: "Next.js",
      description: "React framework with hybrid rendering",
      icon: "https://cdn.simpleicons.org/nextdotjs",
      color: "from-gray-700 to-black",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "nuxt",
      name: "Nuxt",
      description: "Vue full-stack framework (SSR, SSG, hybrid)",
      icon: "/icon/nuxt-js.svg",
      color: "from-green-400 to-green-700",
      default: false,
    },
    {
      id: "svelte",
      name: "Svelte",
      description: "Cybernetically enhanced web apps",
      icon: "/icon/svelte.png",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "solid",
      name: "Solid",
      description: "Simple and performant reactivity for building UIs",
      icon: "/icon/solid.svg",
      color: "from-blue-600 to-blue-800",
      default: false,
    },
    {
      id: "astro",
      name: "Astro",
      description: "Content-focused with Island Architecture",
      icon: "/icon/astro.svg",
      color: "from-purple-500 to-orange-500",
      default: false,
    },
    {
      id: "qwik",
      name: "Qwik",
      description: "Resumable framework with instant load times",
      icon: "https://cdn.simpleicons.org/qwik/AC7EF4",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "angular",
      name: "Angular",
      description: "Enterprise-grade TypeScript framework by Google",
      icon: "https://cdn.simpleicons.org/angular/DD0031",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "redwood",
      name: "RedwoodJS",
      description: "Opinionated fullstack (React + GraphQL + Prisma)",
      icon: "https://cdn.simpleicons.org/redwoodjs/BF4722",
      color: "from-red-600 to-orange-500",
      default: false,
    },
    {
      id: "fresh",
      name: "Fresh",
      description: "Deno-native framework with islands architecture",
      icon: "https://cdn.simpleicons.org/deno/000000",
      color: "from-teal-400 to-cyan-600",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "none",
      name: "No Web Frontend",
      description: "No web-based frontend",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  nativeFrontend: [
    {
      id: "native-bare",
      name: "Expo + Bare",
      description: "Expo with StyleSheet (no styling library)",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-blue-400 to-blue-600",
      className: "invert-0 dark:invert",
      default: true,
    },
    {
      id: "native-uniwind",
      name: "Expo + Uniwind",
      description: "Fastest Tailwind bindings for React Native with HeroUI Native",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "native-unistyles",
      name: "Expo + Unistyles",
      description: "Expo with Unistyles (type-safe styling)",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-pink-400 to-pink-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "none",
      name: "No Native Frontend",
      description: "No native mobile frontend",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  astroIntegration: [
    {
      id: "react",
      name: "React",
      description: "Full React component support (required for tRPC)",
      icon: "https://cdn.simpleicons.org/react/61DAFB",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "vue",
      name: "Vue",
      description: "Vue 3 component support",
      icon: "https://cdn.simpleicons.org/vuedotjs/4FC08D",
      color: "from-green-400 to-green-600",
    },
    {
      id: "svelte",
      name: "Svelte",
      description: "Svelte component support",
      icon: "/icon/svelte.png",
      color: "from-orange-500 to-orange-700",
    },
    {
      id: "solid",
      name: "Solid",
      description: "SolidJS component support",
      icon: "/icon/solid.svg",
      color: "from-blue-600 to-blue-800",
    },
    {
      id: "none",
      name: "None",
      description: "Astro components only (no client-side JS framework)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  runtime: [
    {
      id: "bun",
      name: "Bun",
      description: "Fast JavaScript runtime & toolkit",
      icon: "https://cdn.simpleicons.org/bun/FBF0DF",
      color: "from-amber-400 to-amber-600",
      default: true,
    },
    {
      id: "node",
      name: "Node.js",
      description: "JavaScript runtime environment",
      icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",
      color: "from-green-400 to-green-600",
    },
    {
      id: "workers",
      name: "Cloudflare Workers",
      description: "Serverless runtime for the edge",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No Runtime",
      description: "No specific runtime",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  backend: [
    {
      id: "hono",
      name: "Hono",
      description: "Ultrafast web framework",
      icon: "/icon/hono.svg",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "elysia",
      name: "Elysia",
      description: "TypeScript web framework",
      icon: "/icon/elysia.svg",
      color: "from-purple-500 to-purple-700",
    },
    {
      id: "express",
      name: "Express",
      description: "Popular Node.js framework",
      icon: "https://cdn.simpleicons.org/express",
      color: "from-gray-500 to-gray-700",
      className: "invert-0 dark:invert",
    },
    {
      id: "fastify",
      name: "Fastify",
      description: "Fast, low-overhead web framework for Node.js",
      icon: "https://cdn.simpleicons.org/fastify",
      color: "from-gray-500 to-gray-700",
      className: "invert-0 dark:invert",
    },
    {
      id: "nestjs",
      name: "NestJS",
      description: "Progressive Node.js framework for enterprise apps",
      icon: "https://cdn.simpleicons.org/nestjs/E0234E",
      color: "from-red-500 to-red-700",
    },
    {
      id: "encore",
      name: "Encore.ts",
      description: "Type-safe backend with built-in infrastructure",
      icon: "https://encore.dev/assets/branding/logo/logo.svg",
      color: "from-violet-500 to-indigo-700",
    },
    {
      id: "adonisjs",
      name: "AdonisJS",
      description: "Full-featured MVC framework for Node.js",
      icon: "https://cdn.simpleicons.org/adonisjs/5A45FF",
      color: "from-indigo-500 to-purple-700",
    },
    {
      id: "nitro",
      name: "Nitro",
      description: "Universal server framework (powers Nuxt)",
      icon: "/icon/nitro.svg",
      color: "from-cyan-500 to-teal-700",
    },
    {
      id: "fets",
      name: "feTS",
      description: "TypeScript HTTP Framework with e2e type-safety",
      icon: "/icon/fets.svg",
      color: "from-blue-600 to-cyan-700",
    },
    {
      id: "convex",
      name: "Convex",
      description: "Reactive backend-as-a-service",
      icon: "/icon/convex.svg",
      color: "from-pink-500 to-pink-700",
    },
    {
      id: "self-next",
      name: "Fullstack Next.js",
      description: "Use Next.js built-in API routes",
      icon: "https://cdn.simpleicons.org/nextdotjs",
      color: "from-gray-700 to-black",
      className: "invert-0 dark:invert",
    },
    {
      id: "self-tanstack-start",
      name: "Fullstack TanStack Start",
      description: "Use TanStack Start's built-in API routes",
      icon: "/icon/tanstack.png",
      color: "from-purple-400 to-purple-600",
    },
    {
      id: "self-astro",
      name: "Fullstack Astro",
      description: "Use Astro's built-in API routes with SSR",
      icon: "/icon/astro.svg",
      color: "from-purple-500 to-orange-500",
    },
    {
      id: "none",
      name: "No Backend",
      description: "Skip backend integration (frontend only)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  database: [
    {
      id: "sqlite",
      name: "SQLite",
      description: "File-based SQL database",
      icon: "https://cdn.simpleicons.org/sqlite/003B57",
      color: "from-blue-400 to-cyan-500",
      default: true,
    },
    {
      id: "postgres",
      name: "PostgreSQL",
      description: "Advanced SQL database",
      icon: "https://cdn.simpleicons.org/postgresql/4169E1",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "mysql",
      name: "MySQL",
      description: "Popular relational database",
      icon: "https://cdn.simpleicons.org/mysql/4479A1",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "mongodb",
      name: "MongoDB",
      description: "NoSQL document database",
      icon: "https://cdn.simpleicons.org/mongodb/47A248",
      color: "from-green-400 to-green-600",
    },
    {
      id: "edgedb",
      name: "EdgeDB",
      description: "Graph-relational database with built-in query builder",
      icon: "/icon/edgedb.svg",
      color: "from-emerald-500 to-teal-600",
    },
    {
      id: "redis",
      name: "Redis",
      description: "In-memory data store for caching and real-time data",
      icon: "https://cdn.simpleicons.org/redis/DC382D",
      color: "from-red-500 to-red-700",
    },
    {
      id: "none",
      name: "No Database",
      description: "Skip database integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  orm: [
    {
      id: "drizzle",
      name: "Drizzle",
      description: "TypeScript ORM",
      icon: "https://cdn.simpleicons.org/drizzle/C5F74F",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "prisma",
      name: "Prisma",
      description: "Next-gen ORM",
      icon: "https://cdn.simpleicons.org/prisma/2D3748",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "mongoose",
      name: "Mongoose",
      description: "Elegant object modeling tool",
      icon: "https://cdn.simpleicons.org/mongoose/880000",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "typeorm",
      name: "TypeORM",
      description: "Traditional ORM with Active Record/Data Mapper",
      icon: "https://cdn.simpleicons.org/typeorm/E83524",
      color: "from-red-400 to-red-600",
    },
    {
      id: "kysely",
      name: "Kysely",
      description: "Type-safe SQL query builder",
      icon: "https://kysely.dev/img/logo.svg",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "mikroorm",
      name: "MikroORM",
      description: "Data Mapper ORM for DDD",
      icon: "https://mikro-orm.io/img/logo.svg",
      color: "from-cyan-500 to-cyan-700",
    },
    {
      id: "sequelize",
      name: "Sequelize",
      description: "Mature ORM with wide adoption",
      icon: "https://cdn.simpleicons.org/sequelize/52B0E7",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "none",
      name: "No ORM",
      description: "Skip ORM integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  dbSetup: [
    {
      id: "turso",
      name: "Turso",
      description: "Distributed SQLite with edge replicas (libSQL)",
      icon: "https://cdn.simpleicons.org/turso/4FF8D2",
      color: "from-pink-400 to-pink-600",
    },
    {
      id: "d1",
      name: "Cloudflare D1",
      description: "Serverless SQLite-compatible database for Cloudflare Workers",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "neon",
      name: "Neon Postgres",
      description: "Serverless Postgres with autoscaling and branching",
      icon: "/icon/neon.svg",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "prisma-postgres",
      name: "Prisma PostgreSQL",
      description: "Managed Postgres via Prisma Data Platform",
      icon: "https://cdn.simpleicons.org/prisma/2D3748",
      color: "from-indigo-400 to-indigo-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "mongodb-atlas",
      name: "MongoDB Atlas",
      description: "Managed MongoDB clusters in the cloud",
      icon: "https://cdn.simpleicons.org/mongodb/47A248",
      color: "from-green-400 to-green-600",
    },
    {
      id: "supabase",
      name: "Supabase",
      description: "Local Postgres stack via Supabase (Docker required)",
      icon: "https://cdn.simpleicons.org/supabase/3FCF8E",
      color: "from-emerald-400 to-emerald-600",
    },
    {
      id: "planetscale",
      name: "PlanetScale",
      description: "Postgres & Vitess (MySQL) on NVMe",
      icon: "https://cdn.simpleicons.org/planetscale",
      color: "from-orange-400 to-orange-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "upstash",
      name: "Upstash",
      description: "Serverless Redis with REST API and global replication",
      icon: "https://cdn.simpleicons.org/upstash/00E9A3",
      color: "from-emerald-400 to-teal-600",
    },
    {
      id: "docker",
      name: "Docker",
      description: "Run Postgres/MySQL/MongoDB/Redis locally via Docker Compose",
      icon: "https://cdn.simpleicons.org/docker/2496ED",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "none",
      name: "Basic Setup",
      description: "No cloud DB integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  webDeploy: [
    {
      id: "cloudflare",
      name: "Cloudflare",
      description: "Deploy to Cloudflare Workers using Alchemy",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "fly",
      name: "Fly.io",
      description: "Deploy globally with Fly.io edge platform",
      icon: "https://cdn.simpleicons.org/flydotio/8B5CF6",
      color: "from-purple-400 to-purple-600",
    },
    {
      id: "railway",
      name: "Railway",
      description: "Deploy with Railway cloud development platform",
      icon: "https://cdn.simpleicons.org/railway/0B0D0E",
      color: "from-zinc-700 to-zinc-900",
    },
    {
      id: "docker",
      name: "Docker",
      description: "Container-based deployment with Dockerfile",
      icon: "https://cdn.simpleicons.org/docker/2496ED",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "sst",
      name: "SST",
      description: "Deploy to AWS with SST (Serverless Stack)",
      icon: "/icon/sst.svg",
      color: "from-orange-400 to-yellow-500",
    },
    {
      id: "none",
      name: "None",
      description: "Skip deployment setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  serverDeploy: [
    {
      id: "cloudflare",
      name: "Cloudflare",
      description: "Deploy to Cloudflare Workers using Alchemy",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "fly",
      name: "Fly.io",
      description: "Deploy globally with Fly.io edge platform",
      icon: "https://cdn.simpleicons.org/flydotio/8B5CF6",
      color: "from-purple-400 to-purple-600",
    },
    {
      id: "railway",
      name: "Railway",
      description: "Deploy with Railway cloud development platform",
      icon: "https://cdn.simpleicons.org/railway/0B0D0E",
      color: "from-zinc-700 to-zinc-900",
    },
    {
      id: "docker",
      name: "Docker",
      description: "Container-based deployment with Dockerfile",
      icon: "https://cdn.simpleicons.org/docker/2496ED",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "sst",
      name: "SST",
      description: "Deploy to AWS with SST (Serverless Stack)",
      icon: "/icon/sst.svg",
      color: "from-orange-400 to-yellow-500",
    },
    {
      id: "none",
      name: "None",
      description: "Skip deployment setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  auth: [
    {
      id: "better-auth",
      name: "Better-Auth",
      description: "The most comprehensive authentication framework for TypeScript",
      icon: "/icon/better-auth.svg",
      color: "from-green-400 to-green-600",
      default: true,
    },
    {
      id: "clerk",
      name: "Clerk",
      description: "More than authentication, Complete User Management",
      icon: "https://cdn.simpleicons.org/clerk/6C47FF",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "nextauth",
      name: "Auth.js (NextAuth)",
      description: "Open source authentication for Next.js",
      icon: "https://cdn.simpleicons.org/auth0/EB5424",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "stack-auth",
      name: "Stack Auth",
      description: "Open-source Auth0/Clerk alternative with user management",
      icon: "/icon/stack-auth.svg",
      color: "from-purple-400 to-purple-600",
    },
    {
      id: "supabase-auth",
      name: "Supabase Auth",
      description: "Open-source Auth with Supabase platform integration",
      icon: "https://cdn.simpleicons.org/supabase/3FCF8E",
      color: "from-emerald-400 to-emerald-600",
    },
    {
      id: "auth0",
      name: "Auth0",
      description: "Flexible identity platform for authentication and authorization",
      icon: "https://cdn.simpleicons.org/auth0/EB5424",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No Auth",
      description: "Skip authentication",
      icon: "",
      color: "from-red-400 to-red-600",
    },
  ],
  payments: [
    {
      id: "polar",
      name: "Polar",
      description: "Turn your software into a business. 6 lines of code.",
      icon: "/icon/polar.svg",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "stripe",
      name: "Stripe",
      description: "Industry standard payment processing",
      icon: "https://cdn.simpleicons.org/stripe/635BFF",
      color: "from-indigo-500 to-purple-600",
      default: false,
    },
    {
      id: "lemon-squeezy",
      name: "Lemon Squeezy",
      description: "MoR for digital products with tax handling",
      icon: "https://cdn.simpleicons.org/lemonsqueezy/FFC233",
      color: "from-yellow-400 to-yellow-600",
      default: false,
    },
    {
      id: "paddle",
      name: "Paddle",
      description: "MoR platform with global tax compliance",
      icon: "https://cdn.simpleicons.org/paddle/3D3D3D",
      color: "from-slate-500 to-slate-700",
      default: false,
    },
    {
      id: "dodo",
      name: "Dodo Payments",
      description: "MoR for AI and SaaS in 150+ countries",
      icon: "/icon/dodo.svg",
      color: "from-indigo-500 to-blue-600",
      default: false,
    },
    {
      id: "none",
      name: "No Payments",
      description: "Skip payments integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  email: [
    {
      id: "resend",
      name: "Resend",
      description: "Modern email API for developers",
      icon: "https://cdn.simpleicons.org/resend",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "react-email",
      name: "React Email",
      description: "Build emails using React components (no sending)",
      icon: "https://cdn.simpleicons.org/react/61DAFB",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "nodemailer",
      name: "Nodemailer",
      description: "Classic Node.js email sending via SMTP",
      icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",
      color: "from-green-400 to-green-600",
      default: false,
    },
    {
      id: "postmark",
      name: "Postmark",
      description: "Fast transactional email service",
      icon: "https://cdn.simpleicons.org/postmark/FFDE00",
      color: "from-yellow-400 to-yellow-600",
      default: false,
    },
    {
      id: "sendgrid",
      name: "SendGrid",
      description: "Scalable email delivery platform",
      icon: "/icon/sendgrid.svg",
      color: "from-blue-400 to-blue-600",
      default: false,
    },
    {
      id: "aws-ses",
      name: "AWS SES",
      description: "Amazon Simple Email Service",
      icon: "/icon/aws-ses.svg",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "mailgun",
      name: "Mailgun",
      description: "Powerful email API for developers",
      icon: "https://cdn.simpleicons.org/mailgun/F06B66",
      color: "from-red-400 to-red-600",
      default: false,
    },
    {
      id: "plunk",
      name: "Plunk",
      description: "Open-source email platform with event tracking",
      icon: "/icon/plunk.svg",
      color: "from-violet-400 to-violet-600",
      default: false,
    },
    {
      id: "none",
      name: "No Email",
      description: "Skip email integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  fileUpload: [
    {
      id: "uploadthing",
      name: "UploadThing",
      description: "TypeScript-first file uploads with built-in validation",
      icon: "https://uploadthing.com/favicon.ico",
      color: "from-red-400 to-red-600",
      default: false,
    },
    {
      id: "filepond",
      name: "FilePond",
      description: "Flexible file upload with image preview and drag & drop",
      icon: "/icon/filepond.svg",
      color: "from-yellow-400 to-amber-600",
      default: false,
    },
    {
      id: "uppy",
      name: "Uppy",
      description: "Modular file uploader with resumable uploads and plugins",
      icon: "https://uppy.io/img/logo.svg",
      color: "from-cyan-400 to-teal-600",
      default: false,
    },
    {
      id: "none",
      name: "No File Upload",
      description: "Skip file upload integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  logging: [
    {
      id: "pino",
      name: "Pino",
      description: "Fast JSON logger with minimal overhead",
      icon: "",
      color: "from-green-400 to-green-600",
      default: false,
    },
    {
      id: "winston",
      name: "Winston",
      description: "Flexible logging library with multiple transports",
      icon: "",
      color: "from-blue-400 to-blue-600",
      default: false,
    },
    {
      id: "none",
      name: "No Logging",
      description: "Skip logging framework setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  observability: [
    {
      id: "opentelemetry",
      name: "OpenTelemetry",
      description: "Observability framework for traces, metrics, and logs",
      icon: "",
      color: "from-blue-400 to-cyan-500",
      default: false,
    },
    {
      id: "sentry",
      name: "Sentry",
      description: "Error tracking and performance monitoring",
      icon: "https://cdn.simpleicons.org/sentry/362D59",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "grafana",
      name: "Grafana",
      description: "Prometheus metrics for Grafana dashboards and alerting",
      icon: "https://cdn.simpleicons.org/grafana/F46800",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "none",
      name: "No Observability",
      description: "Skip observability/tracing setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  featureFlags: [
    {
      id: "growthbook",
      name: "GrowthBook",
      description: "Open-source feature flags and A/B testing platform",
      icon: "",
      color: "from-purple-500 to-indigo-600",
      default: false,
    },
    {
      id: "posthog",
      name: "PostHog",
      description: "Feature flags with analytics, session replay, and A/B testing",
      icon: "/icon/posthog.svg",
      color: "from-yellow-500 to-orange-600",
      default: false,
    },
    {
      id: "none",
      name: "No Feature Flags",
      description: "Skip feature flags setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  analytics: [
    {
      id: "plausible",
      name: "Plausible",
      description: "Privacy-focused, lightweight analytics - no cookies required",
      icon: "",
      color: "from-indigo-500 to-purple-600",
      default: false,
    },
    {
      id: "none",
      name: "No Analytics",
      description: "Skip analytics setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  backendLibraries: [
    {
      id: "effect",
      name: "Effect (Core)",
      description: "Powerful effect system for TypeScript",
      icon: "/icon/effect.svg",
      color: "from-indigo-400 to-indigo-600",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "effect-full",
      name: "Effect Full",
      description: "Full ecosystem with Schema, Platform, and SQL",
      icon: "/icon/effect.svg",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "none",
      name: "None",
      description: "No additional backend libraries",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  stateManagement: [
    {
      id: "zustand",
      name: "Zustand",
      description: "Lightweight state management with simple API",
      icon: "",
      color: "from-amber-400 to-amber-600",
      default: false,
    },
    {
      id: "jotai",
      name: "Jotai",
      description: "Primitive and flexible atomic state",
      icon: "",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "nanostores",
      name: "Nanostores",
      description: "Tiny state manager (1KB) for all frameworks",
      icon: "",
      color: "from-blue-400 to-blue-600",
      default: false,
    },
    {
      id: "redux-toolkit",
      name: "Redux Toolkit",
      description: "Enterprise-standard state with excellent TS support",
      icon: "https://cdn.simpleicons.org/redux/764ABC",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "mobx",
      name: "MobX",
      description: "Observable-based reactive state management",
      icon: "https://cdn.simpleicons.org/mobx/FF9955",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "xstate",
      name: "XState",
      description: "State machines and statecharts for complex logic",
      icon: "https://cdn.simpleicons.org/xstate/2C3E50",
      color: "from-slate-600 to-slate-800",
      default: false,
    },
    {
      id: "valtio",
      name: "Valtio",
      description: "Proxy-based state (same authors as Zustand)",
      icon: "",
      color: "from-teal-400 to-teal-600",
      default: false,
    },
    {
      id: "tanstack-store",
      name: "TanStack Store",
      description: "Framework-agnostic store powering TanStack ecosystem",
      icon: "",
      color: "from-red-400 to-orange-500",
      default: false,
    },
    {
      id: "legend-state",
      name: "Legend State",
      description: "High-performance observable state for React",
      icon: "",
      color: "from-violet-400 to-violet-600",
      default: false,
    },
    {
      id: "none",
      name: "No State Management",
      description: "Skip state management setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  forms: [
    {
      id: "react-hook-form",
      name: "React Hook Form",
      description: "Performant, flexible form validation library",
      icon: "https://cdn.simpleicons.org/reacthookform/EC5990",
      color: "from-pink-400 to-pink-600",
      default: true,
    },
    {
      id: "tanstack-form",
      name: "TanStack Form",
      description: "Fully-typed, framework-agnostic form library",
      icon: "/icon/tanstack.png",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "formik",
      name: "Formik",
      description: "Popular form state management with Yup validation",
      icon: "",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "final-form",
      name: "Final Form",
      description: "Framework-agnostic form state management",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "conform",
      name: "Conform",
      description: "Progressive enhancement forms with Zod validation",
      icon: "",
      color: "from-emerald-500 to-emerald-700",
      default: false,
    },
    {
      id: "modular-forms",
      name: "Modular Forms",
      description: "Type-safe forms for Solid and Qwik (3KB bundle)",
      icon: "",
      color: "from-sky-400 to-sky-600",
      default: false,
    },
    {
      id: "none",
      name: "No Form Library",
      description: "Build custom form handling",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  validation: [
    {
      id: "zod",
      name: "Zod",
      description: "TypeScript-first schema validation (default)",
      icon: "https://cdn.simpleicons.org/zod/3E67B1",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "valibot",
      name: "Valibot",
      description: "Smaller bundle alternative to Zod (~1KB)",
      icon: "",
      color: "from-yellow-400 to-yellow-600",
      default: false,
    },
    {
      id: "arktype",
      name: "ArkType",
      description: "TypeScript-first validation, 2-4x faster than Zod",
      icon: "",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "typebox",
      name: "TypeBox",
      description: "JSON Schema type builder for TypeScript",
      icon: "",
      color: "from-sky-400 to-sky-600",
      default: false,
    },
    {
      id: "typia",
      name: "Typia",
      description: "Super-fast validation via compile-time transform",
      icon: "",
      color: "from-green-400 to-green-600",
      default: false,
    },
    {
      id: "runtypes",
      name: "Runtypes",
      description: "Runtime type validation with composable validators",
      icon: "",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "effect-schema",
      name: "@effect/schema",
      description: "Effect ecosystem schema validation with powerful transformations",
      icon: "",
      color: "from-black to-gray-700",
      default: false,
    },
    {
      id: "none",
      name: "No Validation",
      description: "Use Zod internally only (no additional library)",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  cssFramework: [
    {
      id: "tailwind",
      name: "Tailwind CSS",
      description: "Utility-first CSS framework",
      icon: "https://cdn.simpleicons.org/tailwindcss/06B6D4",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "scss",
      name: "SCSS",
      description: "CSS preprocessor with variables and nesting",
      icon: "https://cdn.simpleicons.org/sass/CC6699",
      color: "from-pink-400 to-pink-600",
    },
    {
      id: "less",
      name: "Less",
      description: "Backwards-compatible CSS extension",
      icon: "https://cdn.simpleicons.org/less/1D365D",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "postcss-only",
      name: "PostCSS Only",
      description: "Minimal CSS with PostCSS plugins",
      icon: "https://cdn.simpleicons.org/postcss/DD3A0A",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No CSS Framework",
      description: "Plain CSS only",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  uiLibrary: [
    {
      id: "shadcn-ui",
      name: "shadcn/ui",
      description: "Re-usable components built with Radix and Tailwind",
      icon: "https://cdn.simpleicons.org/shadcnui",
      color: "from-gray-600 to-gray-800",
      default: true,
      className: "invert-0 dark:invert",
    },
    {
      id: "daisyui",
      name: "daisyUI",
      description: "Tailwind CSS component library",
      icon: "https://cdn.simpleicons.org/daisyui/1AD1A5",
      color: "from-emerald-400 to-emerald-600",
    },
    {
      id: "radix-ui",
      name: "Radix UI",
      description: "Unstyled, accessible UI components",
      icon: "https://cdn.simpleicons.org/radixui",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "headless-ui",
      name: "Headless UI",
      description: "Unstyled, accessible components by Tailwind Labs",
      icon: "https://cdn.simpleicons.org/headlessui/66E3FF",
      color: "from-cyan-400 to-cyan-600",
    },
    {
      id: "park-ui",
      name: "Park UI",
      description: "Beautifully designed components built on Ark UI",
      icon: "",
      color: "from-green-400 to-green-600",
    },
    {
      id: "chakra-ui",
      name: "Chakra UI",
      description: "Simple, modular React component library",
      icon: "https://cdn.simpleicons.org/chakraui/319795",
      color: "from-teal-400 to-teal-600",
    },
    {
      id: "nextui",
      name: "NextUI",
      description: "Beautiful, fast and modern React UI library",
      icon: "/icon/nextui.svg",
      color: "from-gray-600 to-gray-800",
    },
    {
      id: "mantine",
      name: "Mantine",
      description: "Full-featured React component library",
      icon: "https://cdn.simpleicons.org/mantine/339AF0",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "base-ui",
      name: "Base UI",
      description: "Unstyled components from MUI team (Radix successor)",
      icon: "https://cdn.simpleicons.org/mui/007FFF",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "ark-ui",
      name: "Ark UI",
      description: "Headless UI for React, Vue, Solid, and Svelte",
      icon: "",
      color: "from-green-500 to-teal-600",
    },
    {
      id: "react-aria",
      name: "React Aria",
      description: "Adobe's accessible, unstyled UI components",
      icon: "",
      color: "from-red-500 to-red-700",
    },
    {
      id: "none",
      name: "No UI Library",
      description: "Build custom components",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  packageManager: [
    {
      id: "npm",
      name: "npm",
      description: "Default package manager",
      icon: "https://cdn.simpleicons.org/npm/CB3837",
      color: "from-red-500 to-red-700",
    },
    {
      id: "pnpm",
      name: "pnpm",
      description: "Fast, disk space efficient",
      icon: "https://cdn.simpleicons.org/pnpm/F69220",
      color: "from-orange-500 to-orange-700",
    },
    {
      id: "bun",
      name: "bun",
      description: "All-in-one toolkit",
      icon: "https://cdn.simpleicons.org/bun/FBF0DF",
      color: "from-amber-500 to-amber-700",
      default: true,
    },
  ],
  codeQuality: [
    {
      id: "biome",
      name: "Biome",
      description: "Format, lint, and more",
      icon: "https://cdn.simpleicons.org/biome/60A5FA",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "oxlint",
      name: "Oxlint",
      description: "Oxlint + Oxfmt (linting & formatting)",
      icon: "https://cdn.simpleicons.org/oxc/FF915C",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "ultracite",
      name: "Ultracite",
      description: "Biome preset with AI integration",
      icon: "/icon/ultracite.svg",
      color: "from-indigo-500 to-indigo-700",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "lefthook",
      name: "Lefthook",
      description: "Fast and powerful Git hooks manager",
      icon: "",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "husky",
      name: "Husky",
      description: "Modern native Git hooks made easy",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "ruler",
      name: "Ruler",
      description: "Centralize your AI rules",
      icon: "",
      color: "from-violet-500 to-violet-700",
      default: false,
    },
  ],
  documentation: [
    {
      id: "starlight",
      name: "Starlight",
      description: "Build stellar docs with Astro",
      icon: "/icon/starlight.svg",
      color: "from-amber-500 to-amber-700",
      default: false,
    },
    {
      id: "fumadocs",
      name: "Fumadocs",
      description: "Build excellent documentation site",
      icon: "/icon/fumadocs.svg",
      color: "from-indigo-500 to-indigo-700",
      default: false,
    },
  ],
  appPlatforms: [
    {
      id: "turborepo",
      name: "Turborepo",
      description: "High-performance build system",
      icon: "https://cdn.simpleicons.org/turborepo/EF4444",
      color: "from-gray-400 to-gray-700",
      default: true,
    },
    {
      id: "pwa",
      name: "PWA",
      description: "Make your app installable and work offline",
      icon: "",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "tauri",
      name: "Tauri",
      description: "Build native desktop apps",
      icon: "https://cdn.simpleicons.org/tauri/FFC131",
      color: "from-amber-500 to-amber-700",
      default: false,
    },
    {
      id: "wxt",
      name: "WXT",
      description: "Build browser extensions",
      icon: "",
      color: "from-emerald-500 to-emerald-700",
      default: false,
    },
    {
      id: "opentui",
      name: "OpenTUI",
      description: "Build terminal user interfaces",
      icon: "",
      color: "from-cyan-500 to-cyan-700",
      default: false,
    },
    {
      id: "msw",
      name: "MSW",
      description: "Mock Service Worker for API mocking in tests and development",
      icon: "",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "storybook",
      name: "Storybook",
      description: "Component development and testing workshop",
      icon: "https://cdn.simpleicons.org/storybook/FF4785",
      color: "from-pink-500 to-pink-700",
      default: false,
    },
  ],
  examples: [
    {
      id: "todo",
      name: "Todo Example",
      description: "Simple todo application",
      icon: "",
      color: "from-indigo-500 to-indigo-700",
      default: false,
    },
    {
      id: "ai",
      name: "AI Example",
      description: "AI integration example using AI SDK",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
  ],
  ai: [
    {
      id: "vercel-ai",
      name: "Vercel AI SDK",
      description: "Unified AI SDK for streaming responses and multiple providers",
      icon: "https://cdn.simpleicons.org/vercel/000000",
      color: "from-gray-700 to-black",
      default: true,
      className: "invert-0 dark:invert",
    },
    {
      id: "mastra",
      name: "Mastra",
      description: "TypeScript-native AI agent framework with workflows",
      icon: "/icon/mastra.svg",
      color: "from-purple-500 to-indigo-600",
      default: false,
    },
    {
      id: "voltagent",
      name: "VoltAgent",
      description: "AI Agent framework with memory, workflows, and observability",
      icon: "/icon/voltagent.svg",
      color: "from-yellow-500 to-orange-600",
      default: false,
    },
    {
      id: "langgraph",
      name: "LangGraph.js",
      description: "Graph-based agent orchestration with stateful workflows",
      icon: "/icon/langgraph.svg",
      color: "from-green-500 to-teal-600",
      default: false,
    },
    {
      id: "openai-agents",
      name: "OpenAI Agents SDK",
      description: "Official multi-agent framework with handoffs and guardrails",
      icon: "/icon/openai.svg",
      color: "from-emerald-500 to-teal-600",
      default: false,
    },
    {
      id: "google-adk",
      name: "Google ADK",
      description: "Code-first agent development kit for building AI agents",
      icon: "https://cdn.simpleicons.org/google/4285F4",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "modelfusion",
      name: "ModelFusion",
      description: "Type-safe AI library for multi-provider text generation",
      icon: "https://cdn.simpleicons.org/vercel/000000",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "langchain",
      name: "LangChain",
      description: "Build context-aware reasoning applications",
      icon: "https://cdn.simpleicons.org/langchain/1C3C3C",
      color: "from-green-500 to-emerald-700",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "llamaindex",
      name: "LlamaIndex",
      description: "Data framework for LLM applications",
      icon: "",
      color: "from-purple-500 to-violet-700",
      default: false,
    },
    {
      id: "none",
      name: "No AI SDK",
      description: "Skip AI SDK integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  realtime: [
    {
      id: "socket-io",
      name: "Socket.IO",
      description: "Real-time bidirectional communication with fallbacks",
      icon: "https://cdn.simpleicons.org/socketdotio/010101",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "partykit",
      name: "PartyKit",
      description: "Edge-native multiplayer infrastructure on Cloudflare",
      icon: "https://cdn.simpleicons.org/cloudflare/F38020",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "ably",
      name: "Ably",
      description: "Real-time messaging platform with pub/sub and presence",
      icon: "/icon/ably.svg",
      color: "from-orange-500 to-red-600",
      default: false,
    },
    {
      id: "pusher",
      name: "Pusher",
      description: "Real-time communication APIs with channels and events",
      icon: "https://cdn.simpleicons.org/pusher/300D4F",
      color: "from-purple-600 to-indigo-800",
      default: false,
    },
    {
      id: "liveblocks",
      name: "Liveblocks",
      description: "Collaboration infrastructure for multiplayer experiences",
      icon: "/icon/liveblocks.svg",
      color: "from-indigo-500 to-purple-600",
      default: false,
    },
    {
      id: "yjs",
      name: "Y.js",
      description: "CRDT library for real-time collaboration with conflict-free sync",
      icon: "",
      color: "from-emerald-500 to-teal-600",
      default: false,
    },
    {
      id: "none",
      name: "No Real-time",
      description: "Skip real-time/WebSocket integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  jobQueue: [
    {
      id: "bullmq",
      name: "BullMQ",
      description: "Redis-backed job queue for background tasks and scheduling",
      icon: "https://cdn.simpleicons.org/redis/DC382D",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "trigger-dev",
      name: "Trigger.dev",
      description: "Background jobs as code with serverless execution",
      icon: "/icon/trigger-dev.svg",
      color: "from-green-500 to-emerald-600",
      default: false,
    },
    {
      id: "inngest",
      name: "Inngest",
      description: "Event-driven functions with built-in queuing and scheduling",
      icon: "/icon/inngest.svg",
      color: "from-indigo-500 to-purple-600",
      default: false,
    },
    {
      id: "temporal",
      name: "Temporal",
      description: "Durable workflow orchestration for reliable distributed systems",
      icon: "/icon/temporal.svg",
      color: "from-blue-500 to-cyan-600",
      default: false,
    },
    {
      id: "none",
      name: "No Job Queue",
      description: "Skip job queue/background worker setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  effect: [
    {
      id: "effect",
      name: "Effect (Core)",
      description: "Powerful effect system for TypeScript",
      icon: "/icon/effect.svg",
      color: "from-indigo-400 to-indigo-600",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "effect-full",
      name: "Effect Full",
      description: "Full ecosystem with Schema, Platform, and SQL",
      icon: "/icon/effect.svg",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "none",
      name: "None",
      description: "No Effect library",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  caching: [
    {
      id: "upstash-redis",
      name: "Upstash Redis",
      description: "Serverless Redis with REST API for edge and serverless",
      icon: "https://cdn.simpleicons.org/upstash/00E9A3",
      color: "from-emerald-500 to-teal-600",
      default: false,
    },
    {
      id: "none",
      name: "No Caching",
      description: "Skip caching layer setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  search: [
    {
      id: "meilisearch",
      name: "Meilisearch",
      description: "Lightning-fast search engine with typo tolerance and instant results",
      icon: "https://cdn.simpleicons.org/meilisearch/FF5CAA",
      color: "from-pink-500 to-rose-600",
      default: false,
    },
    {
      id: "typesense",
      name: "Typesense",
      description: "Fast, typo-tolerant search with built-in vector search",
      icon: "https://cdn.simpleicons.org/typesense/D21F27",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "none",
      name: "No Search",
      description: "Skip search engine setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  fileStorage: [
    {
      id: "s3",
      name: "AWS S3",
      description: "Amazon S3 object storage - scalable and reliable",
      icon: "https://cdn.simpleicons.org/amazons3/569A31",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "r2",
      name: "Cloudflare R2",
      description: "S3-compatible storage with zero egress fees",
      icon: "https://cdn.simpleicons.org/cloudflare/F38020",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "none",
      name: "No File Storage",
      description: "Skip file storage setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  animation: [
    {
      id: "framer-motion",
      name: "Framer Motion",
      description: "Production-ready declarative animations for React",
      icon: "https://cdn.simpleicons.org/framer/0055FF",
      color: "from-blue-500 to-purple-600",
      default: false,
    },
    {
      id: "gsap",
      name: "GSAP",
      description: "Professional-grade animation engine for the web",
      icon: "https://cdn.simpleicons.org/greensock/88CE02",
      color: "from-green-500 to-green-700",
      default: false,
    },
    {
      id: "react-spring",
      name: "React Spring",
      description: "Physics-based animations for fluid interactions",
      icon: "",
      color: "from-pink-400 to-pink-600",
      default: false,
    },
    {
      id: "auto-animate",
      name: "Auto Animate",
      description: "Zero-config, drop-in animation utility",
      icon: "/icon/auto-animate.svg",
      color: "from-green-400 to-emerald-600",
      default: false,
    },
    {
      id: "lottie",
      name: "Lottie",
      description: "Render After Effects animations natively",
      icon: "https://cdn.simpleicons.org/airbnb/FF5A5F",
      color: "from-pink-500 to-red-500",
      default: false,
    },
    {
      id: "none",
      name: "No Animation",
      description: "Skip animation library setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  testing: [
    {
      id: "vitest",
      name: "Vitest",
      description:
        "Blazing fast Vite-native unit test framework with Testing Library support for React/Vue/Svelte",
      icon: "https://cdn.simpleicons.org/vitest/6E9F18",
      color: "from-green-400 to-green-600",
      default: true,
    },
    {
      id: "jest",
      name: "Jest",
      description: "Classic testing framework with Testing Library support for React/Vue/Svelte",
      icon: "https://cdn.simpleicons.org/jest/C21325",
      color: "from-red-400 to-red-600",
      default: false,
    },
    {
      id: "playwright",
      name: "Playwright",
      description: "End-to-end testing framework by Microsoft",
      icon: "/icon/playwright.svg",
      color: "from-emerald-400 to-emerald-600",
      default: false,
    },
    {
      id: "vitest-playwright",
      name: "Vitest + Playwright",
      description: "Both unit and E2E testing with Testing Library support for complete coverage",
      icon: "https://cdn.simpleicons.org/vitest/6E9F18",
      color: "from-green-500 to-emerald-600",
      default: false,
    },
    {
      id: "cypress",
      name: "Cypress",
      description: "E2E testing with time travel debugging",
      icon: "https://cdn.simpleicons.org/cypress/69D3A7",
      color: "from-teal-400 to-teal-600",
      default: false,
    },
    {
      id: "none",
      name: "No Testing",
      description: "Skip testing framework setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  cms: [
    {
      id: "payload",
      name: "Payload",
      description: "TypeScript-first headless CMS with Next.js integration",
      icon: "/icon/payload.svg",
      color: "from-slate-700 to-slate-900",
      default: false,
    },
    {
      id: "sanity",
      name: "Sanity",
      description: "Real-time collaborative CMS with schema-as-code",
      icon: "https://cdn.simpleicons.org/sanity/F03E2F",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "strapi",
      name: "Strapi",
      description: "Open-source headless CMS with admin panel",
      icon: "https://cdn.simpleicons.org/strapi/4945FF",
      color: "from-indigo-500 to-purple-600",
      default: false,
    },
    {
      id: "none",
      name: "No CMS",
      description: "Skip headless CMS setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  git: [
    {
      id: "true",
      name: "Git",
      description: "Initialize Git repository",
      icon: "https://cdn.simpleicons.org/git/F05032",
      color: "from-gray-500 to-gray-700",
      default: true,
    },
    {
      id: "false",
      name: "No Git",
      description: "Skip Git initialization",
      icon: "",
      color: "from-red-400 to-red-600",
    },
  ],
  install: [
    {
      id: "true",
      name: "Install Dependencies",
      description: "Install packages automatically",
      icon: "",
      color: "from-green-400 to-green-600",
      default: true,
    },
    {
      id: "false",
      name: "Skip Install",
      description: "Skip dependency installation",
      icon: "",
      color: "from-yellow-400 to-yellow-600",
    },
  ],
  // Rust ecosystem categories
  rustWebFramework: [
    {
      id: "axum",
      name: "Axum",
      description: "Ergonomic and modular web framework by Tokio team",
      icon: "/icon/axum.svg",
      color: "from-blue-500 to-indigo-600",
      default: true,
    },
    {
      id: "actix-web",
      name: "Actix-web",
      description: "Powerful, pragmatic, and extremely fast web framework",
      icon: "/icon/actix.svg",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "none",
      name: "No Web Framework",
      description: "Skip Rust web framework",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  rustFrontend: [
    {
      id: "leptos",
      name: "Leptos",
      description: "Fine-grained reactive framework with SSR support",
      icon: "/icon/leptos.svg",
      color: "from-red-500 to-orange-600",
      default: true,
    },
    {
      id: "dioxus",
      name: "Dioxus",
      description: "React-like GUI library for web, desktop, and mobile",
      icon: "/icon/dioxus.svg",
      color: "from-cyan-500 to-blue-600",
      default: false,
    },
    {
      id: "none",
      name: "No WASM Frontend",
      description: "Skip Rust WASM frontend",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  rustOrm: [
    {
      id: "sea-orm",
      name: "SeaORM",
      description: "Async & dynamic ORM with ActiveRecord pattern",
      icon: "/icon/seaorm.svg",
      color: "from-cyan-500 to-blue-600",
      default: true,
    },
    {
      id: "sqlx",
      name: "SQLx",
      description: "Async SQL toolkit with compile-time checked queries",
      icon: "",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "none",
      name: "No ORM",
      description: "Skip Rust ORM/database layer",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  rustApi: [
    {
      id: "async-graphql",
      name: "async-graphql",
      description: "High-performance GraphQL server with full query language support",
      icon: "https://cdn.simpleicons.org/graphql/E10098",
      color: "from-pink-500 to-rose-600",
      default: false,
    },
    {
      id: "tonic",
      name: "Tonic",
      description: "Production-ready gRPC implementation for Rust",
      icon: "/icon/tonic.svg",
      color: "from-orange-500 to-red-600",
      default: false,
    },
    {
      id: "none",
      name: "No API Layer",
      description: "Skip Rust API layer",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  rustCli: [
    {
      id: "clap",
      name: "Clap",
      description: "CLI argument parser with derive macros (most popular)",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "ratatui",
      name: "Ratatui",
      description: "Terminal user interface library for building rich TUIs",
      icon: "",
      color: "from-emerald-500 to-teal-700",
      default: false,
    },
    {
      id: "none",
      name: "No CLI Tools",
      description: "Skip Rust CLI tools",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  rustLibraries: [
    {
      id: "serde",
      name: "Serde",
      description: "De facto standard serialization framework (always included)",
      icon: "",
      color: "from-orange-500 to-orange-700",
      default: true,
    },
    {
      id: "validator",
      name: "Validator",
      description: "Derive-based validation for structs and fields",
      icon: "",
      color: "from-green-500 to-green-700",
      default: false,
    },
    {
      id: "jsonwebtoken",
      name: "jsonwebtoken",
      description: "JWT encoding and decoding for authentication",
      icon: "",
      color: "from-blue-500 to-indigo-700",
      default: false,
    },
    {
      id: "argon2",
      name: "Argon2",
      description: "Secure password hashing (Argon2id winner of PHC)",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "tokio-test",
      name: "Tokio Test",
      description: "Async testing utilities for Tokio runtime",
      icon: "",
      color: "from-cyan-500 to-blue-600",
      default: false,
    },
    {
      id: "mockall",
      name: "Mockall",
      description: "Powerful mock objects library for Rust testing",
      icon: "",
      color: "from-rose-500 to-pink-600",
      default: false,
    },
    {
      id: "none",
      name: "No Additional Libraries",
      description: "Skip additional Rust core libraries",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  // Python ecosystem options
  pythonWebFramework: [
    {
      id: "fastapi",
      name: "FastAPI",
      description: "Modern, fast (high-performance) web framework for building APIs with Python",
      icon: "https://cdn.simpleicons.org/fastapi/009688",
      color: "from-teal-500 to-green-600",
      default: true,
    },
    {
      id: "django",
      name: "Django",
      description: "High-level Python web framework with batteries included",
      icon: "https://cdn.simpleicons.org/django/092E20",
      color: "from-green-700 to-green-900",
      default: false,
    },
    {
      id: "none",
      name: "No Web Framework",
      description: "Skip Python web framework selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  pythonOrm: [
    {
      id: "sqlalchemy",
      name: "SQLAlchemy",
      description: "The Python SQL toolkit and Object Relational Mapper",
      icon: "",
      color: "from-red-500 to-red-700",
      default: true,
    },
    {
      id: "sqlmodel",
      name: "SQLModel",
      description:
        "SQL databases in Python, designed for simplicity and compatibility with FastAPI",
      icon: "",
      color: "from-teal-500 to-cyan-600",
      default: false,
    },
    {
      id: "none",
      name: "No ORM",
      description: "Skip Python ORM selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  pythonValidation: [
    {
      id: "pydantic",
      name: "Pydantic",
      description: "Data validation using Python type annotations",
      icon: "https://cdn.simpleicons.org/pydantic/E92063",
      color: "from-pink-500 to-rose-600",
      default: true,
    },
    {
      id: "none",
      name: "No Validation Library",
      description: "Skip Python validation library selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  pythonAi: [
    {
      id: "langchain",
      name: "LangChain",
      description: "Framework for developing applications powered by language models",
      icon: "https://cdn.simpleicons.org/langchain/1C3C3C",
      color: "from-emerald-500 to-green-700",
      default: false,
    },
    {
      id: "llamaindex",
      name: "LlamaIndex",
      description: "Data framework for LLM-based applications",
      icon: "",
      color: "from-purple-500 to-violet-700",
      default: false,
    },
    {
      id: "openai-sdk",
      name: "OpenAI SDK",
      description: "Official OpenAI Python client for GPT models",
      icon: "/icon/openai.svg",
      color: "from-gray-700 to-gray-900",
      default: false,
    },
    {
      id: "anthropic-sdk",
      name: "Anthropic SDK",
      description: "Official Anthropic Python client for Claude models",
      icon: "https://cdn.simpleicons.org/anthropic/191919",
      color: "from-orange-500 to-amber-600",
      default: false,
    },
    {
      id: "langgraph",
      name: "LangGraph",
      description: "Library for building stateful, multi-actor applications with LLMs",
      icon: "",
      color: "from-blue-500 to-indigo-700",
      default: false,
    },
    {
      id: "crewai",
      name: "CrewAI",
      description: "Framework for orchestrating role-playing autonomous AI agents",
      icon: "",
      color: "from-cyan-500 to-blue-600",
      default: false,
    },
    {
      id: "none",
      name: "No AI Framework",
      description: "Skip Python AI framework selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  pythonTaskQueue: [
    {
      id: "celery",
      name: "Celery",
      description: "Distributed task queue for Python",
      icon: "https://cdn.simpleicons.org/celery/37814A",
      color: "from-green-500 to-lime-600",
      default: false,
    },
    {
      id: "none",
      name: "No Task Queue",
      description: "Skip Python task queue selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  pythonQuality: [
    {
      id: "ruff",
      name: "Ruff",
      description: "An extremely fast Python linter and code formatter",
      icon: "https://cdn.simpleicons.org/ruff/D7FF64",
      color: "from-yellow-400 to-lime-500",
      default: true,
    },
    {
      id: "none",
      name: "No Code Quality Tool",
      description: "Skip Python code quality tool selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  // Go ecosystem options
  goWebFramework: [
    {
      id: "gin",
      name: "Gin",
      description: "High-performance HTTP web framework with martini-like API",
      icon: "https://cdn.simpleicons.org/gin/00ADD8",
      color: "from-cyan-500 to-blue-600",
      default: true,
    },
    {
      id: "echo",
      name: "Echo",
      description: "High performance, minimalist Go web framework",
      icon: "",
      color: "from-blue-400 to-blue-600",
      default: false,
    },
    {
      id: "none",
      name: "No Web Framework",
      description: "Skip Go web framework selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  goOrm: [
    {
      id: "gorm",
      name: "GORM",
      description: "The fantastic ORM library for Golang",
      icon: "",
      color: "from-cyan-500 to-teal-600",
      default: true,
    },
    {
      id: "sqlc",
      name: "sqlc",
      description: "Generate type-safe Go code from SQL",
      icon: "",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "none",
      name: "No ORM",
      description: "Skip Go ORM/database layer selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  goApi: [
    {
      id: "grpc-go",
      name: "gRPC-Go",
      description: "The Go implementation of gRPC",
      icon: "/icon/grpc.svg",
      color: "from-blue-500 to-indigo-600",
      default: false,
    },
    {
      id: "none",
      name: "No API Layer",
      description: "Skip Go API layer selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  goCli: [
    {
      id: "cobra",
      name: "Cobra",
      description: "Library for creating powerful modern CLI applications",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "bubbletea",
      name: "Bubble Tea",
      description: "Powerful TUI framework based on The Elm Architecture",
      icon: "",
      color: "from-pink-500 to-rose-600",
      default: false,
    },
    {
      id: "none",
      name: "No CLI Tools",
      description: "Skip Go CLI tools selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  goLogging: [
    {
      id: "zap",
      name: "Zap",
      description: "Blazing fast, structured, leveled logging in Go",
      icon: "",
      color: "from-yellow-500 to-amber-600",
      default: true,
    },
    {
      id: "none",
      name: "No Logging Library",
      description: "Skip Go logging library selection",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
};

// Ecosystem configuration
export const ECOSYSTEMS: {
  id: Ecosystem;
  name: string;
  description: string;
  icon: string;
  color: string;
}[] = [
  {
    id: "typescript",
    name: "TypeScript",
    description: "Full-stack TypeScript ecosystem",
    icon: "https://cdn.simpleicons.org/typescript/3178C6",
    color: "from-blue-500 to-blue-700",
  },
  {
    id: "rust",
    name: "Rust",
    description: "High-performance Rust ecosystem",
    icon: "https://cdn.simpleicons.org/rust/000000",
    color: "from-orange-500 to-orange-700",
  },
  {
    id: "python",
    name: "Python",
    description: "Python full-stack ecosystem",
    icon: "https://cdn.simpleicons.org/python/3776AB",
    color: "from-blue-400 to-yellow-500",
  },
  {
    id: "go",
    name: "Go",
    description: "High-performance Go ecosystem",
    icon: "https://cdn.simpleicons.org/go/00ADD8",
    color: "from-cyan-500 to-blue-600",
  },
];

// Categories available for each ecosystem
export const ECOSYSTEM_CATEGORIES: Record<Ecosystem, TechCategory[]> = {
  typescript: [
    "webFrontend",
    "nativeFrontend",
    "astroIntegration",
    "cssFramework",
    "uiLibrary",
    "backend",
    "backendLibraries",
    "runtime",
    "api",
    "database",
    "orm",
    "dbSetup",
    "webDeploy",
    "serverDeploy",
    "auth",
    "payments",
    "email",
    "fileUpload",
    "logging",
    "observability",
    "featureFlags",
    "caching",
    "ai",
    "cms",
    "codeQuality",
    "documentation",
    "appPlatforms",
    "packageManager",
    "examples",
    "git",
    "install",
  ],
  rust: [
    "rustWebFramework",
    "rustFrontend",
    "rustOrm",
    "rustApi",
    "rustCli",
    "rustLibraries",
    "git",
    "install",
  ],
  python: [
    "pythonWebFramework",
    "pythonOrm",
    "pythonValidation",
    "pythonAi",
    "pythonTaskQueue",
    "pythonQuality",
    "git",
    "install",
  ],
  go: ["goWebFramework", "goOrm", "goApi", "goCli", "goLogging", "git", "install"],
};

export const PRESET_TEMPLATES: {
  id: string;
  name: string;
  description: string;
  stack: Partial<StackState>;
}[] = [
  {
    id: "mern",
    name: "MERN Stack",
    description: "MongoDB + Express + React + Node.js - Classic MERN stack",
    stack: {
      projectName: "my-app",
      webFrontend: ["react-router"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "node",
      backend: "express",
      database: "mongodb",
      orm: "mongoose",
      dbSetup: "mongodb-atlas",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: ["todo"],
      git: "true",
      install: "true",
      api: "orpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "pern",
    name: "PERN Stack",
    description: "PostgreSQL + Express + React + Node.js - Popular PERN stack",
    stack: {
      projectName: "my-app",
      webFrontend: ["tanstack-router"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: ["todo"],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "t3",
    name: "T3 Stack",
    description: "Next.js + tRPC + Prisma + PostgreSQL + Better Auth",
    stack: {
      projectName: "my-app",
      webFrontend: ["next"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: ["biome"],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "uniwind",
    name: "Uniwind Native",
    description: "Expo + Uniwind native app with no backend services",
    stack: {
      projectName: "my-app",
      webFrontend: ["none"],
      nativeFrontend: ["native-uniwind"],
      astroIntegration: "none",
      cssFramework: "none",
      uiLibrary: "none",
      runtime: "none",
      backend: "none",
      database: "none",
      orm: "none",
      dbSetup: "none",
      auth: "none",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: [],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "none",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "astro-react",
    name: "Astro + React",
    description: "Astro with React integration, tRPC, and Hono backend",
    stack: {
      projectName: "my-app",
      webFrontend: ["astro"],
      nativeFrontend: ["none"],
      astroIntegration: "react",
      cssFramework: "tailwind",
      uiLibrary: "daisyui",
      runtime: "bun",
      backend: "hono",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "astro-fullstack",
    name: "Fullstack Astro",
    description: "Astro with React using built-in API routes (fullstack mode)",
    stack: {
      projectName: "my-app",
      webFrontend: ["astro"],
      nativeFrontend: ["none"],
      astroIntegration: "react",
      cssFramework: "tailwind",
      uiLibrary: "daisyui",
      runtime: "none",
      backend: "self-astro",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
];

export type StackState = {
  ecosystem: Ecosystem;
  projectName: string | null;
  webFrontend: string[];
  nativeFrontend: string[];
  astroIntegration: string;
  runtime: string;
  backend: string;
  database: string;
  orm: string;
  dbSetup: string;
  auth: string;
  payments: string;
  email: string;
  fileUpload: string;
  logging: string;
  observability: string;
  featureFlags: string;
  analytics: string;
  backendLibraries: string;
  stateManagement: string;
  forms: string;
  validation: string;
  testing: string;
  realtime: string;
  jobQueue: string;
  caching: string;
  animation: string;
  cssFramework: string;
  uiLibrary: string;
  cms: string;
  codeQuality: string[];
  documentation: string[];
  appPlatforms: string[];
  packageManager: string;
  examples: string[];
  aiSdk: string;
  git: string;
  install: string;
  api: string;
  webDeploy: string;
  serverDeploy: string;
  yolo: string;
  // Rust ecosystem fields
  rustWebFramework: string;
  rustFrontend: string;
  rustOrm: string;
  rustApi: string;
  rustCli: string;
  rustLibraries: string;
  // Python ecosystem fields
  pythonWebFramework: string;
  pythonOrm: string;
  pythonValidation: string;
  pythonAi: string;
  pythonTaskQueue: string;
  pythonQuality: string;
  // Go ecosystem fields
  goWebFramework: string;
  goOrm: string;
  goApi: string;
  goCli: string;
  goLogging: string;
};

export const DEFAULT_STACK: StackState = {
  ecosystem: "typescript",
  projectName: "my-app",
  webFrontend: ["tanstack-router"],
  nativeFrontend: ["none"],
  astroIntegration: "none",
  runtime: "bun",
  backend: "hono",
  database: "sqlite",
  orm: "drizzle",
  dbSetup: "none",
  auth: "better-auth",
  payments: "none",
  email: "none",
  fileUpload: "none",
  logging: "none",
  observability: "none",
  featureFlags: "none",
  analytics: "none",
  backendLibraries: "none",
  stateManagement: "none",
  forms: "react-hook-form",
  validation: "zod",
  testing: "vitest",
  realtime: "none",
  jobQueue: "none",
  caching: "none",
  animation: "none",
  cssFramework: "tailwind",
  uiLibrary: "shadcn-ui",
  cms: "none",
  codeQuality: [],
  documentation: [],
  appPlatforms: ["turborepo"],
  packageManager: "bun",
  examples: [],
  aiSdk: "vercel-ai",
  git: "true",
  install: "true",
  api: "trpc",
  webDeploy: "none",
  serverDeploy: "none",
  yolo: "false",
  // Rust ecosystem defaults
  rustWebFramework: "axum",
  rustFrontend: "none",
  rustOrm: "sea-orm",
  rustApi: "none",
  rustCli: "none",
  rustLibraries: "serde",
  // Python ecosystem defaults
  pythonWebFramework: "fastapi",
  pythonOrm: "sqlalchemy",
  pythonValidation: "pydantic",
  pythonAi: "none",
  pythonTaskQueue: "none",
  pythonQuality: "ruff",
  // Go ecosystem defaults
  goWebFramework: "gin",
  goOrm: "gorm",
  goApi: "none",
  goCli: "none",
  goLogging: "zap",
};

export const isStackDefault = <K extends keyof StackState>(
  stack: StackState,
  key: K,
  value: StackState[K],
): boolean => {
  const defaultValue = DEFAULT_STACK[key];

  if (stack.backend === "convex") {
    if (key === "runtime" && value === "none") return true;
    if (key === "database" && value === "none") return true;
    if (key === "orm" && value === "none") return true;
    if (key === "api" && value === "none") return true;
    if (key === "auth" && value === "none") return true;
    if (key === "dbSetup" && value === "none") return true;
  }

  if (
    key === "webFrontend" ||
    key === "nativeFrontend" ||
    key === "codeQuality" ||
    key === "documentation" ||
    key === "appPlatforms" ||
    key === "examples"
  ) {
    if (Array.isArray(defaultValue) && Array.isArray(value)) {
      const sortedDefault = [...defaultValue].sort();
      const sortedValue = [...value].sort();
      return (
        sortedDefault.length === sortedValue.length &&
        sortedDefault.every((item, index) => item === sortedValue[index])
      );
    }
  }

  if (Array.isArray(defaultValue) && Array.isArray(value)) {
    const sortedDefault = [...defaultValue].sort();
    const sortedValue = [...value].sort();
    return (
      sortedDefault.length === sortedValue.length &&
      sortedDefault.every((item, index) => item === sortedValue[index])
    );
  }

  return defaultValue === value;
};
