// Resolved from this file's directory (apps/web/src/lib), so four levels up
// reaches the repo root. templates-binary/ is generated by the
// template-generator prebuild, which runs before the web build.
const binaryTemplateModules = import.meta.glob(
  "../../../../packages/template-generator/templates-binary/**/*",
  {
    eager: true,
    import: "default",
    query: "?url",
  },
) as Record<string, string>;

const BINARY_TEMPLATE_MARKER = "templates-binary/";

const binaryTemplateUrls = new Map(
  Object.entries(binaryTemplateModules).map(([modulePath, url]) => [
    modulePath.slice(modulePath.indexOf(BINARY_TEMPLATE_MARKER) + BINARY_TEMPLATE_MARKER.length),
    url,
  ]),
);

export async function loadBinaryTemplate(sourcePath: string): Promise<Uint8Array> {
  const url = binaryTemplateUrls.get(sourcePath);
  if (!url) {
    throw new Error(`Missing browser binary template: ${sourcePath}`);
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to load browser binary template: ${sourcePath}`);
  }

  return new Uint8Array(await response.arrayBuffer());
}
