// Generated by apps/docs/scripts/generate-docs.ts. Do not edit by hand.

export const OPTION_ENTRY_COUNT = 424;
export const ECOSYSTEM_COUNT = 5;
export const ECOSYSTEM_NAMES = ["TypeScript","Rust","Python","Go","Java"] as const;
