import {
  ECOSYSTEM_COUNT,
  ECOSYSTEM_NAMES,
  OPTION_ENTRY_COUNT,
} from "./project-stats.generated";

export { ECOSYSTEM_COUNT, ECOSYSTEM_NAMES, OPTION_ENTRY_COUNT };

export const OPTION_COUNT_LABEL = `${OPTION_ENTRY_COUNT}`;

export const ECOSYSTEM_COUNT_LABEL = `${ECOSYSTEM_COUNT}`;
