import type { OptionCategory } from "@better-fullstack/types";

import type { StackState } from "@/lib/stack-defaults";

export const NON_OPTION_STACK_KEYS = ["ecosystem", "projectName", "yolo"] as const;

export const STACK_STATE_OPTION_CATEGORY_BY_KEY: Record<
  Exclude<keyof StackState, (typeof NON_OPTION_STACK_KEYS)[number]>,
  OptionCategory
> = {
  webFrontend: "webFrontend",
  nativeFrontend: "nativeFrontend",
  astroIntegration: "astroIntegration",
  runtime: "runtime",
  backend: "backend",
  database: "database",
  orm: "orm",
  dbSetup: "dbSetup",
  auth: "auth",
  payments: "payments",
  email: "email",
  fileUpload: "fileUpload",
  logging: "logging",
  observability: "observability",
  featureFlags: "featureFlags",
  analytics: "analytics",
  backendLibraries: "backendLibraries",
  stateManagement: "stateManagement",
  forms: "forms",
  validation: "validation",
  testing: "testing",
  realtime: "realtime",
  jobQueue: "jobQueue",
  caching: "caching",
  i18n: "i18n",
  animation: "animation",
  cssFramework: "cssFramework",
  uiLibrary: "uiLibrary",
  shadcnBase: "shadcnBase",
  shadcnStyle: "shadcnStyle",
  shadcnIconLibrary: "shadcnIconLibrary",
  shadcnColorTheme: "shadcnColorTheme",
  shadcnBaseColor: "shadcnBaseColor",
  shadcnFont: "shadcnFont",
  shadcnRadius: "shadcnRadius",
  cms: "cms",
  search: "search",
  fileStorage: "fileStorage",
  codeQuality: "codeQuality",
  documentation: "documentation",
  appPlatforms: "appPlatforms",
  packageManager: "packageManager",
  versionChannel: "versionChannel",
  examples: "examples",
  aiSdk: "ai",
  aiDocs: "aiDocs",
  git: "git",
  install: "install",
  api: "api",
  webDeploy: "webDeploy",
  serverDeploy: "serverDeploy",
  rustWebFramework: "rustWebFramework",
  rustFrontend: "rustFrontend",
  rustOrm: "rustOrm",
  rustApi: "rustApi",
  rustCli: "rustCli",
  rustLibraries: "rustLibraries",
  rustLogging: "rustLogging",
  rustErrorHandling: "rustErrorHandling",
  rustCaching: "rustCaching",
  rustAuth: "rustAuth",
  pythonWebFramework: "pythonWebFramework",
  pythonOrm: "pythonOrm",
  pythonValidation: "pythonValidation",
  pythonAi: "pythonAi",
  pythonAuth: "pythonAuth",
  pythonTaskQueue: "pythonTaskQueue",
  pythonGraphql: "pythonGraphql",
  pythonQuality: "pythonQuality",
  goWebFramework: "goWebFramework",
  goOrm: "goOrm",
  goApi: "goApi",
  goCli: "goCli",
  goLogging: "goLogging",
  goAuth: "goAuth",
};

export const VIRTUAL_NONE_MULTI_SELECT_STACK_KEYS = [
  "rustLibraries",
  "pythonAi",
  "aiDocs",
] as const;

export function usesVirtualNoneSelection(
  key: keyof StackState,
): key is (typeof VIRTUAL_NONE_MULTI_SELECT_STACK_KEYS)[number] {
  return (VIRTUAL_NONE_MULTI_SELECT_STACK_KEYS as readonly string[]).includes(key);
}
