export {
  NON_OPTION_STACK_SELECTION_KEYS as NON_OPTION_STACK_KEYS,
  STACK_SELECTION_OPTION_CATEGORY_BY_KEY as STACK_STATE_OPTION_CATEGORY_BY_KEY,
  VIRTUAL_NONE_MULTI_SELECT_STACK_SELECTION_KEYS as VIRTUAL_NONE_MULTI_SELECT_STACK_KEYS,
  usesVirtualNoneStackSelection as usesVirtualNoneSelection,
} from "@better-fullstack/types/stack-translation";
